<?php
use Application\Helper\Common;

$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch();
if ($routeMatch) {
    $routeName = $routeMatch->getMatchedRouteName();
} else {
    $routeName = '404';
}
$currentRoute = explode('/', $routeName);
$currentParentRoute = $currentRoute[0];
$parentRoute = $this->route;
$routes = $this->config('router')['routes'][$parentRoute];
$currentSlug = $routeMatch ? $routeMatch->getParams('slug', null) : null;
$arrayLink = [];

$activeMenu = false;
if (isset($custom_links)) {
    foreach ($routes['custom_links'] as $link) {
        $arrayLink[] = $link['link']['en'];
        $arrayLink[] = $link['link']['ar'];
    }
    if (in_array($currentSlug, $arrayLink)) {
        $activeMenu = true;
    }
}
?>

<li class="<?php echo $parentRoute ?> dropdown<?php echo ($currentParentRoute == $parentRoute || $activeMenu) ? ' active current-menu-item' : '' ?>">
    <a data-toggle="dropdown" href="<?php echo $this->url($parentRoute) ?>">
        <?php echo $this->translate(Common::getNameFromRoute($parentRoute)) ?>
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">

        <!-- Custom pages were set in landing module config route -->
        <?php if (isset($routes['custom_links'])) : ?>
            <?php
            foreach ($routes['custom_links'] as $link) :
                $url =  (Locale::getPrimaryLanguage(Locale::getDefault()) == 'en') ? $link['link']['en'] : $link['link']['ar'];
            ?>
                <li class="<?php echo $url ?> <?php echo ($currentSlug == $url) ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('blog/view', ['slug' => $url]) ?>">
                        <?php echo $this->translate($link['label']) ?>
                    </a>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>

        <!-- Child menus for child_routes -->
        <?php
        foreach ($routes['child_routes'] as $k => $route) :
            $currentRoute = $parentRoute . '/' . $k;
            ?>
            <?php if (!isset($route['hide'])) :  // hide route on navigation ?>
            <li<?php echo ($routeName == $currentRoute) ? ' class="active '.$k.'"' : ' class="'.$k.'"' ?>>
                <a href="<?php echo $this->url($currentRoute) ?>">
                    <?php echo $this->translate(Common::getNameFromRoute($route['options']['route'])) ?>
                </a>
            </li>
        <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</li>