<?php
use Application\Helper\Common;

//var_dump($this->routes);die;
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch()->getMatchedRouteName();
$currentRoute = explode('/', $routeName);
$currentParentRoute = $currentRoute[0];
$parentRoute = $this->route;
$routes = $this->config('router')['routes'][$parentRoute];

?>
<li class="dropdown<?php echo ($currentParentRoute == $parentRoute) ? ' active current-menu-item' : '' ?>">
    <a data-toggle="dropdown" href="<?php echo $this->url($parentRoute) ?>">
        <?php echo $this->translate(Common::getNameFromRoute($parentRoute)) ?>
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
        <?php
        foreach ($routes['child_routes'] as $k => $route) :
            $currentRoute = $parentRoute . '/' . $k;
            ?>
            <li<?php echo ($routeName == $currentRoute) ? ' class="active"' : '' ?>>
                <a href="<?php echo $this->url($currentRoute) ?>">
                    <?php echo $this->translate(Common::getNameFromRoute($route['options']['route'])) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</li>