<?php
use Application\Helper\Common;

//var_dump($this->routes);die;
$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$routeName = $routeMatch->getMatchedRouteName();

$currentRoute = explode('/', $routeName);
$currentSlug = $routeMatch->getParam('slug', null);
$parentRoute = (Common::getParentMenuFromSlug($currentSlug, $this->config('router'))) ?
    Common::getParentMenuFromSlug($currentSlug, $this->config('router')) :
    $currentRoute[0];
$routes = $this->config('router')['routes'][$parentRoute];

if ($routeMatch) {
    $routeName = $routeMatch->getMatchedRouteName();
    $currentSlug = $routeMatch->getParam('slug', null);
} else {
    $routeName = '404';
    $currentSlug = null;
}
if ($routeName == 'blog/view') {
    $urlKey = $currentSlug;
} else {
    $urlKey = $routeName;
}
//var_dump($urlKey);die;
$em = $this->em();
$currentMenu = $em->getRepository('Landing\Entity\Menu')->createQueryBuilder('m')
    ->where('m.value = :key')
    ->setParameter(':key', $urlKey)
    ->orwhere('m.valueAr = :keyar')
    ->setParameter(':keyar', $urlKey)
    ->getQuery()
    ->getResult();
//var_dump($currentMenu);die;
if (!empty($currentMenu)) {
    $parentMenu = $currentMenu[0]->getParentMenu() ? $currentMenu[0]->getParentMenu() : $currentMenu[0];
}
?>
<?php if (!empty($currentMenu)) : ?>
    <?php echo $this->renderMenu($routeMatch, 'sidebar') ?>
<?php else : ?>
<div class="list-group panel default-panel">
    <?php if ($parentRoute != 'mission') : ?>
    <div class="panel-heading">
        <a href="<?php echo $this->url($parentRoute) ?>"
           title="<?php echo $this->translate(Common::getNameFromRoute($parentRoute)) ?>">
            <?php echo $this->translate(Common::getNameFromRoute($parentRoute)) ?>
        </a>
    </div>
    <?php endif; ?>

    <!-- Custom pages were set in landing module config route -->
    <?php if (isset($routes['custom_links'])) : ?>
        <?php
        foreach ($routes['custom_links'] as $link) :
            $url =  (Locale::getPrimaryLanguage(Locale::getDefault()) == 'en') ? $link['link']['en'] : $link['link']['ar'];
            ?>
            <a class="list-group-item<?php echo ($currentSlug == $url) ? ' active' : '' ?>"
                href="<?php echo $this->url('blog/view', ['slug' => $url]) ?>">
                <?php echo $this->translate($link['label']) ?>
            </a>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- Child menus for child_routes -->
    <?php
    foreach ($routes['child_routes'] as $k => $route) :
        $currentRoute = $parentRoute . '/' . $k;
        ?>
        <?php if (!isset($route['hide']) && strtolower($route['type']) != 'segment') :  // hide route on navigation ?>
        <a class="list-group-item<?php echo ($routeName == $currentRoute) ? ' active' : '' ?>"
           href="<?php echo $this->url($currentRoute) ?>"
           title="<?php echo $this->translate(Common::getNameFromRoute($route['options']['route'])) ?>">
            <?php echo $this->translate(Common::getNameFromRoute($route['options']['route'])) ?>
        </a>
    <?php endif; ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>