<?php $this->headTitle($this->translate('Edit Menu "'. $this->title .'"')) ?>
<?php $this->headScript()
    ->prependFile('/js/admin/menu/modal.js')
    ->prependFile('http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js')
;
?>
    <h1 class="text-center"><?php echo $this->translate('Edit Menu "' . $this->title . '"') ?></h1>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>

<?php
/** @var \Zend\Form\Element $element */
foreach($form->getElements() as $element): ?>
    <?php
    $messages = $element->getMessages()
    ?>
    <div class="form-group<?php if($messages) echo " has-error" ?>">
        <?php if($messages): ?>
            <?php foreach($messages as $message): ?>
                <div class="col-md-3">&nbsp;</div>
                <div class="alert-danger col-md-7">
                    <?php if (is_array($message)): ?>
                        <?php
                        foreach ($message as $k=>$mess) {
                            echo $mess . '<br />';
                        }
                        ?>
                    <?php else: ?>
                        <?php echo $message ?>
                    <?php endif; ?>
                </div>
            <?php endforeach;?>
        <?php endif; ?>
        <?php if ($element->getName() == 'showMenu') : ?>
            <div class="col-md-3">
                &nbsp;
            </div>
            <div class="col-md-7">
                <div class="checkbox">
                    <label class="control-label col-md-3">
                        <?php
                        //var_dump($element->getValue());die;
                        $checked =  $element->getValue() ? ' checked="checked"' : '' ?>
                        <input<?php echo $checked ?> name="showMenu" type="checkbox" value="1" />
                        <?php echo $element->getLabel() ?>
                    </label>
                </div>
            </div>
        <?php else : ?>
            <label class="control-label col-md-3"><?php echo $element->getLabel() ?></label>
            <div class="col-md-7">
                <?php echo $this->formElement($element); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach;?>

<?php echo $this->form()->closeTag(); ?>

<div id="search-url-key" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Select <span class="type"></span></h4>
            </div>
            <div class="modal-body">
                <p>
                    Search your <span class="type"></span> by title
                <form role="form" class="form">
                    <div class="form-group">
                        <input id="search-box" class="form-control" type="text" name="s" />
                    </div>
                </form>
                </p>
                <div class="result">
                    <p class="text-info">
                        Choose <span class="type"></span> by click on title below here
                    </p>
                    <div class="response">

                    </div>
                </div>
            </div>
            <!--
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
            -->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->