<?php
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch()->getMatchedRouteName();
$modules = explode('/', $routeName);
$module = isset($modules[1]) ? $modules[1] : null;
?>

<ul class="nav navbar-nav">
    <li class="<?php echo ($module == 'dashboard') ? ' active' : '' ?>">
        <a href="/admin/dashboard">Dashboard</a>
    </li>
    <li class="dropdown<?php echo ($module == 'category') ? ' active' : '' ?>">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Category <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="/admin/category/new">Add a Category</a>
            </li>
            <li>
                <a href="/admin/category">Categories Manager</a>
            </li>
        </ul>
    </li>
    <li class="dropdown<?php echo ($module == 'blog') ? ' active' : '' ?>">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Blog <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="/admin/blog/new">Add News</a>
            </li>
            <li>
                <a href="/admin/blog">News Manager</a>
            </li>
        </ul>
    </li>
    <li class="dropdown<?php echo ($module == 'mission-category') ? ' active' : '' ?>">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Mission Category <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="<?php echo $this->url('zfcadmin/mission-category/new') ?>">Add a Category</a>
            </li>
            <li>
                <a href="<?php echo $this->url('zfcadmin/mission-category') ?>">Categories Manager</a>
            </li>
            <li>
                <a href="<?php echo $this->url('zfcadmin/mission-category/static/new') ?>">Add New Static Page</a>
            </li>
            <li>
                <a href="<?php echo $this->url('zfcadmin/mission-category/static') ?>">Mission Static Pages Manager</a>
            </li>
        </ul>
    </li>
    <li class="dropdown<?php echo ($module == 'mission-blog') ? ' active' : '' ?>">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Mission Blog <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="<?php echo $this->url('zfcadmin/mission-blog/new') ?>">Add News</a>
            </li>
            <li>
                <a href="<?php echo $this->url('zfcadmin/mission-blog') ?>">News Manager</a>
            </li>
        </ul>
    </li>
    <li class="dropdown<?php echo ($module == 'moderator') ? ' active' : '' ?>">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Moderator <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="<?php echo $this->url('zfcadmin/moderator/create') ?>">Add Moderator</a>
            </li>
            <li>
                <a href="<?php echo $this->url('zfcadmin/moderator') ?>">Moderators Manager</a>
            </li>
        </ul>
    </li>
</ul>

<?php if ($this->zfcUserIdentity()) : ?>
<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">System <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="<?php echo $this->url('zfcadmin/menu') ?>">Menu Manager</a>
            </li>
	    <li>
                <a href="<?php echo $this->url('zfcadmin/menu', ['action' => 'new']) ?>">Add Menu</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Account <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="<?php echo $this->url('zfcuser/changepassword') ?>">Change password</a>
            </li>
            <li>
                <a href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a>
            </li>
        </ul>
    </li>
</ul>
<?php endif; ?>
