<?php $this->headTitle(sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName())) ?>
<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dd class="form-group"><?php echo $this->formInput($form->get('identity')); ?></dd>

<dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
<dd class="form-group"><?php
echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
<dd class="form-group"><?php
echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
?></dd>

<dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
<dd class="form-group"><?php
echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
?></dd>

<dd class="form-group"><?php
//echo $this->formInput($form->get('csrf'));
echo $this->formInput($form->get('submit')->setAttribute('class', 'btn btn-primary'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>
