<div class="container clearfix">
    <div class="col-xs-3">
        <h3 class="white-head"><?php echo $this->translate('Site Map') ?></h3>
        <ul>
            <li>
                <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('the-ministry') ?>"><?php echo $this->translate('The Ministry') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('foreign-policy') ?>">
                    <?php echo $this->translate('Foreign Policy') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('about-iraq') ?>"><?php echo $this->translate('About Iraq') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('diplomatic-missions') ?>">
                    <?php echo $this->translate('Diplomatic Missions') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('consular-services') ?>">
                    <?php echo $this->translate('Consular Services') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('contact-us') ?>"><?php echo $this->translate('Contact Us') ?></a>
            </li>
        </ul>
    </div>
    <div class="col-xs-5 clearfix">
        <h3 class="white-head"><?php echo $this->translate('Links') ?></h3>
        <div class="col-xs-6">
            <ul>
                <li>
                    <a href="<?php echo $this->url('about-iraq/constitution') ?>">
                        <?php echo $this->translate('Iraq\'s Constitution') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('about-iraq/investment') ?>">
                        <?php echo $this->translate('Investment in Iraq') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('about-iraq/encyclopedia') ?>">
                        <?php echo $this->translate('Iraq Encyclopedia') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('about-iraq/tourist-guide') ?>">
                        <?php echo $this->translate('Tourist Guide') ?></a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6">
            <ul>
                <li>
                    <a href="<?php echo $this->url('foreign-policy/arab-league') ?>">
                        <?php echo $this->translate('Arab League') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('foreign-policy/economic-rehabilitation') ?>">
                        <?php echo $this->translate('Economic Rehabilitation') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('foreign-policy/human-rights') ?>">
                        <?php echo $this->translate('Human Rights') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('foreign-policy/international-organizations') ?>">
                        <?php echo $this->translate('International Organizations') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('foreign-policy/iraq-s-security') ?>">
                        <?php echo $this->translate('Iraq\'s Security') ?></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-xs-4 clearfix">
        <div class="col-xs-6">
            <h3 class="white-head"><?php echo $this->translate('Languages') ?></h3>
            <ul>
                <li>
                    <a href="/"><?php echo $this->translate('English') ?></a>
                </li>
                <li>
                    <a href="/ar/"><?php echo $this->translate('عربي') ?></a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 text-center">
            <a href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('/trash/images/logo.png') ?>" alt="Republic of Iraq"/>&nbsp;
            </a>
            <p class="site-title">
                <?php echo $this->translate('Republic of Iraq') ?><br />
                <?php echo $this->translate('Ministry of Foreign Affairs') ?>
            </p>
        </div>
    </div>
</div>