<?php
/** @var \Blog\Entity\Blog $blog */
$blog = $this->blog;
?>
<div class="well clearfix article article<?php echo $blog->getId() ?>">
    <div class="media-object photo col-xs-4">
        <a href="<?php echo $blog->getUrl() ?>" class="news-photo" title="<?php echo $blog->getTitle() ?>">
            <img alt="" src="<?php echo $blog->getThumbnail() ?>" />
        </a>
    </div>
    <div class="media-body col-xs-8">
        <a href="<?php echo $blog->getUrl() ?>" class="media-heading" title="<?php echo $blog->getTitle() ?>">
            <h3>
                <?php echo $blog->getTitle() ?>
            </h3>
        </a>
        <div class="short-description">
            <?php echo $blog->getShortContent() ?>
        </div>
        <div class="author-date">
            <span class="date">
                <i class="glyphicon glyphicon-calendar"></i>
                <?php echo $blog->getExactCreateTime() ?>
            </span>
            |
            <span class="author">
                <i class="glyphicon glyphicon-user"></i>
                <?php echo sprintf($this->translate('Written by %s'), $blog->getCreateUser()->getDisplayName()) ?>
            </span>
        </div>
    </div>
</div>