<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Untitled Document</title>
    <style type="text/css">
        .side_elements {
            width: 100%;
            color: #000000;
        }

        .side_elements #Accordion1 .ui-helper-reset.ui-state-default {
            padding: 0;
            text-align: center;
            font-family: arial;
        }

        .ui-state-default a {
            font-size: 12px;
        }
    </style>
    <link href="/menu/jQueryAssets/jquery.ui.core.min.css" rel="stylesheet" type="text/css">
    <link href="/menu/jQueryAssets/jquery.ui.theme.min.css" rel="stylesheet" type="text/css">
    <link href="/menu/jQueryAssets/jquery.ui.accordion.min.css" rel="stylesheet" type="text/css">
    <script src="/menu/jQueryAssets/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/menu/jQueryAssets/jquery.ui-1.10.4.accordion.min.js" type="text/javascript"></script>
</head>

<body>
<div class="side_elements">
    <div id="Accordion1">
        <h3><a href="#"><strong><?php echo $this->translate('The Minister') ?></strong></a></h3>

        <div>
            <p><img src="/menu/accordion/41.jpg" width="240" alt=""/></p>

            <p><?php echo $this->translate('Name: Dr. Ibrahim al-Jaafari') ?></p>
            <ul>
                <li>
                    <p><?php echo $this->translate('Iraqi Foreign Ministry.') ?></p>
                </li>
                <li>
                    <p><?php echo $this->translate('Former Iraqi Prime Minister.') ?> <strong><a
                            href="http://www.beladitvnews.com/the-ministry/the-minister"><font color="#D0171B"><?php echo $this->translate('Read more') ?></font></a></strong></p>
                </li>
            </ul>
        </div>
        <h3><a href="#"><strong><?php echo $this->translate('Iraq\'s Constitution') ?></strong></a></h3>

        <div>
            <p><?php echo $this->translate('In the name of God, the Most merciful, the Most compassionate') ?></p>

            <p>"<?php echo $this->translate('We have honored the sons of Adam') ?>"</p>

            <p><?php echo $this->translate('Preamble') ?></p>

            <p><?php echo $this->translate('We, the people of Mesopotamia, the homeland of the apostles and prophets, resting place of the virtuous
                imams, cradle of civilization, crafters of writing, and home of numeration.') ?></p>

            <p><?php echo $this->translate('Upon our land the first law made by man was passed, and the oldest pact of just governance was inscribed,
                and upon our soil the saints and companions of the Prophet prayed') ?></p>

            <p><strong><a href="http://www.beladitvnews.com/about-iraq/constitution"><font color="#D0171B"><?php echo $this->translate('Read more') ?></font></a></strong></p>
        </div>

        <h3><a href="#"><?php echo $this->translate('Iraq Encyclopediaa') ?></a></h3>

        <div>
            <p><?php echo $this->translate('-Content 3DAILY AVERAGE OF TEMPERATURES (CENTIGRADE) AND RELATIVE HUMIDITY FOR BAGHDAD CITY BY MONTH FOR
                THE YEAR 2009') ?></p>

            <p><?php echo $this->translate('-RAINFALL, ANNUAL AVERAGE OF RELATIVE HUMIDITY AND TEMPERATURES FOR THE YEARS 1999-2009') ?></p>

            <p><?php echo $this->translate('-POPULATION OF IRAQ FOR THE YEARS 1977 - 2011.') ?></p>

            <p><?php echo $this->translate('-AREA, YIELD AND PRODUCTION FOR CROPS AND VEGETABLES FOR THE YEAR 2010.') ?></p>

            <p><?php echo $this->translate('-No. OF HOLDINGS AND PALMS BY SEX ON NATIONAL LEVEL AND GOVERNORATES ACCORDING TO THE AGRICULTURAL
                CENSUSES FOR THEYEAR 2001.') ?></p>

            <p><?php echo $this->translate('-PRODUCTION OF DATES BY KINDS FOR THE YEARS 2000 -2010 (10 Ton).') ?></p>

            <p>.<strong><a href="http://www.beladitvnews.com/about-iraq/encyclopedia"><font color="#D0171B"><?php echo $this->translate('Read more') ?></font></a></strong></p>
        </div>
        <h3><a href=""/Documentfiles/connection.jpg""><?php echo $this->translate('International Conventions') ?></a></h3>

        <div>
            <p><strong><a href="/documentfiles/un_charter.pdf"><font color="#D0171B"><?php echo $this->translate('The UN Charter') ?></font></a></strong>
            </p>

            <p><strong><a href="/documentfiles/vinen.pdf"><font color="#D0171B"><?php echo $this->translate('The First Geneva
                Convention') ?></font></a></strong></p>

            <p><strong><a href="/documentfiles/vinen.pdf"><font color="#D0171B"><?php echo $this->translate('The Second Geneva Convention') ?></font></a></strong>
            </p>

            <p><strong><a href="/documentfiles/vinenc.pdf"><font color="#D0171B"><?php echo $this->translate('The Third Geneva Convention') ?></font></a></strong>
            </p>

            <p><strong><a href="/documentfiles/vinen.pdf"><font color="#D0171B"><?php echo $this->translate('The Fourth Geneva Convention') ?></font></a></strong>
            </p>

            <p><strong><a href="/documentfiles/vinenc.pdf"><font color="#D0171B"><?php echo $this->translate('Consular Relations') ?></font></a></strong>
            </p>

            <p><strong><a href="/documentfiles/vinend.pdf"><font color="#D0171B"><?php echo $this->translate('Diplomatic
                Relations') ?></font></a></strong></p>
        </div>
        <h3><a href="#"><strong><?php echo $this->translate('Security Council Resolutions') ?></strong></a></h3>

        <div></strong></p>
            <strong><a href="http://www.beladitvnews.com/foreign-policy/security-council-resolutions"><font
                    color="#D0171B"><?php echo $this->translate('Diplomatic Relations') ?></font></a></strong></div>
        <h3><a href="#"><strong><?php echo $this->translate('The New Iraq') ?></strong></a></h3>

        <div>
            <p><?php echo $this->translate('•The new Iraq inherited a heavy legacy of hostility and distrust as a result of the irresponsible
                policies of the former regime towards the neighboring and far countries which led to a decline in the
                country\'s position in the international community. <br>
                •The Foreign Ministry in the new Iraq faced these challenges and still, to address that legacy in a bid
                to retrieve \'s position that befits rich civilization heritage and its people and its riches. <br>
                •As representatives of the new Iraq, we have actively and successfully worked on removing the isolation
                condition to achieve the goals of our foreign policy in a responsible vision in accordance with the
                following:') ?>  <strong><a href="http://www.beladitvnews.com/foreign-policy/the-new-iraq"><font
                        color="#D0171B"><?php echo $this->translate('Read more') ?></font></a></strong></p>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#Accordion1").accordion({
            heightStyle: "content"
        });
    });
</script>
</body>
</html>
