<?php $this->headTitle($this->translate('Approving Corpse Entry To Iraq')) ?>
<h1><?php echo $this->translate('Approving Corpse Entry To Iraq') ?></h1>

<p> <?php echo $this->translate('Approving Corpse Entry to Iraq<br><br>For Iraqis or Muslims from other nationalities who
    want to bury their dead people in Iraq, the consular section do the following steps : -<br>1
    . The Embassy asks for the death certificate that has already been approved by the
    specialized institutions.<br>2 . The Embassy sent a telegram (includes the following
    information: name of the deceased - nationality of the deceased – his date of birth _ the
    date of death - Cause of death - place of death) to the Consular Department in the Ministry
    requesting approval to enter the body.<br>3 . When receiving the Ministry\'s reply (after
    obtaining the approval of the Ministry of Health ),The Mission do the following steps :
    -<br>a-Ratifying the death certificate of the foreigner and delivered it to his relatives ,
    ratifying the Iraqi death certificate and the issues an Iraqi death certificate and give it
    to his family .<br>b- if the relatives of the foreigner deceased, who is not of Iraqi
    origin, to bury him in Iraq, they need to get approval of the Iraqi Ministry of Health,
    after that the mission ratifies the foreign death certificate and take the sum of ( 3200 )
    U.S. $ as entry fee according to Article no. 61 of the Public Health Law No. ( 89 ) in 1981
    and granting an escort visa to Iraq .<br>c- Preparing a facilitating letter to enter the
    body addressing the relevant health authorities at the borders or airports ( including the
    approval from the Ministry of Foreign Affairs / Consular Department mentioned in its
    telegram ) .<br>d- The consul or his nominee should be existed in the place where the body
    located for the purpose of sealing the coffin with red wax.<br>4 . The Public Health Law
    instructs that If the body could not be moved for any reason at the time, it was not
    permissible to bring out the body from the grave and moved it to Iraq only a year after the
    date of burial.') ?>'<br>