<?php $this->headTitle($this->translate('Authorization')) ?>
<h1><?php echo $this->translate('Authorization') ?></h1>

<p><span style="font-weight: bold;"><span style="text-decoration: underline;">
            <?php echo $this->translate('Legal Authorization') ?><br><br></span></span>
    <?php echo $this->translate('First:
    the issuance of authorizations (general and limited)<br> A large numbers of
    citizens residing abroad need to grant general or limited authorizations to
    be used by the people inside Iraq. The Consul needs to consider the
    following:<br> 1. The authorization cannot be issued the Iraqi citizen still
    has the Iraq IDs.<br> 2. The authorizations are of two types: A- General
    authorization: authorizes the person who gets it the right to dispose all
    properties of the person who authorizes him. Therefore, granting it must be
    accurate. This authorization does not expire unless it is abolished by the
    authorizer through filling out the application form for dismissing the
    authorized (notification and dismissal document) and attaching (informing
    notice) in accordance to the templates in the embassy. The general
    authorization is of two types (authorizing a person/model template 12 1)
    (authorizing a lawyer/template 12-2) the photos of the authorizer and the
    authorized are put and stamped.<br> B- Limited authorization: given for one
    or several specific issues, which gives the authorized a limited right to
    dispose within the specified issues, work, repercussions as required by the
    type of work or custom. For the purpose of following up a specific task or
    accomplish a specific job and ends with the end of its purpose (template No.
    13).<br> <br> C- For both general and limited authorization, a fee is paid
    upon ratification, which differs in the amount from one to another in a
    receipt (37 a).<br> <br> 3. The authorization is of 3 copies and is signed
    by the authorize himself. The first copy is given authorizer, the second is
    kept in the authorizations record, and the third is kept in a special
    file.<br> <br> 4. The general and limited authorization is made for one or
    several authorized persons, in case there were several persons in one
    authorization, then, they are not allowed to work individually unless
    expressly stated in the authorization. Also, the authorization may be
    written by more than one person, in this case the fees are collected
    depending on the number of the authorized, as if each one of them has a
    separate authorization.<br> <br> <br> Second, procedure followed for issuing
    authorizations<br> <br> 1. When the applicant submits his/her request, the
    Consul checks the applicant\'s IDs such as the nationality card (Jinsiya) and
    nationality certificate (shahadat Al jinsiya).<br> 2. The Consul read out
    the authorization to the applicant and its type (general - limited) the
    authorizer recognizes signs it in front of the consul.<br> 3. The Consul
    fills his/her part of the authorization, namely, (I certify that …. the
    authorizer in this authorization is Mr. …. Identified by the (Jinsiya or
    shahadat Al jinsiya) dated …. Numbered ...... issued on ........ from the
    province of ……… and I have read out the authorization items on .. /.. /200..
    The Name of the Consul................. signature and stamp of the
    Consulate.<br> 4. The Consul must write the full name of the authorizer and
    his/her permanent address and number and date of jinsiya and shahadat Al
    jinsiya.<br> 5. Writing down the authorization in the register of
    authorizations and give it a number and date of issuance, and the signature
    of the authorizer in the register.<br> 6. The first copy of the
    authorization is attached in the register and stamped equally between the
    register and the authorization. The general number of the authorization is
    the page number of the register and the register number, on the cover of the
    register. The register is full during the year, another register is opened
    number (2) and so the number of the page.<br> <br> Third, instructions for
    issuing authorizations<br> A. The authorizer must appear in person in front
    of the Consul when issuing authorization.<br> B. The full information for
    the authorizer must be written in the register depending on nationality card
    (Jinsiya) and nationality certificate (shahadat Al jinsiya) and not to rely
    on the passport (writing the number and date of release for each of the
    nationality card (Jinsiya) and nationality certificate (shahadat Al jinsiya)
    as the real estate departments rely during the purchase transaction on the
    nationality card (Jinsiya) and nationality certificate (shahadat Al jinsiya)
    to compare it with the information in the authorization.<br> C. Personal
    photo of the authorizer is glued and stamped by the consulate stamp.<br> D.
    The number of the real estate must be written in full as in the deed (number
    of the land and district) not just the address (street, area, house) in case
    of the limited authorizations.<br> E. Accuracy in information of the
    authorizers and the authorized and the details of the authorizations.<br> E.
    Preferably, the signature of the authorizer must be in Arabic.<br> F.
    Preferably, a copy of the legal share holders and the deed must be attached.<br>
    G. Updated life certificate must be attached.<br> (Consular Department
    letter No. 8/9/1/68076 of 24/4/2008)<br> <br> Note on issuing endorsement
    from the authorizer:<br> In order to reduce forgery, the Directorate of Real
    Estate Registration asked that an a printed endorsement must be attached
    with each authorization to sell a property from the authorizer to the
    authorized and signed by him in addition to the left thumb print on the
    endorsement. It must be signed and stamped by the Consul and write the full
    address and phone number of the authorizer on the endorsement letter. The
    Mission keeps a copy of the endorsement and the authorization for reference
    when needed, according to the attached form number (1).<br> (Consular
    Department letter No. 8/9/1/85079 on 30/8/2010)<br> (Consular Department
    letter No. 6/9/1/18840 on 24/5/2011)<br> <br> Fourth: vehicles selling
    authorizations<br> For the documentation of the selling a vehicle or usage
    authorization on behalf of the rightful owner, the vehicle number and year
    of manufacture, color, and number of the VIN and engine. The authorization
    needs to be stamped by the Directorate of Traffic / computer in order to
    become effective. Three types of authorizations are used and according to
    the attached forms that are different from one to another, according to the
    purpose as follows: -<br> 1. Model (1) is used for selling and driving
    vehicles.<br> 2. Model number (2) is used for driving a vehicle.<br> 3.
    Model No. (3) for purchase and registration of a vehicle.<br> <br> <br> As
    for the vehicles that were not recorded in Iraq and recently entered, the
    authorization model No. (4) is used.<br> Consular Department letter
    number:<br> 8/4/22/74285 on 13/5/2010<br> 8/4/2/c/86950 on 11/6/2009<br>
    <br> Fifth: Cancelling Authorizations<br><br> Cancelling the authorization
    in accordance with the provisions of the civil law is done by the authorizer
    by filling template number (1) for the cancelling the authorized in an
    accurate way in addition to sending template number (2) to notify the
    authorized that is stamped by the consular stamp and the name and signature
    of the Consul to notify the authorized by the Ministry of Justice /
    Department of Legal Notary.<br> A passport copy is sent with the template.
    The fee for the template is taken which is 350 Iraqi Dinar which equals $1
    in accordance to receipt (37a) (letter ​​No.8/4/21/93270 on 5/8/2009).') ?>'</p>

