<?php $this->headTitle($this->translate('Birth Certificate')) ?>
<h1><?php echo $this->translate('Birth Certificate') ?></h1>
<p><span style="font-weight: bold;"><br><br>
        <?php echo $this->translate('First - Birth Certificates:') ?></span><br>
    <?php echo $this->translate('After
    making sure of the new born father\'s Iraqi citizenship , the Consular
    Section at the Embassy, according to Article V of the Law on registration of
    births and deaths No. (148) of 1971, registers the birth and issues a birth
    certificate based on the Arab and foreign birth certificate approved from
    the competent authorities in that country, including the ratification by the
    Ministry of Foreign Affairs in four copies:<br><br>1-The white copy: for the
    Department of Civil Status.<br> 2-The red copy: for the applicant.<br> 3-The
    green or yellow copy: for the computer.<br> 4-The blue copy: a copy to be
    saved at the Consular Division.<br><br>The copy of Civil Status and copy of
    Computer to be sent to the Ministry of Health / Department of health and
    life Statistics attached with a copy of the birth of Arab or foreign
    certificate ratified by the Ministry of Foreign Affairs in the country of
    the Mission\'s work and a copy of the Civil Status Card of the father or
    brother or unmarried sister or the mother whose husband\'s name installed in
    identity in the first political mail. The birth certificate is organized
    once at the time of birth and in the case of the need for extra copies the
    related people can go to Bureau of health and life Statistics in the
    Ministry of Health for the purpose of issuing a copy of registering the
    birth which contains all the information recorded in the birth certificate
    and the number they need. The registration copy serves as a birth
    certificate includes all of the information recorded in the birth
    certificate. There are things recorded concerning the work of the consul and
    should not be overlooked during the organization of a birth certificate (the
    date of the organization of the certificate - gender of the baby - the stamp
    and signature of the Consul - the cell of the Civil Affairs Department).(The
    letter of the consular department, No. (8/ 4 / 22/65506 15 / 2 /2010). And
    the letter of Ministry of Health / Department of Planning and Resource
    Development / Department of health and life Statistics No. 55 243 on 13 / 12
    /2007).<br><br><br>- <span style="text-decoration: underline;">The practical procedures required for the issuance of birth and death certificates:</span><br>1-It
    is necessary for the father of the child to be present in the Consular
    Section of the Embassy, if not , the marriage contract should be among the
    required documents to prove paternity of the child (perhaps that the child\'s
    father does not accept registering his child in his name).<br>2- The
    consular section should fill in all the required cells of the forms of birth
    and death certificates.<br>3- Information for the Civil Status is taken from
    the identity of the father\'s Civil Status (page - records - department of
    civil status- the province) and if this is not possible, the dictated
    information would base on information provided by his father.<br>4-
    Registering the date of mother\'s birth in the hour of birth event and not
    the date of organizing the certificate.<br>5- The adoption of a birth or
    death certificate issued by the missions will not be taken in case there is
    a difference in the names between birth certificate or death certificate
    (Arabic or foreign) and what is recorded in the Civil Status Card provided
    by the citizen. (The Letter of Consular Department, No. 6 / 4 /22/ 8920 on
    27 / 2 / 2011).<br>Note (a) : - At the birth of an Iraqi child abroad his
    family submits to the mission a statement of birth issued by the authority
    in the country in which the birth occurred certified by the competent
    authorities during the two months from the date of birth, if it is late they
    must pay a fine of ten thousand Iraqi dinars equivalent ($ 8.50 ) as a fee
    of delay of registration (Our letter No. 64 161 on 4 / 2 /2009) and under
    receipt ( 37 a) on the basis of Article V of registering the births and
    deaths number ( 148 ) of 1971 as amended. (Letter of Consular Department,
    No. 8 / 4 / 21/64161 4 / 2 /2009).<br>(B): - It is not permissible to adopt
    citizenship certificate or passport for the issuance of a birth or death
    certificate as they do not have the registration of the number of the page
    and the record so only Civil Status (ID).is adopted.<br><br><span
        style="font-weight: bold;">Document of Birth:</span><br><br>It is an
    official document issued by the personal status courts according to the
    provisions of the law of registration of births and deaths No. (148) for the
    year 1971 amended and it serves as a birth certificate for children or
    people who did not get a certificate from an authorized official during
    birth because they were not born at an empowered hand to organize birth
    certificate (for example, inside the hospital or authorized midwife) or
    other reasons. The document of birth is not authorized for the consul for it
    exclusively authorized to the judiciary and the consul cannot release it
    only after authorization from the judge of personal status and it has many
    complexities there is no room for touching it.') ?><br><br><br><br><br><br><br>
</p>