<?php $this->headTitle($this->translate('Certificate Of Origin')) ?>
<h1><?php echo $this->translate('Certificate Of Origin') ?></h1>
<p><br><?php echo $this->translate('<span
        style="font-weight: bold;">  - Fees for certificates of origin, lists, and inspection</span>
    <span style="font-weight: bold;">certificates: - <br><br></span><br> Fees
    are taken for the ratification of certificates of origin, commercial lists,
    and inspection certificates according to the amended law of ratification of
    signatures on Iraqi and foreign records and documents No. 52 of 1970 and as
    shown below: - <br><br>1- The aforementioned documents are ratified by the
    commercial attaché or Iraqi missions, in case there were no commercial
    attaché. The amount of $160 or its equivalent is taken for each
    ratification; original document or a copy and for certificates of origin,
    commercial lists, and inspection certificates. The ratification should be
    done on the last copy taking into account sealing all copies to avoid
    forgery, providing that all copies are sealed from the top to avoid taking
    out any sheet of the documents (Consular Department Letter No. 8/9/1/4666 in
    23/5/2007).<br><br>2 - The aforementioned documents issued by one of the
    member states of the Arab Common Market and ratified by the official
    reference in the country of origin of the goods produced in Arab countries
    are ratified (without taking ratification fees) in accordance to the
    resolution of the Economic and Social Council of the Arab League No. 1506 in
    19/2/2004 and the approval of the Cabinet / Economic Affairs Committee in
    its letter No. 1320 in 26/2/2007 which stipulates the cancelling of fees on
    certificates of origin and commercial lists associated with them preserving
    Iraq\'s right of reciprocity.<br><br>3 – Concerning the goods manufactured in
    non-Arab countries and exported to the Iraqi market (i.e. re-exporting from
    the local market of these countries to the Iraqi market) the procedures set
    below are followed: <br><br>A – The ratification of the consulate of the
    manufacturing countries in the light of the original certificate of origin
    sent to the Arab country. <br><br>B – The ratification of the Ministry of
    Foreign Affairs of the Arab country that exports the goods to Iraq to ratify
    the Consulate seal of the manufacturing country.<br><br>C – Ratification
    fees ($160) are taken and all the documents are sealed. <br>(Consular
    Department letter No. 8/9/1/83159 in 11/8/2010 and 8/9/1/70440 in 7/4/2010)
    <br>D - Taking into account that the goods are produced by the same producer
    countries and writing that upon ratification to avoid any change in case of
    ratification in a country other than the country of origin.') ?><br></p><br>
