<?php $this->headTitle($this->translate('Death Certificate')) ?>
<h1><?php echo $this->translate('Death Certificate') ?></h1>
<p><span style="font-weight: bold;"><?php echo $this->translate('Death   Certificates :') ?> </span> <br>
    <?php echo $this->translate('After the
    person in charge of the Consular work confirms the death of Iraqi C, the
    Consular Section registers the death in an Iraqi death certificate issues it
    on the basis of Article 10 of the law of births and deaths\' registration,
    which issued based on Arab or Foreign death certificate, certified by the
    Ministry of Foreign Affairs in the work area of the Mission. <br>The Consul
    writes down the information in all the certificate fields and information of
    the Civil Status Card of the deceased , his son or his wife , the death
    certificate shall not be issued to a person other than an Iraqi, the death
    certificate issued in four copies are: -<br>The first copy (white copy) a
    copy of the Civil Status and the second copy (red copy) a copy of relatives
    and the third copy (green or yellow) Electronic system copy and fourth copy
    (blue copy) save by the Consular Section of the Embassy for the purpose of
    reference when needed. <br>Copies of Civil Status and Electronic system are
    sent to the Ministry of Health / Department of Health and Life Statistics
    attached with replica image of the death certificate certified by the
    Ministry of Foreign Affairs in the work area of the Mission with a picture
    of the Civil Status Card of the deceased in the first mail.<br>The consul
    should always remember some of the fields contained in the certificate for
    the Consular Section, including: -<br>(Date of issuance of the death
    certificate - stamped with the seal of Consular Department - mentioning the
    name and signature of the consul) Note that each death certificate must
    include the following: -<br>(The name of the deceased - date of birth -
    nationality - date of death - the cause of his death - a place of death)<br><br>The
    death certificate is essential to the family of the deceased for the purpose
    of registration in the civil records and restrictions and issues of
    inheritance and legacies, therefore the family copy of the certificate must
    be delivered to the relatives for the purpose of registration in the civil
    status records. If the Mission suspects that the death occurred as a result
    of a criminal act, it must ask the concerned party in its work area for a
    body autopsy to confirm the cause of death and to inform the Consular
    Department of the results.<br>Note: - The duration to inform about the death
    outside Iraq is (45) days from the date of death and the implementation of
    paragraph (a) of Article (10) of the amended law of births and deaths No.
    (148) for the year 1971. In the case of delays in death informing, a sum of
    ten thousand dinars must be paid as a fine or a sum equivalent to ($8.50) as
    late registration fee according the accountant receipt (37a) (the consular
    department instructions 8 / 4 / 21/64161 in 4 / Feb. /2009).') ?><br><br></p><br>