<?php $this->headTitle($this->translate('Extension Of Passports')) ?>
<h1><?php echo $this->translate('Extension Of Passports') ?></h1>
<p><span style="font-weight: bold;"><?php echo $this->translate('Extension Of Passports') ?></span><br><br><span
        style="font-weight: bold;"><?php echo $this->translate('First:') ?></span>
    <?php echo $this->translate('Instructions of Extension:<br>1
    - Passports edition (S) got the approval of Directorate of Passports / legal
    Department for a period of eight years starting from the date of issuance
    and if has already been extended previously.<br>2 - Passports Edition (N)
    are no more valid since 1/1/2008 .<br>3 - Passports Edition (M) are no more
    valid since 1/1/2007<br>4 - Passport Edition (H) got the approval of
    Directorate of Passports to be extend for a period of one year beginning
    from 1/1/2011 up to 1 / 1/2012<br>5 - Passport Edition (G) is valid for a
    period of eight years and cannot be extended.<br>6 - Passport Edition (A) is
    valid for eight years and cannot be extended.<br><br><span
        style="font-weight: bold;">Second:</span> Requirements for Extending
    passport edition (S):<br>1 . Bearer of the passport what approves his Iraqi
    citizenship .<br>2 . Filling a permission form for an extension of the
    passport.<br>3 . Collecting a fee of 25 U.S. dollars for the extension.<br>4
    .Minors parent to be existed in the mission building.')<br><br><br><br></p>