<?php echo $this->headTitle($this->translate('Faq')) ?>
<h1><?php echo $this->translate('Faq') ?></h1>
<table class="table table-consended" cellspacing="0" border="0">
    <tbody>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="53"><?php echo $this->translate('Q. Can an Iraqi Birth Certificate be issued to a child of a non-Iraqi
                            father?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. The Iraqi Birth certificate only can be issued to a child of an Iraqi father;
                        it may not be issued in the event the child’s father is an Arab or a foreigner.') ?><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="54"><?php echo $this->translate('Q. How the foreign marriage certificates / the judgments of divorce
                            can be registered in the Civil Status registers of Iraq?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('The foreign bodies in the Iraq mission’s territory shall issue marriage
                        certificates / judgments of divorce according to their relevant laws. To register such
                        certificates / judgments in the Civil Status register of Iraq, according to the Law of Civil
                        Status No. 65 for 1972, the following procedures shall be followed:<br>1-A counterpart of the
                        marriage certificate, authenticated by the Embassy or the General Consulate, shall be sent
                        together with authenticated copies of the Husband’s and the Wife’s Civil Status ID card to the
                        Civil Status department which issued the Husband’s Civil Status ID card in order to record the
                        marriage occurrence and open new separate family page. The divorce occurrence will be registered
                        in the family’s page in the Civil Status register.<br>2-If the marriage certificate / the
                        judgment of divorce is in a foreign language, it shall be translated to Arabic by a certified
                        translator and authenticated by the notary public and the Embassy.<br>3-The marriage c') ?>
                    </td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="55"><?php echo $this->translate('Q. What are the procedures to provide a citizen with a confirmation
                            over being unmarried?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. The citizen shall submit a Transcript of Record from the Civil Status
                        department, authenticated by the Ministry of Internal and the Ministry of Foreign Affairs –
                        Authentications, during the period of issuing the confirmation.') ?><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="56"><?php echo $this->translate('Q. What is required from the citizen for obtaining a Civil Status ID
                            card lost / damaged substitute?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. –<br>1-A request to obtain a Civil Status ID card lost / damaged substitute
                        shall be submitted.<br>2-The application form (available in the Embassy) shall be attached to
                        the request.<br>3-The form shall be filled by the master of family, mistress of family, record
                        holder, guardian or attorney at law, with their explicit signatures and full names.<br>4-The
                        Consul shall note down the applicant’s statement on the reverse of the abovementioned form,
                        state the full name of applicant and have his/her thumbprint placed thereon. The statement shall
                        be signed by the Consul (whose name shall be stated in full) and sealed by the consular seal. If
                        the request is for a damaged substitute, the original old ID card shall be attached to the form.
                        If the request is for a lost substitute, the statement shall be noted down on the reverse of the
                        form and a copy of the lost or his/her father’s or brother’s ID card, authenticated by the
                        Embassy as True Copy, shall be attached thereto.<br>5-Tw') ?>
                    </td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="57"><?php echo $this->translate('Q. What are the procedures required prior to a citizen’s request for
                            obtaining Civil Status ID cards for his/her children?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. –<br>1-He/she should have registered his/her marriage occurrence with the
                        Civil Status department.<br>2-He/she should have indicated the birth occurrence of the newborn
                        with the Civil Status department.<br>3-After realizing the above, a request may be submitted by
                        the citizen to the Embassy for obtaining a Civil Status ID card for his/her child, within the
                        disciplines notified to the Embassy.') ?><br><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="58"><?php echo $this->translate('Q. What are the procedures required by a citizen to obtain an Iraqi
                            Nationality Certificate lost / damaged substitute?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('1-A request to obtain an Iraqi Nationality Certificate lost / damaged substitute
                        shall be submitted.<br>2-The application form (available in the Embassy) shall be filled and
                        attached to the request.<br>3-The Consul shall note down the applicant’s statement on the
                        reverse of the abovementioned form, state the full name of applicant and have his/her thumbprint
                        placed thereon. The statement shall be signed by the Consul and sealed by the consular seal. If
                        the request is for a damaged substitute, the original old Nationality Certificate shall be
                        attached to the form. If the request is for a lost substitute, a copy of the father’s or
                        brother’s Nationality Certificate, authenticated by the Embassy as True Copy, shall be attached.<br>4-4
                        recent photos shall be attached to the request.<br>5-A copy of the applicant’s, father’s and
                        mother’s passport shall be attached, sealed by the consular seal and authenticated by the Consul
                        as True Copy.<br>6-An amount of 2 USD, representing the cer') ?>
                    </td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="59"><?php echo $this->translate('Q. What are the required procedures to authenticate a Police Clearance
                            Certificate?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. –<br>1-When a request is submitted to obtain a Police Clearance Certificate
                        from an Embassy or a General Consulate, and the applicant came to Iraq after he/she obtained
                        such certificate, then he/she may have the same authenticated by the Ministry of Internal and
                        the Ministry of Foreign Affairs and then by the Embassy.<br>2-If the applicant is abroad, the
                        Ministry of Internal does not authenticate such certificate when issued. In this case, the
                        Embassy or the General Consulate may authenticate the thumbprint of the certificate
                        holder.') ?><br><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="60"><?php echo $this->translate('Q. What are the required procedures if a citizen was unable to attend
                            at the Embassy or the Consulate to submit a request for obtaining a Certificate of Life due
                            to illness or disability and his/her r') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. In such case, the following procedures shall be followed:<br>1-A confirmation
                        from the official authorities in the country of residence, showing that he/she is still alive,
                        shall be submitted in the month he wants to obtain the official certificate of life from the
                        Embassy or the General Consulate. The official form of the Certificate of Life, sent to him/her
                        by the Embassy or the General Consulate and published at Ministry of Foreign Affairs’ or the
                        Embassy’s website, shall be filled completely, his/her photo attached thereto and signed by
                        him/her and then attached to the confirmation. It shall be mailed to the Embassy where the
                        Consul shall sign and seal it and state his full name thereon. A counterpart of the Certificate
                        of Life and the competent authorities’ confirmation shall be retained with the certificates of
                        life dossier.') ?><br><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="61"><?php echo $this->translate('Q. What are the procedures required from a citizen if he was unable to
                            send its original valid passport, due to damage or lost, for the purpose of obtaining a
                            decision from the Nationality Directorate') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. In such case, the following procedures shall be followed:<br>1-A confirmation
                        issued by the residence authorities and authenticated by the Ministry of Foreign Affairs of the
                        country of residence, stating that he/she does not hold a passport, shall be submitted.<br>2-The
                        personal photo shall be sealed by the Embassy’s seal.<br>3-A written undertaking (according to
                        the form available in the Embassy), pursuant to which he/she shall undertakes that he/she does
                        not hold a passport, shall be submitted.<br>4-The Directorate of Nationality shall approach the
                        Directorate of Passports to incorporate his/her full name, date and place of birth, mother’s
                        name, Civil Status ID card Register and Pg. Numbers and Iraqi Nationality Certificate number and
                        date, so as not to obtain an Iraqi passport, in addition to other Iraqi documents.') ?><br><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="62"><?php echo $this->translate('Q. What is required from the citizen in the former Rafha Camp in Saudi
                            Arabia, who holds what is called a (Statement of Birth), of Saudi Arabia, which is not a
                            Birth Certificate; as the Saudi birth ce') ?>/a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. In this case, the Embassy shall approach the Saudi Embassy through an official
                        letter to authenticate the said document. In the event the Embassy of Saudi refused to
                        authenticate, the ministry of foreign affairs shall be approached about the matter so that it
                        shall be referred to the competent bodies and take the appropriate decision in this respect.<br>-For
                        the religious marriage contracts, they may be authenticated by Ministry of Foreign Affairs in
                        the country accrediting the Embassy. Thereafter, the Embassy shall authenticate the Seal of the
                        Ministry of Foreign Affairs in the mission’s territory.') ?><br><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="63"><?php echo $this->translate('Q. Who are covered by the exemption from the condition of obtaining a
                            visa to enter Iraq?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. H.E. Minister of Internal has approved on exempting Arabs and foreigners, of
                        Iraqi origins, who hold foreign passports, from the condition of obtaining a visa to enter Iraq.
                        However, this does not mean to discontinue granting those visas, if they applied for, rather
                        they and their family members shall be granted visas without fees.') ?><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="64"><?php echo $this->translate('Q. Are the Iraq born Foreigners, and their family members, covered by
                            the exemption from the condition of obtaining visas to enter Iraq?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. H.E. Minister of Internal has approved on granting the Iraq born foreigner,
                        and his/her family members, visas by our missions abroad, without approaching the ministry of
                        foreign affairs, against a fee from only the family members, provided that the Iraq born
                        foreigner should be among the visiting family.') ?><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="65"><?php echo $this->translate('Q. What is the competence of our missions abroad to grant visa without
                            approaching the ministry of foreign affairs?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. –<br>1-Arab and foreigner wives of Iraqis, and their children, shall be
                        directly granted visas to enter Iraq, without fees.<br>2-Holders of diplomatic, service and
                        private passports, after submitting the letter of the Ministry of Foreign Affairs in the country
                        accrediting the mission, considering the Ethic of Reciprocity and notifying the Ceremonies
                        Department after granting visa.<br>3-Students who study in Iraq after submitting what confirms
                        that they are admitted and continuing studying in Iraq. This covers the students of schools,
                        institutes and universities of only the Ministry of Education and the Ministry of Higher
                        Education and Scientific Research.<br>4-The journalists, as the missions shall first call the
                        press agency so that it will perform its roll and notify the Consular Department to authorize it
                        to grant visas.') ?><br><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="66"><?php echo $this->translate('Q. What is the mechanism of obtaining approvals on granting visas to
                            the Arab and foreigner investors?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. The Arab and foreigner investors are required to contact the National
                        Investment Commission of the Cabinet Presidency, which e-mail and website are stated, about our
                        circular above. All our missions abroad are required to affix these information on the bulletin
                        board on the frontage of the mission premises for information. The Investment Commission shall
                        obtain the approvals during 72 hours and contact us in this respect to authorize our missions to
                        grant visas.') ?><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="67"><?php echo $this->translate('Q. What are the instructions for granting group visas for the
                            religious tourism groups?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. The group visa is granted to a group of 10 members or more. Their names shall
                        be arranged in lists (manifests) by the Iraqi tour and travel companies and the companies in the
                        countries requiring to group visitors. The Iraqi receiving company shall contact the tourism
                        board to obtain the approval over granting visas and then approach the Consular Department to
                        authorize our missions abroad to grant visas. This is in normal cases, yet sometimes there are
                        exemptions to be issued in the religious events, where the approval of the Ministry of Internal,
                        over authorizing our missions abroad and the border points to grant visas, is obtained. The
                        validity period of approval shall be for a limited time.') ?><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    <tr>
        <td>


            <table border="0" cellspacing="0" cellpadding="5">

                <tbody>
                <tr>
                    <td class="txt2"><a name="68"><?php echo $this->translate('Q. Can the applications, for granting foreigner workers visas to enter
                            Iraq, be processed?') ?></a></td>
                </tr>
                <tr>
                    <td class="txt4"><?php echo $this->translate('Ans. This applications for granting foreigner workers visas to enter Iraq are to be
                        stopped, except for housekeepers.') ?><br></td>
                </tr>
                <tr>

                </tr>

                </tbody>
            </table>


        </td>
    </tr>
    </tbody>
</table>
<style>
    td.txt4 {display: none;}
    td.txt2 > a {cursor: pointer; color: #444; transition: color 0.3s ease-out;}
    td.txt2 > a:hover {color: #3B93C9;}
    td.txt2 > a.active {color: #3B93C9;}
</style>
<script>
    $(document).ready(function(){
        $('.txt2 > a').click(function(e){
            e.preventDefault();

            $(this).toggleClass('active');
            $(this).parents().eq(3).find('.txt4').toggle('slow');
        });
    });
</script>