<!DOCTYPE html>
<html>
<head>
    <link href="http://dev.hoaxinh.net/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="http://dev.hoaxinh.net/css/site.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.css" media="screen"
          rel="stylesheet" type="text/css">
    <link href="http://dev.hoaxinh.net/css/style.css" media="screen" rel="stylesheet" type="text/css">
    <!-- BEGIN Grabbed Website Stylesheets -->
    <link href="../css/englishstyle.css" rel="stylesheet" type="text/css"/>
    <link href="../css/topnews.css" rel="stylesheet" type="text/css"/>
    <link type="text/css" rel="stylesheet" href="../css/style.css"/>
    <!-- END Grabbed Website Stylesheets -->
</head>
<body>
<div class="container">
    <div id="main-content">
        <!-- BEGIN Container -->
        <div id="content-container">
            <!-- BEGIN Section Navigation -->
            <div id="section-navigation">
                <div class="content_leftheader"><span class="title">Services for Iraqi Citizen</span></div>
                <div class="qucikmenu">
                    <ul>
                        <li><a href="birth-certificate.html"> Birth certificate</a></li>
                        <li><a href="marriage-divorces-registration.html"> Marriage/ divorces registration</a></li>
                        <li><a href="the-civil-status-id.html"> The Civil Status ID</a></li>
                        <li><a href="nationality-cert.html"> Nationality Cert.</a></li>
                        <li><a href="non-conviction-certificate.html"> Non-conviction certificate</a></li>
                        <li><a href="life-certificate.html"> life certificate</a></li>
                        <li><a href="pass-doc.html"> Pass doc.</a></li>
                        <li><a href="authorization.html"> Authorization</a></li>
                        <li><a href="forms.html"> Forms</a></li>
                        <li><a href="ratifications.html"> Ratifications</a></li>
                        <li><a href="faq.html"> FAQ</a></li>
                        <li><a href="fees.html"> Fees</a></li>
                        <li><a href="death-certificate.html"> Death Certifcates</a></li>
                        <li><a href="passport-system.html"> Passport System</a></li>
                        <li><a href="indigent-deportation.html"> Indigent deportation</a></li>
                        <li><a href="patrimonies.html"> Patrimonies</a></li>
                        <li><a href="approving-corpse-entry-to-iraq.html"> Approving Corpse Entry to Iraq</a></li>
                        <li><a href="passports-issuance.html"> Passports Issuance</a></li>
                        <li><a href="extension-of-passports.html"> Extension of passports</a></li>
                        <li><a href="loss-of-passports.html"> Loss of passports</a></li>
                        <li><a href="lawsuits.html"> Lawsuits</a></li>
                        <li><a href="general-affairs.html"> General Affairs</a></li>
                    </ul>
                </div>
                <div class="content_leftheader"><span class="title">Services for Foreign Nationality</span></div>
                <div class="qucikmenu">
                    <ul>
                        <li><a href="visa.html"> Visa</a></li>
                        <li><a href="ratifications-1.html"> Ratifications</a></li>
                        <li><a href="certificate-of-origin.html"> Certificate of origin</a></li>
                        <li><a href="forms-1.html"> Forms</a></li>
                        <li><a href="faq-1.html"> FAQ</a></li>
                        <li><a href="fees-1.html"> Fees</a></li>
                        <li><a href="palestinian-travel-documents.html"> Palestinian Travel Documents</a></li>
                    </ul>
                </div>
            </div>
            <!-- END Section Navigation -->
            <!-- BEGIN Page Content -->
            <div id="content">


                <span id="ctl00_Main_errormessage" class="htext"></span>

                <table id="ctl00_Main_Grid2" cellspacing="0" cellpadding="0" border="0"
                       style="width:438px;border-collapse:collapse;">
                    <tbody>
                    <tr>
                        <td valign="top">

                            <table width="438px" border="0" cellspacing="0" cellpadding="0">

                                <tbody>
                                <tr>
                                    <td colspan="2" valign="top"><br> <strong class="htext">Fees</strong><br><br></td>
                                </tr>

                                <tr>
                                    <td>
                                        <table width="140" border="0" cellspacing="0" cellpadding="0"
                                               bordercolor="#E5E5E5" height="21" dir="ltr">
                                            <tbody>
                                            <tr>
                                                <td width="68">

                                                </td>

                                            </tr>
                                            </tbody>
                                        </table>
                                        <hr>
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="2" valign="top">

                                        <p><span style="font-weight: bold;">Consular fees and commercial<br><br><br><br></span>
                                        </p>
                                        <table cellpadding="0" cellspacing="0"
                                               style="width: 320px; border-left-width: 1px; border-left-color: #000000; border-left-style: solid; border-top-width: 1px; border-top-color: #000000; border-top-style: solid;">
                                            <tbody>
                                            <tr>
                                                <td rowspan="1" colspan="1"
                                                    style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    <br>&nbsp; &nbsp; &nbsp;<br><br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    <p style="margin: 0px; text-align: center;"><span
                                                            style="font-weight: bold;">Ratification</span></p></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    <p style="margin: 0px; text-align: center;"><span
                                                            style="font-weight: bold;">Fee in dollar</span></p></td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    1
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Limited authorization<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    10
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    2
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Limited authorization <br>(copy)<br><br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    5
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    3
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    General authorization<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    30
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    4
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    General authorization<br>(copy)<br><br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    5
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    5
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Cancelling the authorization<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    1
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    6
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Stamp ratification<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    5
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    7
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Stamp ratification (copy)<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    2
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    8
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Ratification of certificate of origin <br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    160
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    9
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Ratification of certificate of origin (copy) <br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    160
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    10
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Ratification of commercial list <br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    160
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    11
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Ratification of commercial list (copy)<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    160
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    12
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Medical test (contagious diseases)<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    5
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    13
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Certificate of examination Lists for goods exported to Iraq (meat -
                                                    medicines) and so on<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    160
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    14
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Certificate of no criminal record<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    8.5
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    15
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    birth certificate<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    15
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    16
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    fine on delaying issuance of a certificate of birth or death<br>
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    8.5
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    17
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    passport<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    20
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    18
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Passport extension<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    25
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    19
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Laissez passer<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    25
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    20
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    National ID (Jinsiya)<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    1
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    21
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Nationality certificate (shahadat al jinsiya)<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    2
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    22
                                                </td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    Entry of Arab or foreign corpse<br></td>
                                                <td style="border-right-width: 1px; border-right-color: #000000; border-right-style: solid; border-bottom-width: 1px; border-bottom-color: #000000; border-bottom-style: solid;">
                                                    3200
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <br><span style="text-decoration: underline;"><span style="font-weight: bold;">Services provided by the Consulate for free: -<br><br></span></span><br>1-Adding
                                        a child to the passport.<br>2-Confirmation letter.<br>3-Adding the family
                                        name.<br><br><br><br>

                                        <p></p><br>
                                    </td>
                                </tr>


                                </tbody>
                            </table>

                        </td>
                    </tr>
                    </tbody>
                </table>
                <br><br>
                <table id="ctl00_Main_grid3" cellspacing="0" cellpadding="0" border="0"
                       style="width:200px;border-collapse:collapse;">
                    <tbody>
                    <tr>
                        <td valign="top">
                        </td>
                    </tr>
                    </tbody>
                </table>
                <hr>


            </div>
            <!-- END Page Content -->
        </div>
        <!-- END Container -->
    </div>
</div>

</body>
</html>