<?php $this->headTitle($this->translate('Fees')) ?>
<h1><?php echo $this->translate('Fees') ?></h1>
<table align="center" cellspacing="0" cellpadding="1"
       style="border-left-color: #000000; border-left-width: 1px; border-left-style: solid; width: 332px; border-top-color: #000000; border-top-width: 1px; border-top-style: solid;">
    <tbody>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    style="font-weight: bold;">no</span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    style="font-weight: bold;"><?php echo $this->translate('Transaction type') ?></span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    style="font-weight: bold;">&nbsp;<?php echo $this->translate('Stamp duty Dinar') ?></span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    style="font-weight: bold;">&nbsp;<?php echo $this->translate('Stamp duty dollar') ?></span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    style="font-weight: bold;">&nbsp;<?php echo $this->translate('revenue tax Dinar') ?></span><span
                    style="font-weight: bold;">&nbsp;</span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    style="font-weight: bold;">&nbsp;<?php echo $this->translate('revenue tax Dollar') ?></span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    style="font-weight: bold;"><?php echo $this->translate('Total Dinar') ?></span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    style="font-weight: bold;"><?php echo $this->translate('Total Dollar') ?></span></p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;1</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>Limited
                authorization<br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>12000 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    >8</span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    >3000</span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>2 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>15000 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>10 </span></p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;2</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Limited authorization
                <br>(copy)') ?><br><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    >4500 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>3 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>3000 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>2 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>7500 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>5 </span></p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;3</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('General
                authorization') ?><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>32490 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    >21,66</span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>12510 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>8,34</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            &nbsp;<span ></span><span ></span><span
                ><span
                    ></span><span ></span>45000 </span>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>30 </span></p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>4</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('General
                authorization(copy)') ?><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>6000 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>4 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    >1500 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    >1 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    >7500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    >5 </span>
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>5</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Cancelling the
                authorization') ?><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    >7500 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    >5 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    >7500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    >5 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;6</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Stamp
                ratification') ?>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>3000 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>2 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;-</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;-</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>3000 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>2 </span></p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;7</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Stamp ratification
                (copy)') ?>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>240000 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>160 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>240000 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    >160&nbsp;</span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;8</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Ratification of
                certificate of origin') ?> <br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>75000 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>50 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>75000 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>50 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;9</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ><?php echo $this->translate('Ratification of certificate of origin copy)') ?></span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>15000 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>10 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>15000 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>10 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;10</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Ratification of
                commercial list') ?> <br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>7500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>5 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>7500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>5 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;11</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Ratification of
                commercial list (copy)') ?><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>37500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>25 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>37500 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>25 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;12</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Medical test (contagious
                diseases)') ?><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>22500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>15 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>22500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>15 </span></p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;13</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Certificate of
                examination Lists for goods exported to Iraq (meat - medicines)
                and so on') ?> <br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>30000 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>20 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;-</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;-</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>30000 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>20 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;14</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('Certificate of no
                criminal record') ?>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>37500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>25 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>37500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>25 </span></p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;15</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('birth certificate') ?><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>52500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>35&nbsp;</span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>52500 </span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>35 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;16</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><?php echo $this->translate('fine on delaying
                issuance of a certificate of birth or death') ?><br>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>37500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>25 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>-&nbsp;</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>37500 </span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>25 </span>&nbsp;
            </p>
        </td>
    </tr>
    <tr>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;17</p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>passport<br></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>4800000</span>
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p>&nbsp;<span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>3200 </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>- </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>- </span></p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span>
            </p>
            <p><span
                    >4800000&nbsp;</span>&nbsp;
            </p>
        </td>
        <td style="border-bottom-color: #000000; border-bottom-width: 1px; border-bottom-style: solid; border-right-color: #000000; border-right-width: 1px; border-right-style: solid;">
            <p><span
                    ></span><span ></span><span
                    ><span
                        ></span><span ></span>3200</span></p>
            <p><span
                    > </span>&nbsp;
            </p>
        </td>
    </tr>
    </tbody>
</table>
<p><br></p>
<p><span
        ><?php echo $this->translate('Services provided by the Consulate for free') ?></span><span
        >:&nbsp;</span>
</p>
<p><span
        >1</span><span
        >-</span><span
        ><?php echo $this->translate('Add a child to Passport') ?></span><span
        style="color: black; font-size: 14pt;">.</span>
</p>
<p><span
    ">2</span><span
        >-</span><span
        ><?php echo $this->translate('Letter of conformation.') ?></span></p>
<p><span
        >3</span><span
        >-</span><span
        ><?php echo $this->translate('Add family name') ?></span><span
        >.</span>
</p>
<p></p>
<br>
</td>
</tr>
</tbody>
</table>