<?php $this->headTitle($this->translate('General Affairs')) ?>
<h1><?php echo $this->translate('General Affairs') ?></h1>
<p> <?php echo $this->translate('General Affairs<br>Certain Provisions of the Relevant Laws<br><br>First -
    Provisions of the births and deaths law:<br><br>Law of births and deaths
    registration number 148 for the year (1971) , and its amended<br>Article V :<br>1
    . The sponsored of a born outside Iraq need to tell the Iraqi mission or any
    other health competent authority in Iraq about the childbirth within a
    period of sixty days.<br><br>2 . The Iraqi mission or its substitute to
    issued a certificate with four copies according to the foreign birth
    certificate and send the first copy ( of the Civil Status ) and the third
    copy ( of the computer ) to the Ministry of Health / Directorate of
    Statistics and then delivered to the stakeholders and the Iraqi mission
    saves the fourth copy .<br>Article X :<br>1 . When a death happened outside
    Iraq ,the relatives of the dead asks the Iraqi mission or its substitute
    during forty five days to organize a certificate.<br>2 . The Iraqi mission
    or its substitute Issues four copies , according to the foreign death
    certificate recognized by the country in which the death occurred, they need
    to be certified and translated in Arabic , in accordance with the provisions
    of this law .<br> 3 . The Iraqi mission sent the first copy (copy of the
    Civil Status ) and the third copy ( copy of the computer) to the Ministry of
    Health / Department of Health Statistics ,the second copy to be delivered to
    the related people and the fourth copy to be saved by the Iraqi mission .
    Directorate of Health Statistics sends the certificate to the competent
    health authority for registration in the Department of Civil Status
    .<br><br>Article XXI : Paragraph (2)<br> It is not allowed to modify or
    change the information contained in the certificate of birth or death, in
    the official records concerning births or deaths or to add the missing notes
    ,without a judgment of a competent court .<br>Secondly - Texts of the Vienna
    Convention on Consular Relations :<br>Article 36<br>1.With a view to
    facilitating the exercise of consular functions relating to nationals of the
    sending<br>State:<br>(a) Consular officers shall be free to communicate with
    nationals of the sending State and to have access to them. Nationals of the
    sending State shall have the same freedom with respect to communication with
    and access to consular officers of the sending State;<br>(b) If he so
    requests, the competent authorities of the receiving State shall, without
    delay, inform the consular post of the sending State if, within its consular
    district, a national of that State is arrested or committed to prison or to
    custody pending trial or is detained in any other manner. Any communication
    addressed to the consular post by the person arrested, in prison, custody or
    detention shall be forwarded by the said authorities without delay. The said
    authorities shall inform the person concerned without delay of his rights
    under this subparagraph;<br>(c) Consular officers shall have the right to
    visit a national of the sending State, who is in prison, custody or
    detention, to converse and correspond with him and to arrange for his legal
    representation.<br>They shall also have the right to visit any national of
    the sending State who is in prison, custody or detention in their district
    in pursuance of a judgment. Nevertheless, consular officers shall refrain
    from taking action on behalf of a national who is in prison, custody or
    detention if he expressly opposes such action.<br>2.The rights referred to
    in paragraph 1 of this article shall be exercised in conformity with the
    laws and regulations of the receiving State, subject to the proviso,
    however, that the said laws and regulations must enable full effect to be
    given to the purposes for which the rights accorded under this article are
    intended. <br><br>Article 39<br>Consular fees and charges<br>1.The consular
    post may levy in the territory of the receiving State the fees and charges
    provided by the laws and regulations of the sending State for consular acts.<br>2.The
    sums collected in the form of the fees and charges referred to in paragraph
    1 of this article, and the receipts for such fees and charges, shall be
    exempt from all dues and taxes in the receiving State. <br><br>Vocabulary of
    Certain Professions<br>Official موظف<br> Student طالب <br> Worker عامل<br>
    Businessman رجل اعمال<br> Free jobs اعمال حرة<br> Former official موظف سابق
    <br> Retired متقاعد <br> Journalist صحافي <br> Doctor طبيب<br> Engineer
    مهندس<br>Dentist طبيب اسنان<br> Pharmacist صيدلي <br> Actor ممثل<br>Painter
    رسام<br> Accountant محاسب<br> Merchant تاجر<br> Government official موظف
    حكومي<br> Attaché ملحق <br> House Wife ربة بيت<br> Consul القنصل<br> Expert
    خبير<br> Lawyer محامي<br><br>Records Required by the Consular Section<br>1.Record
    for Extending Passports Validity.<br> 2.Record for Granting Visas.<br>
    3.Record for General Authorization .<br> 4.Record Special Authorization.<br>
    5.Record for Ratifications.<br> 6.Record for the Iraqi Community .<br>
    7.Record for Births .<br> 8.Record for Deaths.<br> 9.Record for Laissez
    Passer<br> 10.Record for Palestinian Documents .<br> 11.Record for the
    Barred from Entering Iraq .') ?><br><br><br></p><br>