<?php $this->headTitle($this->translate('Indigent Deportation')) ?>
<h1><?php echo $this->translate('Indigent Deportation') ?></h1>
<p> <?php echo $this->translate('Indigent deportation <br>Iraqis indigent deportation<br><br>Intended of
    Indigent deportation, are Iraqi citizens who have been befell them certain
    calamity; lost their passports or have run out of money and would like to
    return to Iraq. Although the Embassy is responsible for dealing with
    situations of citizens abroad in such cases, however, at the present time
    there is no specific financial allocation embassy can spend it to indigent
    deportation but that the embassy can do the following : -<br>1. After the
    embassy to be sure of indigent\'s origin by providing proves that Iraqis (the
    Civil Status Card - a certificate of nationality – a copy of his lost
    passport), Embassy send a telegram to the Consular Department at the
    Ministry learned of the information and request approval to issue a passport
    for him.<br>2. Providing the Ministry of Foreign Affairs / Consular
    Department with adequate information for the address of his family in Iraq
    for the purpose of attending to the Ministry and the paying of the expenses
    of the ticket or any other expenses after the Embassy had set the
    amount.<br>3. The Ministry accounts receive the Amount ( set by the Embassy
    ) from the citizen\'s family and send telegram to the Embassy to book ticket
    and any other expenses and send it with the accounts of the Embassy to the
    Ministry for Expenses Settlement ( the amounts must be estimated on the
    basis of prices in Hard Currency ) .<br>4. When the Embassy receives a
    telegram, orders to book a ticket and deports indigent.<br>Note: - In the
    case that an indigent\'s passport missing, his Testimony must taken and sent
    in an official letter to the Directorate of Passports and if his passport
    with him, it pulls from him and provide him laissez passer for the purpose
    of deport him to Iraq.') ?>'<br><br></p>