<?php $this->headTitle($this->translate('Lawsuits')) ?>
<h1><?php echo $this->translate('Lawsuits') ?></h1>
<p> <?php echo $this->translate('Lawsuits') ?><br><br>
    <?php echo $this->translate('First: Judicial Notifications <br>on behalf of the Iraqi
    judicial offices, the mission informs the concerned people with the lawsuits
    took place inside Iraq and the date of the lawsuit hearing .<br>Second: The
    Oath Swearing <br>It is like the Judicial Notifications as the consul calls
    the person on oath and the Consul recite the text of the oath and ask him to
    repeat twice and then he reported that he (sworn in front of me ) and be
    signed by the consul and stamped with the seal of the consulate putting the
    date and to be sent back to the Consular Department with an official letter
    .<br><br>Third:<br>Sometimes the Ministry of Foreign Affairs in the country
    in which the mission exists, ask the mission to inform the Iraqi citizens or
    companies with judicial deadlines , so the Consul send these notifications
    to the Ministry of Foreign Affairs / Consular Department for the purpose of
    delivering them to the concerned parties .') ?><br><br></p>