<?php $this->headTitle($this->translate('Life Certificate')) ?>
<h1><?php echo $this->translate('Life Certificate') ?></h1>
<p>
    <?php echo $this->translate('1.The Iraqi retired citizen resident outside Iraq needs, at the beginning of
    every year, to send a letter to the National Pension Commission. Therefore,
    the Consul is required to issue the attached form (1) (Appendix ) (The
    Consular Department Letter No. 1 6/4/22 / 7024 issued on 8/3/2011 ) and fill
    all its paragraphs.&nbsp; The Consul must abide by some conditions like the
    presence of the retired person himself and identify him because this
    document is to prove the life of a retired person.<br> 2. The Consul signs
    and stamps the certificate with the Consulate\'s stamp and writ his/her name.
    <br> 3. The certificate of life then is given to the retired to send it to
    the relevant authorities.<br> 4. The certificate gets ratified in Iraq by
    the Department of ratifications in the Consular Department at the Ministry
    of Foreign Affairs.<br> <br> <span style="font-weight: bold;">Note : </span>-<br>
    In case the citizen cannot reach the Embassy to apply for the certificate
    (being sick or handicapped) then, he/ she should apply a letter from
    official bodies in the state of residence showing that he is still alive in
    the month that he wants to get the certificate of life from the embassy and
    attach with it the official certificate of life sent to him by the Embassy,
    which is posted on the ministry or the embassy websites, after filling,
    attaching&nbsp; photos and signing it and send it to the embassy by mail.
    Then, the Consul stamps and signs it. The mission keeps a copy of the
    certificate of life and the letter from the foreign authorities in the
    certificates of life dossier.<br><br>(Consular Department letter No. 1/4/22
    /87161 on 20/9/2010).') ?>'</p>