<?php $this->headTitle($this->translate('Loss of Passports')) ?>
<h1><?php echo $this->translate('Loss of Passports') ?></h1>
<p>
    <?php echo $this->translate('Citizens who lost their passports need to do the
    following : <br>1 . To declare that the passport has been lost, fearing that
    the passport is being held by the local authorities or the employer. After
    the issuance of the new passport , the local authorities to be informed that
    the old passport was canceled and need to be confiscated when found .<br>2 .
    Filling a form no. (1) of investigating the loss of the passport ,and
    stamped and signed by the consul .<br>3 . The Applicant should bring a
    letter from the police or the residence department includes passport number
    and date of entry.<br>4 . loss of passport should be publicized in a local
    newspaper.<br>5 . The loser should write down his testimony before the
    consul about how he lost the passport with all information concerning the
    lost passport and to be signed by the consul .<br>6 . The loser should
    verify his Iraqi citizenship.<br>7 . Four modern color images.<br>8 . All
    the aforementioned documents to be compared with the records of the Embassy
    if the lost passport was issued by the embassy.<br>9 . Community form should
    be filled with the required personal information.<br>10 . His testimony
    should be sent with the attachments to the Directorate of Passports to
    obtain approval for the issuance of a new passport.<br>11 . The Consular
    Department shall inform all Iraqi missions abroad with the loss of the
    passport for the purpose of informing the Ministry of Foreign Affairs in the
    countries they are accreted in, to prevent use by suspect parties.')?><br><br>
</p>