<?php $this->headTitle($this->translate('Marriage Divorces Registration')) ?>
<h1><?php echo $this->translate('Marriage Divorces Registration') ?></h1>
<p>
    <?php echo $this->translate('Foreign
    directories issue contracts and a decision of marriage and divorce,
    according to the laws and these documents implemented for Iraqi citizens in
    the records of Civil Status in accordance with the legal requirements set
    out in Article 38 of the Civil Status Law No. 65 of 1972 and all Iraqis live
    outside Iraq have to notify.<br><br> The Embassy or General Consulate about
    the event of marriage or divorce, or annulment, for the purpose of
    registration in the Department of civil Status the husband performs the
    following: -<br>1-Translate the marriage contract or divorce judgment if it
    is in the foreign language by the Association of Iraqi translators or the
    Faculty of Languages at the University of Baghdad exclusively.<br>2- Ratify
    the marriage contract or divorce judgment from the Consular Department /
    ratifications section.<br>3- The husband submits a copy of the marriage
    contract or judge\'s decision to divorce accompanied by a copy of the Arabic
    translation of the above mentioned with a certified copy of the Civil Status
    Card of the husband and the wife to the Civil Affairs Department, which
    issued the Civil Status Card of the husband for the purpose of marking the
    marriage and open a new page for a couple independent from the family and
    indicate the divorce in case it takes place.<br>Note: - It is not possible
    for the Embassy or the Mission to provide a confirmation letter for an
    unmarried citizen, whether man or woman, only after providing a copy of
    registration from the Civil Affairs Department during the period of issuance
    of confirmation.<br>It is possible for the citizen resides abroad to grant a
    private authorization for a person in Iraq authorizing him or her to audit
    the Department of Civil Status Affairs for the purpose of issuing a copy of
    registration.') ?><br><br></p>