<?php $this->headTitle($this->translate('Nationality Cert')) ?>
<h1><?php echo $this->translate('Nationality Cert') ?></h1>
<p>
    <?php echo $this->translate('the nationality cert
    Secondly: how to obtain a certificate of Iraqi nationality:<br>A - Instructions for the issuance of a certificate of
    Iraqi nationality: -
    <br> For the purpose of obtaining a certificate of Iraqi nationality for Iraqi citizens living abroad they must do
    the following:
    First:1 – The citizen must fill in an application for a certificate citizenship (Form No. 1)
    the original copy, not the copied and attach a photo to his or her application. The photo must be stamped
    by the consulate and proved by the left thumbprint of the applicant in the space provided for it and the Consul
    must back up the information in the declaration and sign by him and prove his full name and stamp by the
    consular stamp.<br>2 - A colored copy of the certificate of Iraqi nationality of the father or the mother must
    be attached.<br>3- A colored copies of identities of civil status of the applicant and his father or his mother.
    <br>4 - Additional recent photograph of the applicant must be attached.<br>A testimony of the applicant of the
    certificate must be recorded and taking his left thumb imprint on the form and recording his testimony and his
    father if he is an underage on the origin of the form.<br>Second, in the event of obtaining a certificate of Iraqi
    nationality instead of corrupted or lost follow the following:<br>1 - Organizing a statement form (1) and dictate
    and take his thumb imprint in the cells relevant to stamp the photo with the Consular stamp.<br>2 - Attaching the
    origin of Iraqi nationality certificate (damaged) or a photocopy of the (missing).<br>3 - A copy of a colored
    identity civil status must be attached with a photo of the applicant.<br> (The letter of Nationality Directorate,
    No. 1334, at 02.28.2012).<br> Third, the amount of (1250 ) dinars, which equivalents of two dollars in hard currency
    meets a fee for the issuance of the certificate according to Accounting receipt (37 a). (Circulating letter of
    Consular Department 04.08.21 / 84715 of 17/12/2008).<br>Fourth: Authorize a relative of the owners of the documents
    who are in Iraq to come to the Directorate of Citizenship to complete the legal procedures in Iraq , and come to the
    Directorate of status relevant for the purpose of registration in the records of civil status after the issuance of
    the decision as Iraqi by nationality, and give them the identities of the Civil Status, and then they can give them
    Iraqi certificate of nationality and send it to the Embassy or Consulate General , through the Ministry of Foreign
    Affairs for the purpose of delivery it to its owner.<br>Issuing and attestation of issuance of a certificate of
    Iraqi nationality:-<br>For the purpose of facilitating the issuance procedures and support the attestation of
    issuance of a certificate of Iraqi nationality and dealing with the issue of the damaged records in the Directories
    of Nationality, the General Directory of Nationality has been attributed what follows:<br>1 - Adoption of
    (page of works model No. 2) When the request for a certificate of Iraqi nationality ( new ) or Replacement of
    Damaged or attesting the issuance no need to get a passport as long as it\'s not available to the citizen and
    depend on ( pledge No. 3 ) .<br>2 - To support the purpose of the issuance of attesting Iraqi nationality
    certificates for citizens living outside Iraq whose their records are damaged they must submit the following
    with the support:<br>A – A Certificate of Iraqi nationality of the citizen (color copy).<br>B - The Civil Status
    Card (color copy) <br>C - Provide a certificate of Iraqi nationality of his father or one of his brothers or
    uncles with the identity of one of the Civil Status (colored copy). <br>D - Attach recent photograph of the
    applicant. <br>E - Attach (A page of works model No. 2) referred to in item (1) above after filling by the
    citizen and fixing the personal photo of the applicant and stamp it by the stamp of the consular and taking
    the imprint of his left thumb and then sign it by the consul and stamp it by Consular stamp. <br>(The Circulating
    letter by Consular Department No. 08.04.22 / 87823 dated 09.26.2010). <br>B - Discarding Iraqi citizenship: -
    <br>For the purpose of issuing a decision for Iraqis who want to discard the Iraqi nationality in accordance with
    the provisions of Article (10) of the first Iraqi Nationality Law No. (26) of 2006, which states the following: -
    <br>((Iraqi that acquires a foreign nationality can retain his Iraqi nationality unless he declares in a statement
    for abandoning his Iraqi citizenship)). For the purpose of implementing this article follow the following mechanism
    for the promotion of the papers of abandoning Iraqi citizenship: - <br>1. Submit a request to abandon the Iraqi
    nationality in accordance with the model number (1) the facility and fill out by the Iraqi students to give up his
    citizenship after taking a thumb print and signature as well as the signature of the consul or embassy employee in
    charge and stamped the stamp of the consular section. <br>2. With the request Iraqi archives of the applicant must
    be sent out. They are namely: - <br>A. Iraqi nationality certificate and if this is not possible to send a copy of
    the certificate but must say why not sending out the original certificate. <br>B. If the applicant was unable to
    send the original certificate or a copy send a copy of the certificate of nationality of his father or one of his
    brothers or sisters and taken pledge from him to that he lost the certificate in accordance with the pledge form
    (2) Appendix <br>C. The applicant must send out the Civil Status Card, and if could not he must send a copy and if
    this is not possible and submitting a photocopy of the identity of the of his father or one of his brothers to
    deduce them from the store recorded in the records of the 1957 census and take from him a pledge that he lost his
    or her identity of the Civil Status. Model No.(3) (The letter of the Nationality Directorate G St. No. 6/2007/301
    in 18/01/2007) <br>D. He must send the original Iraqi effective passport in and in the case a person claims that
    his passport had been damaged or lost, he has to prove his claim to provide the following: - <br>1. Submit a letter
    of endorsement issued from directories of residence and certified by the Ministry of Foreign Affairs of the State
    of residence of the lack of possession of a passport.<br>2 . The photo must be stamped by the embassy\'s stamp.<br>
    3 . Provide a written pledge by the citizen according to the form (4) in which he undertakes to not having a
    passport.<br>(The Circulating letter of the Consular Department No. 08.04.22 / 87122 of 09/26/2010)<br> In
    addition to that the Directorate for Nationality approaches the Directorate of Passports to install his or her
    full name with the place and date of his birth and his mother\'s name and the registration number with the page
    of works to the Civil Status Card and the number and date of certificate Iraqi nationality in order to make
    sure he is not getting an Iraqi passport, as well as any other Iraqi documents.<br>E . In light of the foregoing,
    and after the implementation of the above items Directorate for Nationality issues a decision includes
    consideration the person abandoned his nationality and the freezing of his registration for the 1957 and sends
    the decision to the Ministry of Foreign Affairs / Consular Department for the purpose of sending it to the embassy
    concerned with a view to informing the concerned authorities.<br>C - Restore Iraqi Nationality: -<br>Iraqi
    Nationality Law No. (26) for the year 2006 includes the articles about recovering Iraqi nationality, namely:
    -<br>1 . Article (10) Third, states the following: -<br>(An Iraqi who gave up his nationality can recover it
    if he returned to Iraq in a legitimate manner and stayed in it no less than one year. The Minister to consider
    after which acquired the nationality of Iraq from the date of his return, and if he applied to recover Iraqi
    nationality before the expiry of the period mentioned. This right can be taken only once).<br>2 . Article (18)
    first states the following: -<br>(Every Iraqi dropped his Iraqi nationality for political, racial or sectarian
    reasons can recover it by applying to it. In case of his death his children who have lost their Iraqi nationality
    according to their father or their mother can apply to recover Iraqi nationality).<br>In light of the two articles
    above the following procedures to be followed when submitting a request to restore the Iraqi nationality for those
    who lost their nationality because of acquiring foreign nationality in a foreign country or dropped their
    nationality for political, racial or sectarian reasons: -<br>1.The citizen should present a request requesting
    the restore of Iraqi nationality and there is no special form to do so.<br>2.He should present a photocopy of
    the certificate of Iraqi nationality or a certificate of nationality of his father or a brother or a sister and
    the Civil Status Card of him and any other document.<br>3. He should present the record of 1957 under which all
    explanations are included.<br>4. He or she should present a copy of his foreign passport.<br>5 . He should present
    housing or placebo- card support housing.<br>6.He should attach recent (2) photos.<br>7. The person should appear
    in person or authorize any person to follow-up his papers in the concerned departments and pay fees and fiscal
    stamps and forms for these departments. (The Circulating letter of Consulate Department No. 04.08.21 / 40029 of
    08/01/2007)<br> (The letter of the Directorate of Nationality No. 5197 on 04.04.2005)<br>D - Nationality of Iraqi
    nationality:-<br>1-Naturalization of the wife of the Iraqi <br>Article (11) of the Nationality Law No. (26) For
    the year 2006 stated on the following: <br>(Non-Iraqi women married to Iraqi to may gain Iraqi citizenship) under
    the following conditions:-<br>A – She must submit a request to the Minister of the Interior.<br>B –Five years must
    be passed on her marriage and set up in Iraq.<br>C _The marital bond must be continued until the date of submission
    of the application except the one who is divorced or her husband died and she had a son from that husband.<br>2 –
    To get Nationality for the husband of the Iraqi woman.<br>Article (7) of the Iraqi Nationality Law No. ( 26) for
    the year 2006 stated the following :<br>(The Minister may accept to give non Iraqi man the nationality of Iraq for
    who is married to an Iraqi nationality woman) if he fulfills the following conditions: -<br>A – He must enter Iraq
    legally and he is a resident in it when he applies for nationality with the exception those born and resided in Iraq
    and the holders of the civil status card but they did not receive a certificate of Iraqi nationality.<br>B – His
    residence in Iraq not less than five consecutive years prior to the submission of the application with the survival
    of the marital bond .<br>C . He must be of good behavior and reputation and not sentenced to a felony or misdemeanor
    involving moral turpitude.<br>D - To be safe from the transition disease.<br>E - To have a clear way to live.<br>3-
    Granting Iraqi nationality to the children of Iraqi women.<br>It is possible to grant nationality to the children of
    Iraqi women from foreign nationality in accordance with the provisions of Articles 3 / 4 and A / First of Iraqi
    Nationality Law No. (26) of 2006 , which stated as follows:<br>A - Article 3 / A (Anybody who born to an Iraqi
    father or an Iraqi mother can be considered an Iraqi). <br>B - Article 4 / I (The minister can consider who is born
    out of Iraq from an Iraqi mother and an unknown father or has no Iraqi nationality if he chose that within a year
    from the date of adulthood, unless difficult circumstances prevented without it, provided that he is a resident in
    Iraq at the time of the application for obtain Iraqi nationality).<br>Special conditions to apply Article 3 / a:<br>1
    – He must provide a statement of foreign birth (original copy) certified by the Embassy of the State in which the
    child was born.<br>2- He must submit a copy of his foreign passport.<br>3- Submitting a copy of the certificate of
    Iraqi nationality and identity of the Civil Status of Iraqi mother.<br>4-Submitting a marriage contract translated
    into Arabic and endorsed by our embassy there.<br>5- The marriage of the Iraqi woman must be indicated in the
    records of civil status and in the absence of indicating the marriage the Civil Affairs Department must be addressed
    by the Consular Department before involving in the process of granting the Iraqi nationality.<br>6-Writing down
    testimony of the statement of the applicant and his mother\'s testimony in detail by the embassy.<br>7- The mother
    must of Iraqi nationality, while the birth of her son.<br>8- The Embassy sends the request with the above archives
    to the Nationality Directorate.<br>9- After that the Directorate for Nationality issues a decision considering the
    son an Iraqi in accordance with the provisions of Article 3 / A LN above and informs the Directorate of Civil Status
    / Records to play their role to instruct the Department of Civil Status Registration where his mother recorded for
    the purpose of registration in their records and give him the Civil Status Card.<br>10 - The attendance of the
    caller or his mother or his legal representative and mandatory is compulsory for the purpose of following up the
    Directorate of Nationality and completing the steps above and then following up the Directorate of Civil Status to
    complete stages to obtain the Civil Status Card, note that the Civil Status Card and Iraqi nationality certificate
    is not delivered only to its rightful owner.<br> (The letter of Nationality Directorate St. X / 245 / 2006/7685 on
    23.08.2006).<br>For the purpose of the application of Article 3 / follow up the following mechanism,: -<br>1- Iraqi
    citizenship who is married to an Arab or a foreign national should go to the Nationality Directorate for the purpose
    to state the position of her son from Iraqi Nationality Law No. 26 Year 2006 concerning the duration of residence in
    Iraq.<br>2- Provide a certificate of birth if the birth occurred in Iraq and the Arab or foreign birth if birth
    occurred outside the country certified by the concerned embassy.<br>3. It is then recorded in the records of Civil
    Status of Statistics in 1957 under the Iraqi birth certificate if the birth in Iraq or in a manner renewed
    registration certificate if it non-Iraqi (Arab / foreign).<br>4– Then he is given the identity card according to the
    provisions of the Civil Status Law No. 65 of 1972 as amended and then it is possible to obtain a certificate of
    Iraqi nationality. (The letter of the Consular Department 08.04.22 / 97554 of 12/22/2010).<br>For Iraqi children
    covered by Article 4 / first, it requires the availability of the following conditions: -<br>A - Submitting a
    request to the Minister of the Interior for a certificate of Iraqi nationality.<br>B – He has to be a resident in
    Iraq at the time the application submission.<br>C - His chosen for the Iraqi nationality must be within one year
    from the date of attaining the age of adulthood unless difficult circumstances prevented that.<br> 4 - Nationality
    of foreigners born in Iraq<br>Article (5) of the Iraqi Nationality Law No. (26) for the year 2006 stated the
    following : -<br>(The Minister may consider an Iraqi that is born in Iraq and has reached the age of adulthood in it
    from a non-Iraqi father, who is also a resident routinely at the birth of his son on a condition that the son offers
    a request to grant the Iraqi nationality).<br>5-Granting Nationality to non- Iraqi <br>Article (6) the Iraqi
    Nationality Law No. (26) For the year 2006 stated on the following: -<br>First: The Minister may accept the
    nationality of non- Iraqi when the following conditions are available;<br>A – He must be adult.<br>B – He must enter
    Iraq legally and a resident in it when you apply for nationality with the exception of those born in Iraq or the
    residents in it and those who obtain the Civil Status Card and did not get a nationality certificate .<br>C –Those
    who resided legally in Iraq for at least ten consecutive years prior to the submission of the application.<br>D – He
    must be of good behavior and reputation and not judged by a felony or misdemeanor involving moral turpitude.<br>E
    –He must have a clear way to live.<br>F – He must be safe from the disease.<br>Secondly, Iraqi nationality may not
    be granted to the Palestinians to ensure the right to return to their homeland.<br>Third: - Iraqi nationality shall
    not be granted for the purposes of the policy of resettlement residential demographics in Iraq.<br>Fourth: - All
    decisions of granting nationality issued by the Iraqi regime to achieve its objectives to be
    re-examined.') ?>
</p><br>
