<?php $this->headTitle($this->translate('Non Conviction Certificate')) ?>
<h1><?php echo $this->translate('Non Conviction Certificate') ?></h1>
<p>
    <?php echo $this->translate('First: How to obtain a Non Conviction Certificates (Certificates of Good
    Conduct) :<br>In order to help the Iraqi citizens living abroad ,or Arabs
    and foreigners who have already reside in Iraq, obtaining a Non Conviction
    Certificates , they need to follow these steps : -<br>1 . To apply for
    getting the certificate to the consul or his nominee , according to the
    application form (No. 3 ) .<br>2 – To write down accurately all information
    in the record of the applicant according to the form number (2).<br>3 . To
    write down accurately all information in the finger prints form according to
    form number (5).<br>4 . To put fingers prints of the certificate requester
    clearly according to the form number (6).<br>5 . To attach a passport
    photocopy of the certificate requester .<br>6 . To attach four new colored
    photographs.<br>7 . An amount of (10,000 ) ten thousand Iraqi dinars to be
    collected by the Directorate of Criminal Evidences Investigations in Baghdad
    ( letter of the Consular Department No. m . G 01/26/1460 at 03/24/2011 )
    .<br>8 . To send all that has been mentioned in the paragraphs above along
    with a letter from the embassy to the Directorate of Criminal Evidences
    Investigations. Then the certificate to be issued and brought back to the
    mission in the same way it was received.<br>9 . It is necessity to write the
    name of the certificate requester in a foreign language according to his
    passport.<br><br> Please note the following: -<br>1 . The form of the
    certificate to be given for the Iraqis is the same to be given for the Arabs
    or foreigners who have already staying in Iraq .<br>2 . The certificate
    issued needs no ratification by the Ministry of Interior.<br>3 . To put the
    left hand thumb print of the requester in the proper field on the
    certificate under the supervision of the embassy\'s competent official.<br>4
    . To use black ink instead of the blue when taking fingerprints .') ?><br><br>
</p>