<?php $this->headTitle($this->translate('Palestinian Travel Documents')) ?>
<h1><?php echo $this->translate('Palestinian Travel Documents') ?></h1>
<p>
<?php echo $this->translate('The Directorate of Residence / Arabs Department issuing a travel document
    for Palestinian resident in Iraq, under the auspices of the Iraqi
    government. And because of the special circumstances of the Iraqi Diplomatic
    Missions abroad at the present time it does not issue such documents, but
    when the Palestinian document holder issued by the Iraqi Missions or from
    Iraq for following up, the Mission should send a telegram or a letter to the
    Ministry of Foreign Affairs/Consular Department to inform them of the number
    of document, the date of issue, place of issuance, the name of the holder,
    the name of his accompanying and informing the Ministry what is required
    (renewal document request, extension request, adding the wife or adding a
    child to the document) and no action will taken until receiving the answer
    of the Ministry of Foreign Affairs / Consular Department , and when the
    renewal or extension of the document completed by the Directorate of
    Residence / Department Arabs, the document send to the concerned Diplomatic
    Mission by diplomatic pouch through the consular Department or delivered to
    the authorized person in order to be sent to the applicant (owner of the
    document).<br>Below the new mechanism to issue the document: -<br>1 - The
    Iraqi travel document granted according to the Palestinian travel documents
    law no. (65) For the year (1983).<br>2 - The Iraqi travel document granted
    to the Palestinians refugee in year (1984) only.<br>3 - Submitting a request
    to grant the document for the citizen to one of our Missions abroad and
    sending old document, if the citizen had it in the past, and the Mission
    should send the request with it annexes to the Ministry of Foreign
    Affairs/Consular Department which in turn sends the request to the
    Directorate of Residence/Department Arabs to issue document.<br>4 - Power of
    Attorney to authorized person inside Iraq, a private Power of Attorney for
    the purpose of following up with Directorate of Residence / Department of
    the Arabs, and the document proceed (issued) after the ratification of the
    Power of Attorney by one of our Missions abroad and then by the Ministry of
    Foreign Affairs / Department of Ratifications.<br>5 - The authorized person
    who have the Power of Attorney following up with the Ministry of
    Displacement and Migration for the purpose of bringing a letter that
    supports the Palestinian document request from (1948) refugees, sending the
    letter by official mail and a letter from the Embassy of the State of
    Palestine in Baghdad to support that the document request does not have a
    Palestinian Authority passport. <br>6 - The authorized person who has the
    Power of Attorney request to obtain security clearance to issue the document
    according to the contexts then the document issued and sent to the concerned
    Mission through Diplomatic Pouch of the Ministry of Foreign Affairs/Consular
    Department or delivered to the authorized person for the purpose of sending
    the document to owner. <br><br>The extension for the new document shall be
    the following: -<br>1 - Either sending the request to extend the document
    via one of our Missions abroad to the Ministry of Foreign Affairs/Consular
    Department, which in turn sends the request to the Directorate of Residency/
    Arabs Department, where it extended and returned to the Embassy by
    Diplomatic Pouch through the Consular Department of the Ministry of Foreign
    Affairs.<br>2 - Or sending the document by the applicant directly to
    authorized person in Iraq, according to private Power of Attorney certified
    by the Iraqi Embassy and the authorized person upon receiving the Power of
    Attorney needed for ratification by the Consular Department of the Ministry
    of Foreign Affairs/Department of Ratifications, then it be extended by the
    Directorate of Residence and delivered to the authorized person for the
    purpose of sending the document to the owner.<br>(Letter No. 2/6
    /General/22462 of 19 June 2011)') ?><br><br></p>