<?php $this->headTitle($this->translate('Passport Issuance')) ?>
<h1><?php echo $this->translate('Passport Ossiance') ?></h1>
<p>
    <?php echo $this->translate('If the citizen loses his passport then he needs a
    new passport .<br>First: Some Instructions for a new passport issuance :<br>-
    if the citizen possesses no identity documents , he contact his family in
    Iraq and ask them to take original documents that prove his Iraqi
    nationality to the Consular Department which inform the embassy with
    that.<br>- It is possible to issue a passport for the child, regardless of
    their age after getting an approval from his parents .<br>- it is not
    possible to issue a passport based only on the Civil Status Card , without
    the nationality certification.<br>- The new citizenship law no. (26) 2006
    and in its Article 10 authorizes dual nationality, so it is possible for an
    Iraq citizen to get an Iraqi passport, despite having a foreign nationality
    unless he declares a written abandonment of the Iraqi nationality.<br>- An
    applicant for a passport should be present in person to the mission.<br>-
    Applications for a passport for women and children living outside Iraq,
    needs no approval of those charged with authority.<br>- The old personal
    documents can be used in condition that the embassy employee confirms that
    the applicant himself holds those documents.<br>- The identity card of
    children under one year of age, which include not photo can be used after
    submitting a letter of support from the embassy with a photo of the
    applicant.<br>- The naturalized winning the Iraqi citizenship under the new
    law No. (26) 2006 needs to provide a nationality certificate.<br>- Passports
    to be issued only from the Ministry not from the missions.<br>- A passport
    of an Iraqi citizens should not be taken back only by a decision of the
    higher authorities.<br>Some instructions for Iraqi passports currently in
    force :<br>1 . Passport Edition (S) , issued in 2004<br>This Edition is
    valid for eight years starting from the date of issuance not from the date
    of validity and if it\'s already been extended and expired it will not be
    extended.<br><br>2 . Passport Electronic Edition (G) 2006 <br>A – Validity
    of this edition is eight years with no extension .<br>B - On 10/07/2009
    Directorate of Passports stopped completely issuing this edition , and
    considered all passports of this category (G) , which issued by the
    aforementioned office in 2006 and became effective until the date of
    validity , and could not be replaced unless its pages ended or become
    invalid .<br>3 . Passport edition (A) 2009<br>A - this edition issued in
    2009 and considered as a completion of the passport edition (G) but not a
    substitution for it . Anyone who holds the passport edition (G) cannot be
    granted a passport of edition (A) unless it ends its pages or became invalid
    .<br>B - The missions organized the palpations for these passports and sent
    them electronically to the Directorate of Passports for printing them and
    send them to the missions concerned.<br>C – Validity of these passports is
    eight years and could not be extended.<br>D – Issuance of these passports
    are currently in Iraq (Directorate of Passports) .<br>E - The form no. (1)
    is used at the present time for obtaining the passport (A).<br><br>Requirements
    for obtaining passport Edition (A)<br>1 - Fill in the form of application
    accurately in both Arabic and English languages published on the web site of
    the Passports Directorate following the link :
    WWW.IRAQINATIONALITY.GOV.IQ.com<br>2 – Signature to be put on the right box
    and thumbprint in the left box.<br>3 - The applicant\'s photo to be stamped
    with the consular seal .<br>4 – The form should be signed by the consul with
    the consular stamped seal .<br>5 - The form and the attachments should be
    sent electronically to the Directorate of Passports:<br>Attachments of the
    passport application for edition (A): <br>A –fee is (20) U.S. dollars or its
    equivalent in other currencies .<br>B - Three color photos ( white
    background ) .<br>C - a color copy of a the nationality card .<br>D - a
    color copy of the Civil Status Document .') ?><br><br><br><br></p>