<?php $this->headTitle($this->translate('Pass Doc')) ?>
<h1><?php echo $this->translate('Pass Doc') ?></h1>
<p>
<?php echo $this->translate('Ithas 6 months validity from the date of issuance, the bearer has the right to
    enter Iraq once and the Consul at the mission is permitted, if necessary, to
    add other countries and accompanying persons. It is granted in the following
    cases: -<br>1. When the citizen loses his/her/her passport and is willing to
    return to Iraq.<br>2. In case of withdrawing a citizen\'s passport and wants
    to return to Iraq.<br>3. In case of deporting an indigent person to
    Iraq.<br>4 .In case when a foreigner that enters Iraq from an unknown
    destination, or bears a nationality of a state that has no representation in
    Iraq and wants to travel to his/her state or a state that accepts
    him.<br><br>Documents relied upon to prove in regards to paragraph (1) above<br>A.
    national identity Card. <br>B. Citizenship Certificate.<br>C. Copy of valid
    passport.<br><br>The citizen fills a form containing information about
    his/her name, birth date, place of residence, and former passport number if
    any, his/her address in Iraq with the names and addresses of people he
    knows. <br><br>Procedures for the issuance Passport Laissez<br>1. The
    information is written in the record issuance of the passport Laissez,
    appendix No. 1, as well as a photo of the citizen in addition to indicating
    the documents on which the issuance of the passport counted.<br>2. The
    information and photo of the citizen and accompanying citizens are put in
    the passport; the photos are stamped with the Consulate stamp.<br>3. Writing
    the passport number and date of issuance and expiry (which usually is
    limited to six months).<br>4. Notes in the visas page are put as follows: We
    have issued this passport for the loss of the passport of the holder to
    enable him to return to Iraq.<br>5. The passport is signed by the Consul and
    stamped by the consular stamp, the name of the Consul is written in both
    languages.<br><span style="font-weight: bold;">Note: -</span><br>1 - This
    passport is used for a single trip, to return to Iraq, and is delivered at
    the point of entry into the Iraqi territories.<br>2 - It is necessary to
    write the reason for granting the passport in one of its pages and send a
    telegram to the Consular Department with the passport number and date of
    issuance and the border point through which the citizen wishes to enter to
    inform the concerned authorities on time.') ?>' <br><br></p>