<?php $this->headTitle($this->translate('Patrimonies')) ?>
<h1><?php echo $this->translate('Patrimonies') ?></h1>
<p>
    <?php echo $this->translate('It is all that is left by the deceased such as movable
    and immovable property such like, real estate and vehicles , furniture,
    jewelries and so on.<br>Due to the presence of large numbers of Iraqi
    citizens abroad, there will be certainly, at death, patrimony that related
    to the inheritors as indicated in the legitimate share document, and here
    comes the role of the consul in the follow-up of these legacies after being
    authorized by relatives of the deceased ( the legal heirs ) either alone or
    with a lawyer for obtaining their share in the patrimony , but in order to
    do so the Consul turn asks the Ministry of Foreign Affairs / consular
    Department to contact relatives of the deceased to prepare the following:
    -<br>(1) The Legal Share Document (which determines names of the people who
    have the right of the patrimony)<br>(2) The authorization paper that was
    organized by the heirs indicated in the Legal Share Document to authorize
    the consul to follow the patrimony. The authorization documents should be
    certified before the being sent to the consul by the central bank , the Tax
    Office and Consular Department in the Ministry of Foreign Affairs , and the
    Consular Department sends them to the Embassy and when received by the
    consul he do the following : -<br>1 . Open a special file with the name of
    the deceased person , date , cause and place of the death . Inside he put
    the Legal Share Document, the authorization paper and all documents and
    correspondences relating to the patrimony.<br>2 . The consul contacts the
    Ministry of Foreign Affairs of the State in which the patrimony exists in
    order to settle it and determine the deserves of the deceased.<br>3 . In the
    case of a non-cash assets such as furniture , cars or real estate , the
    consul liquidates the patrimony through the specialized courts and to
    identify the means by which he carries out the liquidation either by auction
    or by delivering it to the beneficiaries bodies and to agree on pricing them
    , and after converting these patrimonies into cashes , expenses of the
    attorney and other expenses shall be deducted.<br>4. To write a check to the
    Iraqi Central Bank with foreign currency and to be sent to the Consular
    Department at the Foreign Ministry with reference to the patrimony and the
    name of the decedent and persons covered by inheritance . The Ministry of
    Foreign Affairs sends the check to the Central Bank .<br>5 . The Consul
    sends the authorization and the Legal Share Document to the ministry
    (Consular Department) which sends them back to the Tax Board.<br>Note :<br>Dealing
    with the patrimony funds outside or inside Iraq can be done only through the
    Central Bank and the tax Board , and the consul would not agree to any
    authorization allows the lawyer to sell , to mortgage and collect
    cash.') ?><br><br></p>