<?php $this->headTitle($this->translate('Ratifications')) ?>
<h1><?php echo $this->translate('Ratifications') ?></h1>
<p>
    <?php echo $this->translate('First - the ratification procedures of the stamp: -<br>The embassies and
    consulates ratify the Iraqi and foreign documents, which is carried out
    basing on the law of ratification of signatures on the Iraqi and foreign
    documents number (52) of 1970 and its amendments. The ratification is done
    on authorizations and documents used inside Iraq and signed in a foreign
    country and organized according to the law, if endorsed by the Iraqi consul
    or his/her replacement, the ratifications include: -<br>1.The ratification
    of the stamp and signature, whether for institutions or individuals. The
    concept of the ratification of document differs from the concept of the
    ratification of the signature; the first means the ratification of what is
    in the document, while the second means to ratify the validity of the
    signature after signing in front of the Consul and to identify the person or
    compare the signature with an existing signature previously in the mission
    in a formal way.<br>2.Certificate of origin and trade lists.<br>3.
    Graduation certificates or various school documents.<br><br>Second – Basic
    terms of ratification: -<br>1. The document or certificate must be issued by
    a foreign body and ratified by the Ministry of Foreign Affairs of the
    country which released the document or certificate in order to be ratified
    by the mission and then by the Department of Ratifications in the Consular
    Department.<br><br>2. The ratification of a certificate of origin, also
    concentrates on the content as well as the stamp.<br>3. The ratification of
    university or institute certificate after the ratification of the Foreign
    Ministry of the country that issued this certificate (in case the applicant
    is the ratification applicant is Iraqi), taking into account the fact that
    the institute or university is recognized in Iraq. <br>4. Copies of
    signatures of the authorized of signing are sent by both the Ministry of
    Foreign Affairs of the country concerned or the Chamber of Commerce to the
    embassy annually or whenever it was changed. Stamp and signature must be
    verified and matched accurately. <br>5. Documents, lists, and certificates
    issued from inside Iraq may not be ratified unless they were certified by
    the Department of ratifications of the Consular Department at the Ministry
    of Foreign Affairs and signed by the authorizing persons exclusively and
    stamped.<br>6. A fee for the ratification of documents is taken accounting
    to receipt (37 a) its number and date on are written on the back of the
    authorization.<br>7. In case there was no Iraqi mission in the concerned
    country, the ratification of a document is ratified by that country\'s
    mission in Iraq, and then approved by the Department of Ratifications in the
    Iraqi Consular Department.<br>8. In case there was no Iraqi mission in the
    country in which the document was issued, and there was no mission of that
    country in Iraq, then the ratification of a document or certificate is done
    in another country where there are missions to that country and an Iraqi
    mission in order to be approved by the two missions and then ratified by
    Department of Ratifications in the Consular Department.<br>9. Documents
    issued by the diplomatic and consular missions and international and
    regional organizations that operate in Iraq that concern their members and
    employees are exempted from the fees in accordance with the provisions of
    international relations and international conventions.<br><br>Third - the
    procedures for the ratification process: -<br>1. The Consul ratifies the
    signature and stamp of the Ministry of Foreign Affairs of the country where
    the mission is located. He also signs and ratifies the signatures of
    individuals in case of testifying or granting authorization (general or
    limited)<br>2. Documents are stamped by the consulate stamp for
    ratifications and the blanks in the ratification page are filled, i.e., (we
    ratify the validity of the stamp and signature ............. and the Foreign
    Ministry……….. the Embassy is not responsible for their contents).<br>3. The
    Consul signs it and stamps it with the stamp of the Consular Department.<br>4.
    Taking the ratification fee under receipt number (37 a), writing its number
    and date on the back of the document.<br>5. The mission organizes a record
    in which it writes all of the information about the documents ratified by
    the mission in the attached form (1).<br><br>Fourth - fees of certificates
    of origin, trade lists, and certificates of inspection: -<br>Fees are taken
    for the ratification of certificates of origin, trade lists, and
    certificates of inspection in accordance to the law of ratification of
    signatures and Iraqi and foreign documents number (52) of 1970 and as shown
    below: -<br>1. The ratification of the aforementioned documents by
    commercial attaché or Iraqi missions in case of the absence of commercial
    attaché; $160 U.S. dollars or its equivalent per process is taken as well as
    for certificates of origin and commercial lists and inspection certificates,
    taking into account stamping all copies with the round stamp of the embassy
    to avoid forgery, providing that all copies have to be stamped on top to
    avoid cancelling any document (letter of the Consular Department No.
    8/9/1/70440 on 7/4/2010).<br>2. Commercial lists\' and certificates of
    origin\'s contents must be ratified, because the ratification of the
    signatures is not enough. The ratification of the aforementioned documents
    issued by a Member State in the Arab Common Market and ratified by the
    official reference in the country of origin of the goods produced in Arab
    countries (without taking fee of ratification) in accordance with the
    Economic and Social Council of the Arab League Decree No. 1506 on 2/19/2004
    and the approval of the Ministerial Council/ Economic Affairs Committee in
    its letter No. 1320 on 26/2/2007 which states abolishing the ratification of
    the certificates of origin and commercial lists attached with them,
    preserving Iraq\'s right to reciprocity.<br>3. The following procedures are
    adopted in as much as it is related to goods manufactured in non-Arab
    countries and exported to Iraqi market: -<br>A- The ratification of the
    embassies or consulates of the manufacturing countries in the light of the
    certificate of origin exported to the Arab countries.<br>B– The ratification
    of the Ministry of Foreign Affairs of the Arab countries exporting goods
    such as re-exporting to Iraq on the ratification of the stamp of the
    Consulates of the manufacturing countries.<br>C- Ratification fees of $160
    per ratification and putting stamp on all pages.<br>D- Taking into account
    that the goods are produced by the same producing countries and write it
    upon ratification to avoid forgery in case the ratification was done in a
    country other than the country of origin.<br>Letter of Consular Department
    (8/9/1/83159 on 11/8/2010) and (8/9/1/70440 on 7/4/2010)') ?>

<p>