<!DOCTYPE html>
<html>
<head>
    <link href="http://dev.hoaxinh.net/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="http://dev.hoaxinh.net/css/site.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.css" media="screen"
          rel="stylesheet" type="text/css">
    <link href="http://dev.hoaxinh.net/css/style.css" media="screen" rel="stylesheet" type="text/css">
    <!-- BEGIN Grabbed Website Stylesheets -->
    <link href="../css/englishstyle.css" rel="stylesheet" type="text/css"/>
    <link href="../css/topnews.css" rel="stylesheet" type="text/css"/>
    <link type="text/css" rel="stylesheet" href="../css/style.css"/>
    <!-- END Grabbed Website Stylesheets -->
</head>
<body>
<div class="container">
    <div id="main-content">
        <!-- BEGIN Container -->
        <div id="content-container">
            <!-- BEGIN Section Navigation -->
            <div id="section-navigation">
                <div class="content_leftheader"><span class="title">Services for Iraqi Citizen</span></div>
                <div class="qucikmenu">
                    <ul>
                        <li><a href="birth-certificate.html"> Birth certificate</a></li>
                        <li><a href="marriage-divorces-registration.html"> Marriage/ divorces registration</a></li>
                        <li><a href="the-civil-status-id.html"> The Civil Status ID</a></li>
                        <li><a href="nationality-cert.html"> Nationality Cert.</a></li>
                        <li><a href="non-conviction-certificate.html"> Non-conviction certificate</a></li>
                        <li><a href="life-certificate.html"> life certificate</a></li>
                        <li><a href="pass-doc.html"> Pass doc.</a></li>
                        <li><a href="authorization.html"> Authorization</a></li>
                        <li><a href="forms.html"> Forms</a></li>
                        <li><a href="ratifications.html"> Ratifications</a></li>
                        <li><a href="faq.html"> FAQ</a></li>
                        <li><a href="fees.html"> Fees</a></li>
                        <li><a href="death-certificate.html"> Death Certifcates</a></li>
                        <li><a href="passport-system.html"> Passport System</a></li>
                        <li><a href="indigent-deportation.html"> Indigent deportation</a></li>
                        <li><a href="patrimonies.html"> Patrimonies</a></li>
                        <li><a href="approving-corpse-entry-to-iraq.html"> Approving Corpse Entry to Iraq</a></li>
                        <li><a href="passports-issuance.html"> Passports Issuance</a></li>
                        <li><a href="extension-of-passports.html"> Extension of passports</a></li>
                        <li><a href="loss-of-passports.html"> Loss of passports</a></li>
                        <li><a href="lawsuits.html"> Lawsuits</a></li>
                        <li><a href="general-affairs.html"> General Affairs</a></li>
                    </ul>
                </div>
                <div class="content_leftheader"><span class="title">Services for Foreign Nationality</span></div>
                <div class="qucikmenu">
                    <ul>
                        <li><a href="visa.html"> Visa</a></li>
                        <li><a href="ratifications-1.html"> Ratifications</a></li>
                        <li><a href="certificate-of-origin.html"> Certificate of origin</a></li>
                        <li><a href="forms-1.html"> Forms</a></li>
                        <li><a href="faq-1.html"> FAQ</a></li>
                        <li><a href="fees-1.html"> Fees</a></li>
                        <li><a href="palestinian-travel-documents.html"> Palestinian Travel Documents</a></li>
                    </ul>
                </div>
            </div>
            <!-- END Section Navigation -->
            <!-- BEGIN Page Content -->
            <div id="content">


                <span id="ctl00_Main_errormessage" class="htext"></span>

                <table id="ctl00_Main_Grid2" cellspacing="0" cellpadding="0" border="0"
                       style="width:438px;border-collapse:collapse;">
                    <tbody>
                    <tr>
                        <td valign="top">

                            <table width="438px" border="0" cellspacing="0" cellpadding="0">

                                <tbody>
                                <tr>
                                    <td colspan="2" valign="top"><br> <strong
                                            class="htext">Ratifications</strong><br><br></td>
                                </tr>

                                <tr>
                                    <td>
                                        <table width="140" border="0" cellspacing="0" cellpadding="0"
                                               bordercolor="#E5E5E5" height="21" dir="ltr">
                                            <tbody>
                                            <tr>
                                                <td width="68" align="left">

                                                </td>

                                            </tr>
                                            </tbody>
                                        </table>
                                        <hr>
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="2" valign="top">

                                        <p></p>

                                        <p><br></p>

                                        <p>&nbsp;<span style="font-weight: bold;">Requirements for the ratification of the documents and certificates: - </span><br><br>1
                                            - The document or certificate issued by a foreign authority must be
                                            certified by the Ministry of Foreign Affairs of that country to be ratified
                                            by the embassy and the Department of ratifications in the Consular
                                            Department. <br><br>2 - It is not permitted to ratify the documents and
                                            certificates issued from inside Iraq unless they are certified by the
                                            Department of ratifications of the Consular Department. <br><br>3 - In the
                                            absence of an Iraqi mission in the country the ratification of the document
                                            can be done in that mission in Iraq, and then be approved by the Department
                                            of ratifications in the Consular Department. <br><br>4 - In the absence of
                                            an Iraqi mission in the country in which the document was issued and the
                                            absence of the mission to that country in Iraq , the ratification of the
                                            document or certificate may be done in another country where there is a
                                            mission to that country and an Iraqi Mission in order to be approved by the
                                            two missions and then ratified by the Department of ratifications in the
                                            Consular Department.<span style="font-weight: bold;"></span></p>

                                        <p></p>

                                        <p></p><br>
                                    </td>
                                </tr>


                                </tbody>
                            </table>

                        </td>
                    </tr>
                    </tbody>
                </table>
                <br><br>
                <table id="ctl00_Main_grid3" cellspacing="0" cellpadding="0" border="0"
                       style="width:200px;border-collapse:collapse;">
                    <tbody>
                    <tr>
                        <td valign="top">
                        </td>
                    </tr>
                    </tbody>
                </table>
                <hr>


            </div>
            <!-- END Page Content -->
        </div>
        <!-- END Container -->
    </div>
</div>

</body>
</html>