<?php $this->headTitle($this->translate('The Civil Status Id')) ?>
<h1><?php echo $this->translate('The Civil Status Id') ?></h1>
<p>
<?php echo $this->translate('The Consular Section organizes the papers to obtain the Civil Status Card and send them to the General Directorate
    of Travel and Nationality / Directorate of Civil Status in accordance with the following steps : -<br>1.
    The citizen submits an application to the mission stating his or her need for the Civil Status Card.<br>2.
    The citizen attaches with the application form (Form Annex 1) the original copy, not the copied. This form
    is used to obtain the the Civil Status Card for the first time or to renew it or to get damaged or lost alternate
    form and stamp with the circular stamp of the consulate.<br>3. The form above filled in by the head of the family
    or family housewife or the owner of the record, or the guardian, or the legal agent signing in their explicit
    signatures as the contents serve as a personal acknowledgement of the correctness of what they stated.<br>The
    form includes the following information: -<br>The number of the page, the record, the name of the directory and
    the governorate, in which the registration happened according to the census of 1957 and full descriptions and the
    names of those the applicant wants to give them a personal card. The applicant must sign and write his full name
    and address in the cell provided and the form must be stamped by the consul.<br>4. Two 3 x 3 cm photos must be
    attached with the form and two copies of each person attached one in the box provided to the photo of the applicants
    and the second photo attached to it.<br>5. In case of request a lost identity replacement the Consul should write
    down the statement of the applicant in the back of the form in addition to the above. The statement must include
    answering three questions, namely, (Where do you think the place of loss of the identity card, when do you lost
    it and how do you lost it?) The statement must be signed by the applicant and install the full name and left thumb
    fingerprint and signed by the consul and stamped by the stamp of the consulate and sent with the application form
    a copy of the lost identity card, a copy of the identity card of his father, his brother or non married sister -
    certified by the consul being as a replica. In case of request damaged replacements the applicant must write down
    a statement signed by him and signed and stamped by the Consul and attach the damaged identity with the form. The
    applicant must attach with the application of lost replacement or damaged a recent photograph of him.<br>6. Any
    official document must be attached with the application to support the personality of the applicant.<br>7. Amount
    of (750) dinars is met, equivalent in foreign currency one dollar fee for the issuance of identity and under a
    receipt of accounting (37 A). (Consulate Letter No. 8 / 4 / 21/84715).<br>8. The embassy to send what is mentioned
    above in a letter to the General Directorate of Travel and Nationality / Directorate of Civil Status and a copy of
    it to the Consular Department for its information and for following-up and accelerating the completion of the
    documents.<br>9. The citizen can authorize one of the citizens inside Iraq (private authorization) to come to the
    Civil Affairs Department for the purpose of following-up.<br>10. The department of Nationality and Civil Status
    holds competent of auditing the information and then organize the Civil Status identity based on records in 1957
    and sent to the Ministry of Foreign Affairs to send it to the embassy or the mission concerned for the purpose
    of delivery to its owner.<br><br>Note: For the purpose of obtaining the Civil Status Card to the children of Iraqi
    citizens abroad this requires the following actions:<br><br>1. The citizen has to prove reality of his marriage
    to the Department of Civil Status of being married.<br>2. The citizen should mark the birth certificate of the
    newborn in the Department of Civil Status.<br>3. After Checking the items ( 1) and ( 2 ) above , the citizen can
    apply to the embassy for the purpose of obtaining the Civil Status Card to his children within the contexts the
    embassy informed by.') ?><br><br>
</p>
