<?php $this->headTitle($this->translate('Visa')) ?>
<h1><?php echo $this->translate('Visa') ?></h1>
<p>
<?php echo $this->translate('<span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">- Visa types:</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
1-Visit or Tourism Visa: - tourist\'s Visa allows the holder to enter Iraq once during the three months from
the date of grant and stay in it for a period of one month, for the purpose of visiting tourist and relic
sites. The visit Visa allows the holder to enter Iraq once during one month from the date of grant and the
residence of a one-month whether for the purposes of religious events or visit the holy sites (Letter of
the Consular Department No. 1/3 / 6/4664 on 16 Feb. 2011).</span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;">
Also Visa grant to the public and political figures, businessmen and investors and the
people who the Ambassadors and charge d\'affaires find interest in their visit to Iraq, according
to their judgment for a period of 30 days (Letter of the Consular Department No. 6 / 3/12162 on 26 March 2013).
</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
In the case of tourist groups offer applications precede through tourism companies in the work area of the
Mission in coordination with one of the officially licensed tourism companies in Iraq.</span></span><br>
<span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">2- Normal Visa: -
normal Visa allows the holder to enter Iraq once during the three months from the date of grant and
residence in Iraq a period not exceeding three months, he must visit the Directorate of residence to
put in the news of the arrival in ten days after his arrival and entered Iraqi territory (Letter of
the Consular Department No. 8/3/8/98609 on 14 Oct. 2009).</span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;">3 - Political Visa: - the political
Visa grant to officials in other countries who are visiting Iraq in official mission, as well as workers
in the Diplomatic, international, regional and Arab Missions in the Republic of Iraq with their families,
according to an official memo and granted under it a special residency. </span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;">4 - Service Visa: -service Visa grant to
people who hold Service passports on the basis of an official memorandum by the Ministry of Foreign Affairs
of the country in which the Mission accredited, pursuant to the principle of reciprocity. </span></span>
<br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
5 – Transit Visa: - transit visa allows the holder to enter Iraq once during the three months from the date of
grant and a residence for a period of not more than seven days.</span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;">6 – Non- stop Transit Visa: - this Visa
allows the holder to transit through Iraqi territory under the supervision of the competent authorities
without stopping and one-time within three months from the date of grant.</span></span><br>
<span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
7 - Urgent Visa: - this Visa granted by residency officer at border crossing points to a
foreigner who arrives intending entering Iraq, and he doesn’t have a visa from our Missions
abroad if the officer is convinced of the reasons that have prevented him to get a Visa.
</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
8 - Multi- Visa: - this Visa granted for a period of three months, six months or one year after obtaining the
legal conditions.</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
(Foreigners Residence law No. 118 for the year 1987, and its amended (Article IV) and (Letter of the Directorate of Residence/
the section of foreign No. 37344 on 22 Dec. 2009).</span></span><br><br><span class="longtext1"><span style="background-color:
white; color: black; font-size: 10pt;">Requirements of the Visa request </span></span><br><span class="longtext1"><span
style="background-color: white; color: black; font-size: 10pt;">        The following conditions must available in the
Visa request: -</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size:
10pt;">1 - The passport has validity for a period of minimum six months.</span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;">2 - Filling in a Visa application form with
two photographs.</span></span><br><span class="longtext1"><span style="background-color: white; color: black;
font-size: 10pt;">3 - Ability to cover the cost of living during the period of his stay in Iraq for holders of
ordinary passports.</span></span><br><span class="longtext1"><span style="background-color: white; color: black;
font-size: 10pt;">4 - There is no objection prevent him from entering the territory of the Republic of Iraq
regarding the public health, security, morals, or the national economy.</span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;">5 - Provide a convincing reason for visit
depending on the Visa type.</span></span><br><span class="longtext1"><span style="background-color: white; color:
black; font-size: 10pt;">6 – The requester not accused or convicted of a crime outside Iraq may be extradited for.</span></span><br>
<span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">7 - There is no order of deporting him
from the Republic of Iraq and to achieve this must check the records for the barred from entering Iraq in accordance with the attached
form (1).</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">8 – Full address
in the place, which he will stay in the Republic of Iraq.</span></span><br><span class="longtext1"><span style="background-color: white;
color: black; font-size: 10pt;">(Foreigner Residence law No. (118) for the year 1987, and the amended (Article V).</span></span><br><span
class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">Instructions for Issuing
Visa </span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
1 - checking the information in the application form No. (1), and checking the period of passport validity of the foreigner
Visa requester (minimum period of six months validity).</span></span><br><span class="longtext1"><span style="background-color:
white; color: black; font-size: 10pt;">2 - Recording information in the Visa record sample No. (2).</span></span><br><span
class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">3 – Writing number of companions next to the Visa if
their names written in the Visa applicant\'s passport.</span></span><br><span class="longtext1"><span style="background-color: white; color
: black; font-size: 10pt;">4 - The lack of clarity and calligraphy differs from one person to another are required to the adoption of electronic
printing filled the application form fields with and fields of the visa sticker, sample No. (3).</span></span><br><span class="longtext1"><span
style="background-color: white; color: black; font-size: 10pt;">(letter of the Consular Department No. 8/3 / General / 86 987 on 19 Oct. 2010)
and (8/3/1/89904 on 13 Oct. 2010)</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
5 - The need to full of all Visa application form\'s fields in Arabic, especially the applicant\'s address in Iraq (block /alley/House/ well-known point),
and the phone number for accelerating the answer to the Visa\'s requests. Noting that a lot the Missions still send application forms without
full of a lot of fields, especially the field of the address in Iraq (letter of the Consular Department No. 8/3 / General / 92543 on 1 Nov. 2010)
</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">6 – Visa signed by the consul and
stamped by the seal of the consulate.</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">
7 - Fees are collected for granting Visa according the accounting receipt (37 a) as follows:</span></span><br><span class="longtext1"><span
style="background-color: white; color: black; font-size: 10pt;">   A – Amount of (30$) U.S. dollars collected for granting tourist Visa arrivals
and religious visit Visa according to the especial approvals for religious tourism companies exclusively as groups and to all individuals
listed in the Visa lists, including companions in passports.</span></span><br><span class="longtext1"><span style="background-color: white;
color: black; font-size: 10pt;">   B – Amount of (40$) U.S. dollars collected for granting regular Visa, religious visit Visa and individual
Visa for passport holder and fees exempted for companions.</span></span><br><span class="longtext1"><span style="background-color: white;
color: black; font-size: 10pt;">   C - Amount of (100$) U.S. dollars collected for granting of multi- Visa.</span></span><br><span
class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">(letter of the Consular Department No. 8/3 / 4/80480
on 12 July 2010)</span></span><br><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">General
Notes for the Visa granting</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">1.
When the presence of banning to enter the territory of the Republic of Iraq to the cause of public health, national security, morals or the
national economy, can approach the Iraqi authorities to find out their opinion on the subject.</span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;">2. When a Visa granted for children under the age of fifteen, required
providing a health certificate to prove fully polio vaccine vaccinated for at least 5 doses of oral polio vaccine.  </span></span><br><span
class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">3. Exception for the Arab who married to Iraqis from
Arab Nationals prevents entering Iraq\'s law, after proves the marriage duly (letter of the Consular Department No. 03/08/28 / 40618 of 23 Jan.
2006).</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">4. Allowing for Arab and foreign
nationals who have resided lawfully in Iraq exclusively.</span></span><br><span class="longtext1"><span style="background-color: white; color: black;
font-size: 10pt;">5. Urgent Visa granted according to the authorities of the residence officer who works at the border Center, if he is convinced of
the reasons that have prevented the Visa obtaining ((includes persons covered by the authority of granting Visa of the Mission)).</span></span><br><span
class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">6. Correspondence related of Foreign Diplomats\' Visa
((granting visas)) to enter Iraq directed to the Protocol Department and a copy given to the Consular Department for informing. </span></span>
<br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">7. When a Visa granted, the number and date of
the Residency Directorate\'s letter should mentioned for the possibility of its conformity with the approval that sent to the residency and the
border.</span></span><br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;">8. The expired Visa not
extendable, but they can be to obtain a new approval with new fees, but in the exceptional cases, like, closing border, the center of Passports
and Residence at the border, will explain the situation on the Visa and allows them to enter without an extension or requesting a new approval,
but this should not exceed more than seven days from the re- open the border.</span></span><br><span class="longtext1"><span style="background-color:
white; color: black; font-size: 10pt;">9. Based on the letter of the Directorate of Residency, foreigners section number A. C / Visa / 1822 / 2011/29559
on 6 July 2011 containing ((to not grant visas or residency permits for foreign workers unless they obtain work permits from the Ministry of Labor and
Social Affairs)) with the exception of the following categories : -</span></span><br><span class="longtext1"><span style="background-color: white;
color: black; font-size: 10pt;"> A - Employed by International Organizations, Diplomatic Missions and Consulates accredited in Iraq.</span></span>
<br><span class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;"> B - Foreigners who the international laws,
conventions and treaties allow them to work, which the Government is a party in       them.</span></span><br><span class="longtext1">
<span style="background-color: white; color: black; font-size: 10pt;"> C – Foreigners who work for the Iraqi government, but are required
to provide the Directorate residence of a letter that supports the contract between the foreigners and Ministries, government departments
with filling out Visa application in Arabic language in order to take.</span></span><br><span class="longtext1"><span style="background-color:
white; color: black; font-size: 10pt;"> D - Foreign workers in the reconstruction of holy shrines in Iraq.</span></span><br><br><span
class="longtext1"><span style="background-color: white; color: black; font-size: 10pt;"></span></span>') ?>
</p>