<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/home-menu/AR/styles.css') ?>
<div id='cssmenu'>
<ul>
   <li class='has-sub'><a href='http://104.236.81.79/ar/the-ministry/the-minister'>السيد الوزير</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/ar/about-iraq/constitution'>دستور جمهورية العراق</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/ar/about-iraq/encyclopedia'>موسوعة العراق</a></li>
   <li class='active has-sub'><a href='http://104.236.81.79/ar/foreign-policy/human-rights'>حقوق الانسان</a>
   <li class='active has-sub'><a href='#'>اتفاقيات دولية</a>
   <ul>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844879731724108.pdf'>ميثاق الأمم المتحدة</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844857332101093.pdf'>اتفاقية جنيف الأولى</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844880963794783.pdf'>اتفاقية جنيف الثانية</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844883517939013.pdf'>اتفاقية جنيف الثالثة</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844885646757133.pdf'>اتفاقية جنيف الرابعة</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844894671733423.pdf'>البروتوكول الأول</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844899001871983.pdf'>البروتوكول الثاني</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844899674393503.pdf'>البروتوكول الثالث</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinabc.pdf'>اتفاقية فيننا للعلاقات القنصلية</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinabd.pdf'>ااتفاقية فيننا للعلاقات الدبلوماسية</a></li>
      <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinabd.pdf'>ااتفاقية فيننا للعلاقات الدبلوماسية</a></li>
	  </ul>
            <li class='has-sub'><a href='http://104.236.81.79/ar/news/arabic-ministry-s-announcements'>اعلانات الوزارة</a></li>
            <li class='has-sub'><a href='http://104.236.81.79/ar/news/arabic-announcements'>اعلانات تجارية</a></li>
            <li class='has-sub'><a href='http://104.236.81.79/ar/foreign-policy/international-organizations'>المنظمات الدولية</a></li>
</ul>
</div>
