<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/home-menu/AR/styles.css') ?>
<div id='cssmenu'>
<ul>
   <li class='has-sub'><a href='http://104.236.81.79/ar/the-ministry/the-minister'>السيد الوزير</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/ar/about-iraq/constitution'>دستور جمهورية العراق</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/ar/about-iraq/encyclopedia'>موسوعة العراق</a></li>
   <li class='active has-sub'><a href='http://104.236.81.79/ar/foreign-policy/human-rights'>حقوق الانسان</a>
   <li class='active has-sub'><a href='#'>اتفاقيات دولية</a>
   <ul>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844879731724108.pdf'>ميثاق الأمم المتحدة</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844857332101093.pdf'>اتفاقية جنيف الأولى</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844880963794783.pdf'>اتفاقية جنيف الثانية</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844883517939013.pdf'>اتفاقية جنيف الثالثة</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844885646757133.pdf'>اتفاقية جنيف الرابعة</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844894671733423.pdf'>البروتوكول الأول</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844899001871983.pdf'>البروتوكول الثاني</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/129844899674393503.pdf'>البروتوكول الثالث</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinabc.pdf'>اتفاقية فيننا للعلاقات القنصلية</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinabd.pdf'>اتفاقية فيننا للعلاقات الدبلوماسية</a></li>
      <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinabd.pdf'>اتفاقية فيننا للعلاقات الدبلوماسية</a></li>
	  </ul>
            <li class='has-sub'><a href='http://104.236.81.79/ar/news/arabic-ministry-s-announcements'>اعلانات الوزارة</a></li>
            <li class='has-sub'><a href='http://104.236.81.79/ar/news/arabic-announcements'>اعلانات تجارية</a></li>
            <li class='has-sub'><a href='http://104.236.81.79/ar/foreign-policy/international-organizations'>المنظمات الدولية</a></li>
</ul>
</div>
<div id="mofamissionurl">
<section class="selectm">
  <div class="dropdown">
    <select name="one" class="dropdown-select" onchange="location = this.options[this.selectedIndex].value;">
	<optgroup label="اوروبا">
      <option value="#">البعثات العراقية في الخارج</option>
    <option value="http://mofamissions.info/ab/CzechPr
">سفارة جمهورية العراق في الجيك - براغ
</option>
    <option value="http://mofamissions.info/ab/AustVien
">سفارة جمهورية العراق في النمسا - فيينا 
</option>
    <option value="http://mofamissions.info/ab/Belarus
">سفارة جمهورية العراق في بلاروسيا - منسك
</option>
    <option value="http://mofamissions.info/ab/Belgium
">سفارة جمهورية العراق في بلجيكا - بروكسل
</option>
    <option value="http://mofamissions.info/ab/Bulgaria
">سفارة جمهورية العراق في بلغاريا - صوفيا
</option>
    <option value="http://mofamissions.info/ab/Denmark
">سفارة جمهورية العراق في الدنمارك - كوبنهاكن
</option>
    <option value="http://mofamissions.info/ab/Finland
">سفارة جمهورية العراق في فنلندا - هلسنكي
</option>
    <option value="http://mofamissions.info/ab/France
">سفارة جمهورية العراق في فرنسا - باريس
</option>
    <option value="http://mofamissions.info/ab/Germany
">سفارة جمهورية العراق في المانيا - برلين
</option>
    <option value="http://mofamissions.info/ab/Greece
">سفارة جمهورية العراق في اليونان - اثينا 
</option>
    <option value="http://mofamissions.info/ab/Hungary
">سفارة جمهورية العراق في اليونان - اثينا 
</option>
    <option value="http://mofamissions.info/ab/Italian
">سفارة جمهورية العراق في ايطاليا - روما
</option>
    <option value="http://mofamissions.info/ab/Netherla
">سفارة جمهورية العراق في هولندا  - لاهاي
</option>
    <option value="http://mofamissions.info/ab/NorwayOs
">سفارة جمهورية العراق في النرويج - اوسلو
</option>
    <option value="http://mofamissions.info/ab/PolandWa
">سفارة جمهورية العراق في بولندا - وارشو
</option>
    <option value="http://mofamissions.info/ab/Portugal
">سفارة جمهورية العراق في البرتغال - لشبونة</option>
    <option value="http://mofamissions.info/ab/Romania
">سفارة جمهورية العراق في رومانيا - بوخارست
</option>
    <option value="http://mofamissions.info/ab/RomeVati
">سفارة جمهورية العراق في ايطاليا - الفاتيكان
</option>
    <option value="http://mofamissions.info/ab/SerbiaB
">سفارة جمهورية العراق في صربيا - بلغراد
</option>
    <option value="http://mofamissions.info/ab/Slovakia
">سفارة جمهورية العراق في سلوفاكيا - براتسلافا
</option>
    <option value="http://mofamissions.info/ab/SpainMa
">سفارة جمهورية العراق في أسبانيا - مدريد
</option>
    <option value="http://mofamissions.info/ab/SwedenS
">سفارة جمهورية العراق في  السويد - ستوكهولم
</option>
    <option value="http://mofamissions.info/ab/Switzerl
">سفارة جمهورية العراق في سويسرا - بيرن
</option>
    <option value="http://mofamissions.info/ab/UKLondon
">سفارة جمهورية العراق في بريطانيا  - لندن
</option>
    <option value="http://mofamissions.info/ab/Ukraine
">سفارة جمهورية العراق في اوكرانيا - كييف
</option>
    <option value="http://mofamissions.info/ab/GerFrank
">قنصلية جمهورية العراق في المانيا - فرانكفورت
</option>
    <option value="http://mofamissions.info/ab/UKManch
">قنصلية جمهورية العراق في انكلترا - مانشستر
</option>
    
  </optgroup>
  <optgroup label="امريكا الشمالية">
    <option value="http://mofamissions.info/ab/USANewY
">ممثلية جمهورية العراق في الأمم المتحدة - نيويورك
</option>
    <option value="http://mofamissions.info/ab/USADC
">سفارة جمهورية العراق في اميركا - واشنطن
</option>
    <option value="http://mofamissions.info/ab/USAD
">قنصلية جمهورية العراق في اميركا - ديترويت
</option>
    <option value="http://mofamissions.info/ab/CanadaMo
">قنصلية جمهورية العراق كندا - مونتريال
</option>
    <option value="http://mofamissions.info/ab/CanadaOt
">سفارة جمهورية العراق في كندا - اوتاوا
</option>
    <option value="http://mofamissions.info/ab/USALosAn">قنصلية جمهورية العراق في لوس انجلس
</option>
  </optgroup>
  <optgroup label="امريكا الجنوبية">
    <option value="http://mofamissions.info/ab/Brazilb
">سفارة جمهورية العراق في البرازيل - برازيليا
</option>
    <option value="http://mofamissions.info/ab/Buenos
">ســفارة جمهورية العراق في الارجنتين - بوينس ايرس
</option>
    <option value="http://mofamissions.info/ab/ChileSan
">سفارة جمهورية العراق في تشيلي - سانتياغو
</option>
    <option value="http://mofamissions.info/ab/MexicoM
">ســفارة جمهورية العراق في مكسيكو
</option>
    <option value="http://mofamissions.info/ab/Venezuel
">سفارة جمهورية العراق في فنزويلا - كراكاس
</option>
  </optgroup>
  <optgroup label="آسيا">
    <option value="http://mofamissions.info/ab/YemenSa
">سفارة جمهورية العراق في اليمن - صنعاء
</option>
    <option value="http://mofamissions.info/ab/Afghanst
">سفارة جمهورية العراق في افغانستان - كابل
</option>
    <option value="http://mofamissions.info/ab/Azerbaij
">سفارة جمهورية العراق في أذربيجان - باكو
</option>
    <option value="http://mofamissions.info/ab/Bahrain
">سفارة جمهورية العراق في البحرين - المنامة
</option>
    <option value="http://mofamissions.info/ab/Banglade
">سفارة جمهورية العراق في بنغلادش - دكا
</option>
    <option value="http://mofamissions.info/ab/ChinaBei
">سفارة جمهورية العراق في الصين - بكين
</option>
    <option value="http://mofamissions.info/ab/Emirates
">سفارة جمهرية العراق في الأمارات - أبو ظبي
</option>
    <option value="http://mofamissions.info/ab/Georgia
">سفارة جمهورية العراق في جورجيا - تبليسي
</option>
    <option value="http://mofamissions.info/ab/IndiaNew
">سفارة جمهورية العراق في الهند - نيودلهي
</option>
    <option value="http://mofamissions.info/ab/Indonesi
">سفارة جمهورية العراق في أندونيسيا - جاكرتا
</option>
    <option value="http://mofamissions.info/ab/IranTeh
">سفارة جمهورية العراق في أيران - طهران
</option>
    <option value="http://mofamissions.info/ab/JordanA
">سفارة جمهورية العراق في الاردن - عمان
</option>
    <option value="http://mofamissions.info/ab/Kazakhst
">سفارة جمهورية العراق في كازاخستان - استانا
</option>
    <option value="http://mofamissions.info/ab/Kuwait
">سفارة جمهورية العراق في الكويت - الكويت
</option>
    <option value="http://mofamissions.info/ab/Lebanese
">سفارة جمهورية العراق في لبنان - بيروت
</option>
    <option value="http://mofamissions.info/ab/Malaysia
">سفارة جمهورية العراق في ماليزيا - كوالالمبور
</option>
    <option value="http://mofamissions.info/ab/OmanMusc
">سفارة جمهورية العراق في سلطنة عمان - مسقط
</option>
    <option value="http://mofamissions.info/ab/Pakistan
">سفارة جمهورية العراق في باكستان - اسلام اباد
</option>
    <option value="http://mofamissions.info/ab/Philippi
">سفارة جمهورية العراق في الفلبين - مانيلا
</option>
    <option value="http://mofamissions.info/ab/QatarDoh
">سفارة جمهورية العراق في قطر - الدوحة
</option>
    <option value="http://mofamissions.info/ab/KSARyad
">سفارة جمهورية العراق في السعودية - الرياض
</option>
    <option value="http://mofamissions.info/ab/SyriaDa
">سفارة جمهورية العراق في سوريا - دمشق
</option>
    <option value="http://mofamissions.info/ab/TurkeyA
">سفارة جمهورية العراق في تركيا - انقرة
</option>
    <option value="http://mofamissions.info/ab/EmiDubai
">قنصلية جمهورية العراق في الأمارات - دبي
</option>
    <option value="http://mofamissions.info/ab/TurkeyGh
">قنصلية جمهورية العراق في تركيا - غازي عنتاب
</option>
    <option value="http://mofamissions.info/ab/Indiamu
">قنصلية جمهورية العراق في الهند - مومباي
</option>
    <option value="http://mofamissions.info/ab/IranAhw
">قنصلية جمهورية العراق في  ايران - الاهواز
</option>
    <option value="http://mofamissions.info/ab/IranMash
">قنصلية جمهورية العراق في  ايران - مشهد
</option>
    <option value="http://mofamissions.info/ab/TurkeyIs
">قنصلية جمهورية العراق في تركيا - اسطنبول
</option>
    <option value="http://mofamissions.info/ab/KSAJedda
">قنصلية جمهورية العراق في السعودية - جدة
</option>
    <option value="http://mofamissions.info/ab/SyriaAle
">قنصلية جمهورية العراق في سورية - حلب
</option>
    <option value="http://mofamissions.info/ab/IranKerm
">قنصلية جمهورية العراق في  ايران - كرمنشاه
</option>
  </optgroup>
  <optgroup label="استراليا">
    <option value="http://mofamissions.info/ab/AustCan
">سفارة جمهوريى العراق في استراليا - كانبرا
</option>
    <option value="http://mofamissions.info/ab/Australi
">قنصلية جمهورية العراق في أستراليا - سدني
</option>
  </optgroup>
  <optgroup label="افريقيا">
    <option value="http://mofamissions.info/ab/LibyaTr
">سفارة جمهورية العراق في ليبيا - طرابلس
</option>
    <option value="http://mofamissions.info/ab/EgyptCa
">سفارة جمهورية العراق في مصر- القاهرة
</option>
    <option value="http://mofamissions.info/ab/Algeria
">سفارة جمهورية العراق في الجزائر - الجزائر
</option>
    <option value="http://mofamissions.info/ab/Mauritan
">سفارة جمهورية العراق في مورتانيا - نواكشوط
</option>
    <option value="http://mofamissions.info/ab/SouthAfr
">سفارة جمهورية العراق في جنوب أفريقيا - بريتوريا
</option>
    <option value="http://mofamissions.info/ab/Tunisia
">سفارة جمهورية العراق في تونس - تونس
</option>
    <option value="http://mofamissions.info/ab/KenyaNa
">سفارة جمهورية العراق في كينيا - نيروبي
</option>
    <option value="http://mofamissions.info/ab/LeaguEyg
">ممثلية جمهورية العراق في الجامعة العربية - مصر
</option>
  </optgroup>
    </select>
  </div>
</section>
</div>
<div id="mag">
<a href="http://www.beladitvnews.com/ar/news/arabic-ministry-s-magazine">
<img border="0" alt="W3Schools" src="/trash/images/m.jpg">
</a>
</div>