<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/home-menu/AR/styles.css') ?>
<div id='mc'>
<ul>
  <li><a href="http://mofa.gov.iq/news/ainspector-general">مكتب المفتش العام</a></li>
  <li><a href="http://mofa.gov.iq/news/arabic-press-releases">المتحدث الرسمي</a></li>
  <li><a href="http://mofa.gov.iq/news/arforeign-service-institute">معهد الخدمة الخارجية</a></li>
</ul></div>
<div id="mag">
<a href="http://www.beladitvnews.com/ar/news/arabic-ministry-s-magazine">
<img border="0" alt="W3Schools" src="/trash/images/m.jpg">
</a>
</div>
<div id="mofamissionurl">
<section class="selectm">
  <div class="dropdown">
    <select name="one" class="dropdown-select" onchange="location = this.options[this.selectedIndex].value;">
	<optgroup label="اوروبا">
      <option value="#">البعثات العراقية في الخارج</option>
    <option value="http://mofamission.gov.iq/ab/CzechPr
">سفارة جمهورية العراق في الجيك - براغ
</option>
    <option value="http://mofamission.gov.iq/ab/AustVien
">سفارة جمهورية العراق في النمسا - فيينا 
</option>
    <option value="http://mofamission.gov.iq/ab/Belarus
">سفارة جمهورية العراق في بلاروسيا - منسك
</option>
    <option value="http://mofamission.gov.iq/ab/Belgium
">سفارة جمهورية العراق في بلجيكا - بروكسل
</option>
    <option value="http://mofamission.gov.iq/ab/Bulgaria
">سفارة جمهورية العراق في بلغاريا - صوفيا
</option>
    <option value="http://mofamission.gov.iq/ab/Denmark
">سفارة جمهورية العراق في الدنمارك - كوبنهاكن
</option>
    <option value="http://mofamission.gov.iq/ab/Finland
">سفارة جمهورية العراق في فنلندا - هلسنكي
</option>
    <option value="http://mofamission.gov.iq/ab/France
">سفارة جمهورية العراق في فرنسا - باريس
</option>
    <option value="http://mofamission.gov.iq/ab/Germany
">سفارة جمهورية العراق في المانيا - برلين
</option>
    <option value="http://mofamission.gov.iq/ab/Greece
">سفارة جمهورية العراق في اليونان - اثينا 
</option>
    <option value="http://mofamission.gov.iq/ab/Hungary
">سفارة جمهورية العراق في هنغاريا - بودابست 
</option>
    <option value="http://mofamission.gov.iq/ab/Italian
">سفارة جمهورية العراق في ايطاليا - روما
</option>
    <option value="http://mofamission.gov.iq/ab/Netherla
">سفارة جمهورية العراق في هولندا  - لاهاي
</option>
    <option value="http://mofamission.gov.iq/ab/NorwayOs
">سفارة جمهورية العراق في النرويج - اوسلو
</option>
    <option value="http://mofamission.gov.iq/ab/PolandWa
">سفارة جمهورية العراق في بولندا - وارشو
</option>
    <option value="http://mofamission.gov.iq/ab/Portugal
">سفارة جمهورية العراق في البرتغال - لشبونة</option>
    <option value="http://mofamission.gov.iq/ab/Romania
">سفارة جمهورية العراق في رومانيا - بوخارست
</option>
    <option value="http://mofamission.gov.iq/ab/RomeVati
">سفارة جمهورية العراق في ايطاليا - الفاتيكان
</option>
    <option value="http://mofamission.gov.iq/ab/SerbiaB
">سفارة جمهورية العراق في صربيا - بلغراد
</option>
    <option value="http://mofamission.gov.iq/ab/Slovakia
">سفارة جمهورية العراق في سلوفاكيا - براتسلافا
</option>
    <option value="http://mofamission.gov.iq/ab/SpainMa
">سفارة جمهورية العراق في أسبانيا - مدريد
</option>
    <option value="http://mofamission.gov.iq/ab/SwedenS
">سفارة جمهورية العراق في  السويد - ستوكهولم
</option>
    <option value="http://mofamission.gov.iq/ab/Switzerl
">سفارة جمهورية العراق في سويسرا - بيرن
</option>
    <option value="http://mofamission.gov.iq/ab/UKLondon
">سفارة جمهورية العراق في بريطانيا  - لندن
</option>
    <option value="http://mofamission.gov.iq/ab/Ukraine
">سفارة جمهورية العراق في اوكرانيا - كييف
</option>
    <option value="http://mofamission.gov.iq/ab/GerFrank
">قنصلية جمهورية العراق في المانيا - فرانكفورت
</option>
    <option value="http://mofamission.gov.iq/ab/UKManch
">قنصلية جمهورية العراق في انكلترا - مانشستر
</option>
  <option value="http://mofamission.gov.iq/UNGeneva
">ممثلية جمهورية العراق في الامم المتحدة - جنيف
</option>
    
  </optgroup>
  <optgroup label="امريكا الشمالية">
    <option value="http://mofamission.gov.iq/ab/USANewY
">ممثلية جمهورية العراق في الأمم المتحدة - نيويورك
</option>
    <option value="http://mofamission.gov.iq/ab/USADC
">سفارة جمهورية العراق في اميركا - واشنطن
</option>
    <option value="http://mofamission.gov.iq/ab/USAD
">قنصلية جمهورية العراق في اميركا - ديترويت
</option>
    <option value="http://mofamission.gov.iq/ab/CanadaMo
">قنصلية جمهورية العراق كندا - مونتريال
</option>
    <option value="http://mofamission.gov.iq/ab/CanadaOt
">سفارة جمهورية العراق في كندا - اوتاوا
</option>
    <option value="http://mofamission.gov.iq/ab/USALosAn">قنصلية جمهورية العراق في لوس انجلس
</option>
  </optgroup>
  <optgroup label="امريكا الجنوبية">
    <option value="http://mofamission.gov.iq/ab/Brazilb
">سفارة جمهورية العراق في البرازيل - برازيليا
</option>
    <option value="http://mofamission.gov.iq/ab/Buenos
">ســفارة جمهورية العراق في الارجنتين - بوينس ايرس
</option>
    <option value="http://mofamission.gov.iq/ab/ChileSan
">سفارة جمهورية العراق في تشيلي - سانتياغو
</option>
    <option value="http://mofamission.gov.iq/ab/MexicoM
">ســفارة جمهورية العراق في مكسيكو
</option>
    <option value="http://mofamission.gov.iq/ab/Venezuel
">سفارة جمهورية العراق في فنزويلا - كراكاس
</option>
  </optgroup>
  <optgroup label="آسيا">
    <option value="http://mofamission.gov.iq/ab/YemenSa
">سفارة جمهورية العراق في اليمن - صنعاء
</option>
    <option value="http://mofamission.gov.iq/ab/Afghanst
">سفارة جمهورية العراق في افغانستان - كابل
</option>
    <option value="http://mofamission.gov.iq/ab/Azerbaij
">سفارة جمهورية العراق في أذربيجان - باكو
</option>
    <option value="http://mofamission.gov.iq/ab/Bahrain
">سفارة جمهورية العراق في البحرين - المنامة
</option>
    <option value="http://mofamission.gov.iq/ab/Banglade
">سفارة جمهورية العراق في بنغلادش - دكا
</option>
    <option value="http://mofamission.gov.iq/ab/ChinaBei
">سفارة جمهورية العراق في الصين - بكين
</option>
    <option value="http://mofamission.gov.iq/ab/Emirates
">سفارة جمهرية العراق في الأمارات - أبو ظبي
</option>
    <option value="http://mofamission.gov.iq/ab/Georgia
">سفارة جمهورية العراق في جورجيا - تبليسي
</option>
    <option value="http://mofamission.gov.iq/ab/IndiaNew
">سفارة جمهورية العراق في الهند - نيودلهي
</option>
    <option value="http://mofamission.gov.iq/ab/Indonesi
">سفارة جمهورية العراق في أندونيسيا - جاكرتا
</option>
    <option value="http://mofamission.gov.iq/ab/IranTeh
">سفارة جمهورية العراق في ايران - طهران
</option>
    <option value="http://mofamission.gov.iq/ab/JordanA
">سفارة جمهورية العراق في الاردن - عمان
</option>
    <option value="http://mofamission.gov.iq/ab/Kazakhst
">سفارة جمهورية العراق في كازاخستان - استانا
</option>
    <option value="http://mofamission.gov.iq/ab/Kuwait
">سفارة جمهورية العراق في الكويت - الكويت
</option>
    <option value="http://mofamission.gov.iq/ab/Lebanese
">سفارة جمهورية العراق في لبنان - بيروت
</option>
    <option value="http://mofamission.gov.iq/ab/Malaysia
">سفارة جمهورية العراق في ماليزيا - كوالالمبور
</option>
    <option value="http://mofamission.gov.iq/ab/OmanMusc
">سفارة جمهورية العراق في سلطنة عمان - مسقط
</option>
    <option value="http://mofamission.gov.iq/ab/Pakistan
">سفارة جمهورية العراق في باكستان - اسلام اباد
</option>
    <option value="http://mofamission.gov.iq/ab/Philippi
">سفارة جمهورية العراق في الفلبين - مانيلا
</option>
    <option value="http://mofamission.gov.iq/ab/QatarDoh
">سفارة جمهورية العراق في قطر - الدوحة
</option>
    <option value="http://mofamission.gov.iq/ab/KSARyad
">سفارة جمهورية العراق في السعودية - الرياض
</option>
    <option value="http://mofamission.gov.iq/ab/SyriaDa
">سفارة جمهورية العراق في سوريا - دمشق
</option>
    <option value="http://mofamission.gov.iq/ab/TurkeyA
">سفارة جمهورية العراق في تركيا - انقرة
</option>
    <option value="http://mofamission.gov.iq/ab/EmiDubai
">قنصلية جمهورية العراق في الأمارات - دبي
</option>
    <option value="http://mofamission.gov.iq/ab/TurkeyGh
">قنصلية جمهورية العراق في تركيا - غازي عنتاب
</option>
    <option value="http://mofamission.gov.iq/ab/Indiamu
">قنصلية جمهورية العراق في الهند - مومباي
</option>
    <option value="http://mofamission.gov.iq/ab/IranAhw
">قنصلية جمهورية العراق في  ايران - الاهواز
</option>
    <option value="http://mofamission.gov.iq/ab/IranMash
">قنصلية جمهورية العراق في  ايران - مشهد
</option>
    <option value="http://mofamission.gov.iq/ab/TurkeyIs
">قنصلية جمهورية العراق في تركيا - اسطنبول
</option>
    <option value="http://mofamission.gov.iq/ab/KSAJedda
">قنصلية جمهورية العراق في السعودية - جدة
</option>
    <option value="http://mofamission.gov.iq/ab/SyriaAle
">قنصلية جمهورية العراق في سورية - حلب
</option>
    <option value="http://mofamission.gov.iq/ab/IranKerm
">قنصلية جمهورية العراق في  ايران - كرمنشاه
</option>
    <option value="http://mofamissions.info/ab/SeoulSou
">سفارة جمهورية العراق في كوريا الجنوبية - سيؤول
</option>
    <option value="http://mofamissions.info/ab/Vietnam
">سفارة جمهورية العراق في فيتنام - هانوي</option>
<option value="http://mofamissions.info/ab/armyere
">سفارة جمهورية العراق في أرمينيا - يريفان</option>
<option value="http://mofamissions.info/ab/SeoulSou
">سفارة جمهورية العراق في كوريا الجنوبية - سيؤول</option>
  </optgroup>
  <optgroup label="استراليا">
    <option value="http://mofamission.gov.iq/ab/AustCan
">سفارة جمهوريى العراق في استراليا - كانبرا
</option>
    <option value="http://mofamission.gov.iq/ab/Australi
">قنصلية جمهورية العراق في أستراليا - سدني
</option>
  </optgroup>
  <optgroup label="افريقيا">
    <option value="http://mofamission.gov.iq/ab/LibyaTr
">سفارة جمهورية العراق في ليبيا - طرابلس
</option>
    <option value="http://mofamission.gov.iq/ab/EgyptCa
">سفارة جمهورية العراق في مصر- القاهرة
</option>
    <option value="http://mofamission.gov.iq/ab/Algeria
">سفارة جمهورية العراق في الجزائر - الجزائر
</option>
    <option value="http://mofamission.gov.iq/ab/Mauritan
">سفارة جمهورية العراق في مورتانيا - نواكشوط
</option>
    <option value="http://mofamission.gov.iq/ab/SouthAfr
">سفارة جمهورية العراق في جنوب أفريقيا - بريتوريا
</option>
    <option value="http://mofamission.gov.iq/ab/Tunisia
">سفارة جمهورية العراق في تونس - تونس
</option>
    <option value="http://mofamission.gov.iq/ab/KenyaNa
">سفارة جمهورية العراق في كينيا - نيروبي
</option>
    <option value="http://mofamission.gov.iq/ab/LeaguEyg
">ممثلية جمهورية العراق في الجامعة العربية - مصر
</option>
    <option value="http://mofamissions.info/ab/Senegal
">سفارة جمهرية العراق في السنغال - داكار
</option>
    <option value="http://mofamissions.info/ab/SriLank
">سفارة جمهورية العراق في سريلانكا - كولومبو
</option>
  </optgroup>
    </select>
  </div>
</section>
</div>
<div id='mc'>
<ul>
  <li><a href="http://mofa.gov.iq/news/arabic-ministry-s-announcements">إعلانات الوزارة</a></li>
  <li><a href="http://mofa.gov.iq/news/arabic-announcements">اعلانات تجارية</a></li>
</ul>
</div>

