<?php echo $this->headTitle($this->translate('Announcements')) ?>
<h1><?php echo $this->translate('Announcements') ?></h1>

<table id="ctl00_Main_grid2" cellspacing="0" border="0" style="border-style:None;width:100%;border-collapse:collapse;">
    <tbody>
    <tr>
        <td>
            <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolor="#eeeeee" class="maintext">
                <tbody>
                <tr>

                    <td width="70%" colspan="2" bgcolor="#D7EFFD"><b><?php echo $this->translate('Tendor') ?> No.(1/15 -2014)</b></td>
                </tr>

                <tr>

                    <td width="70%" colspan="2"><b><?php echo $this->translate('Rehabilitation works of the new Iraqi consulate building in
                            Manchester city centre') ?>' </b></td>
                </tr>
                <tr>
                    <td><?php echo $this->translate('more details') ?></td>
                    <td><a href="/documents/Announcements/130355499515390243.pdf" target="_blank"><?php echo $this->translate('Download More
                            details') ?>'</a></td>
                </tr>


                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolor="#eeeeee" class="maintext">
                <tbody>
                <tr>

                    <td width="70%" colspan="2" bgcolor="#D7EFFD"><b>No.(1/2011</b></td>
                </tr>

                <tr>

                    <td width="70%" colspan="2"><b><?php echo $this->translate('Supply the Ministry Center with internet service through the Optical
                            cable') ?> </b></td>
                </tr>
                <tr>
                    <td><?php echo $this->translate('more details') ?>'</td>
                    <td><a href="/documents/Announcements/129658195220267217.pdf" target="_blank"><?php echo $this->translate('Download
                            More details') ?></a></td>
                </tr>


                </tbody>
            </table>

        </td>
    </tr>
    </tbody>
</table>