<?php echo $this->headTitle($this->translate('Iraq\'s Encyclopedia')) ?>
<h1><?php echo $this->translate('Iraq\'s Encyclopedia') ?></h1>

<ul class="list-group">
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864705844501000.pdf" target="_blank">
            <?php echo $this->translate('DAILY AVERAGE OF TEMPERATURES (CENTIGRADE) AND RELATIVE HUMIDITY FOR BAGHDAD CITY BY MONTH FOR THE YEAR 2009') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864785861705638.pdf" target="_blank">
            <?php echo $this->translate('RAINFALL, ANNUAL AVERAGE OF RELATIVE HUMIDITY AND TEMPERATURES FOR THE YEARS 1999-2009.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864794138480018.pdf" target="_blank">
            <?php echo $this->translate('POPULATION OF IRAQ FOR THE YEARS 1977 - 2011.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864787150332376.pdf" target="_blank">
            <?php echo $this->translate('AREA, YIELD AND PRODUCTION FOR CROPS AND VEGETABLES FOR THE YEAR 2010.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864796708077048.pdf" target="_blank">
            <?php echo $this->translate('No. OF HOLDINGS AND PALMS BY SEX ON NATIONAL LEVEL AND GOVERNORATES ACCORDING TO THE AGRICULTURAL CENSUSES FOR THEYEAR 2001.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864789233666958.pdf" target="_blank">
            <?php echo $this->translate('PRODUCTION OF DATES BY KINDS FOR THE YEARS 2000 -2010 (10 Ton).') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864787910664340.pdf" target="_blank">
            <?php echo $this->translate('LIVESTOCK PRODUCTS FOR THE YEARS 1999 - 2010.') ?>
        </a>
        <a href="/documents/encyclopedia/129864787910664340.pdf" target="_self"><br></a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864792778288948.pdf" target="_blank">
            <?php echo $this->translate('SUMMARY OF THE ANNUAL INDUSTRIAL STATISTIC FOR LARGE ESTABLISHMENTS (Value of production , wages &amp; benefits)FOR THE YEARS 2005 - 2009.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864808070086658.pdf"
           target="_blank"><?php echo $this->translate('NUMBER OF STUDENTS GRADUATED FROM UNIVERSITIES, TECHNICAL EDUCATION COMMISSION AND PRIVITE COLLEGES FOR THEACADEMIC YEARS 1992/1993 - 2009/2010') ?></a>.

    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864810449366316.pdf" target="_blank">
            <?php echo $this->translate('NUMBER OF STUDENTS ADMITTED IN HIGHER STUDIES BY UNIVERSITY, DEGREE, GENDER AND FOR THE ACADEMIC YEAR 2009/2010.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129865460315222029.pdf" target="_blank">
            <?php echo $this->translate('NUMBER OF HOSPITALS, PUBLIC MEDICAL CLINICS AND OTHER HEALTH INSTITUTIONS BY GOVERNORATE FOR THE YEAR2010.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864798242647582.pdf" target="_blank">
            <?php echo $this->translate('NUMBER OF COUNTRIES PARTICIPATED IN BAGHDAD INTERNATIONAL FAIR FOR TWO YEARS 2009-2010.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864776288804328.pdf" target="_blank">
            <?php echo $this->translate('Total Imports For (2009-2010).') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864778003223216.pdf" target="_blank">
            <?php echo $this->translate('TOTAL EXPORTS FOR 2009-2010Table.') ?>'
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864783297890006.pdf" target="_blank">
            <?php echo $this->translate('THE USE OF AGRICULTURAL LAND IN IRAQ, ACCORDING TO WATER BALANCE FOR THEYEAR 2009') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129865484656313419.pdf" target="_blank">
            <?php echo $this->translate('QUANTITY OF REFINED WATER PRODUCED AND CONSUMED AND PER CAPITA CONSUMPTION* FOR THE YEARS 2002-2009.') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864790501980676.pdf" target="_blank">
            <?php echo $this->translate('PRODUCTION AND EXPORT OF CRUDE OIL IN IRAQ FOR THE YEARS 1990-2010.') ?>

        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129865485435869614.pdf" target="_blank">
            <?php echo $this->translate('QUANTITY OF PRODUCED, USED AND FLARED NATURAL GAS IN IRAQ FOR THE YEARS 1989 - 2009 (millionstandard).') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129865485017418724.pdf" target="_blank">
            <?php echo $this->translate('WOMEN SHARE IN WAGE EMPLOYMENT IN THE NON- AGRICULTURAL SECTOR FOR THE YEARS(1990,2004,2006,2008).') ?>
        </a>
    </li>
    <li class="list-group-item">
        <a href="/documents/encyclopedia/129864795318197718.pdf" target="_blank">
            <?php echo $this->translate('NUMBER OF PARLIAMENT MEMBERS BY GENDER FOR THE YEARS 2004-2010.') ?>
        </a>
    </li>
</ul>