<?php echo $this->headTitle($this->translate('About Iraq')) ?>
<h1><?php echo $this->translate('About Iraq') ?></h1>

<table cellspacing="0" cellpadding="5"
       style="width: 440px; height: 1029px; border-top-color: #333333; border-left-color: #333333; border-top-width: 1px; border-left-width: 1px; border-top-style: solid; border-left-style: solid;">
    <tbody>
    <tr>
        <td align="right"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid; background-color: #999999;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">The official name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></b>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid; background-color: #999999;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Republic of Iraq</span></b></td>
    </tr>
    <tr>
        <td valign="middle"
            style="width: 100px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span><span style="font-weight: bold;">Flag</span></span></td>
        <td align="" valign="baseline"
            style="width: 500px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <p style="margin: 0px; text-align: justify;"><span style="font-weight: bold;"><a
                        href="#" target="_self"><img width="138"
                                                                                                           height="88"
                                                                                                           title="Iraq MOFA"
                                                                                                           align=""
                                                                                                           alt="Iraq MOFA"
                                                                                                           src="/img/landing/about-iraq/flag.jpg"
                                                                                                           border="0"
                                                                                                           vspace="0"
                                                                                                           hspace="0"></a></span>
            </p>

            <p style="margin: 0px; text-align: justify;"><br></p></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">Logo</span>&nbsp;<b><span lang="IT"
                                                                       style="line-height: 115%; font-family: calibri; font-size: 12pt;"></span></b>
        </td>
        <td align="left" valign="baseline"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <a href="#" target="_self"><img width="83" height="98"
                                                                                                  title="" align=""
                                                                                                  alt=""
                                                                                                  src="/img/landing/about-iraq/logo.jpg"
                                                                                                  border="0" vspace="0"
                                                                                                  hspace="0"></a></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span lang="IT" style="line-height: 115%; font-family: calibri; font-size: 12pt;">&nbsp;President</span></b>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">Fuad Masum</span></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">The Prime Minister&nbsp;</span></td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">Haider al-Abadi</span></td>
    </tr>
    <tr>
        <td align="left" valign="middle"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">National Anthem</span>&nbsp;<p style="margin: 0px; text-align: justify;">
                <br></p></td>
        <td align="left" valign="middle"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">Mawtini&nbsp;</span></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">Capital&nbsp;</span></td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <span style="font-weight: bold;">Baghdad&nbsp;</span></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Other major cities</span></b>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Mosal,&nbsp;<st1:st1:st1:st1:st1:city
                        w:st="on">Basra
                    </st1:st1:st1:st1:st1:city>,&nbsp;<st1:st1:st1:st1:st1:place w:st="on">Erbil
                    </st1:st1:st1:st1:st1:place> , Karkok, Babil.<br></span></b></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Area</span></b></td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">438317 km</span><span
                    style="line-height: 115%; font-family: arial; font-size: 12pt;">²</span></b></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <font class="Apple-style-span" face="calibri"><span class="Apple-style-span"
                                                                style="line-height: 14px;"><b><b><span
                                style="line-height: 115%; font-family: calibri; font-size: 12pt;">Geographical&nbsp;location</span></b></b></span></font>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">It’s </span><span
                    style="line-height: 115%; font-family: arial; font-size: 12pt;">located</span><span
                    style="line-height: 115%; font-family: calibri; font-size: 12pt;"> in west Asia and It’s partof middle east, Jordan and Syria are to it’s west ,Turkey&nbsp; to It’s north ,Iran to it’s ast and Kuwait and Saudi Arabia to it’s south .</span></b>
        </td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <font class="Apple-style-span" face="calibri"><span class="Apple-style-span"
                                                                style="line-height: 14px;"><b><b><span
                                style="line-height: 115%; font-family: calibri; font-size: 12pt;">Population</span></b></b></span></font>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;"><b><span
                            style="line-height: 115%; font-family: calibri; font-size: 12pt;">33330000 Based&nbsp;</span></b>&nbsp;on estimations of central of statistics with in the ministryof planning of 2011 <a
                        href="http://www.mofa.gov.iq/documentfiles/129864794138480018.pdf" target="_self">for more
                        details...</a></span></b></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Language</span></b></td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">The official languages are Arabic and Kurdish <a
                        href="http://www.mofa.gov.iq/documentfiles/129912295460517064.pdf" target="_self">see section-4
                        of Iraqi constitution</a></span></b></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <font class="Apple-style-span" face="calibri"><span class="Apple-style-span"
                                                                style="line-height: 14px;"><b><b><span
                                style="line-height: 115%; font-family: calibri; font-size: 12pt;">Topography</span></b></b></span></font>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <st1:st1:st1:st1:st1:country-region w:st="on"><b><span
                        style="line-height: 115%; font-family: calibri; font-size: 12pt;">Iraq</span></b>
            </st1:st1:st1:st1:st1:country-region>
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;"> is featured by the plains of Tigris and Euphrates, the marshes are to the south east, the mountains are in Kurdistan region at the borders with <st1:st1:st1:st1:st1:country-region
                        w:st="on">
                        <st1:st1:st1:st1:st1:place w:st="on">Iran</st1:st1:st1:st1:st1:place>
                    </st1:st1:st1:st1:st1:country-region> to the east and turkey to the north</span></b></td>
    </tr>
    <tr>
        <td align="left" valign="baseline"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <font class="Apple-style-span" face="calibri"><span class="Apple-style-span"
                                                                style="line-height: 14px;"><b><b><span
                                style="line-height: 115%; font-family: calibri; font-size: 12pt;">Climate</span></b></b></span></font>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">The western parts have typical desert climate of extreme heat in the summer and extreme cold in the winter ,while the central and southern parts have a hot summer and a moderate winter</span></b>
        </td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span
                    style="line-height: 115%; font-family: calibri; font-size: 12pt;">The Major National Resources</span></b>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <font class="Apple-style-span" size="4" face="Calibri"><span class="Apple-style-span"
                                                                         style="line-height: 18px; font-size: 16px;"><b><b><span
                                style="line-height: 115%; font-family: calibri; font-size: 12pt;">Petrol , Phosphate , Natural Gas and </span></b><span
                            style="line-height: 115%; font-family: calibri; font-size: 11pt;">&nbsp;</span><b><span
                                style="line-height: 115%; font-family: calibri; font-size: 12pt;">Sulfur &nbsp;</span></b></b></span></font>
        </td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Currency</span></b></td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;"><a
                        href="http://www.mofa.gov.iq/en/Aboutiraq/default.aspx?sm=LTsrAFNdpTY=" target="_self">Iraqi
                        Dinar</a></span></b></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <font class="Apple-style-span" size="4" face="Calibri"><span class="Apple-style-span"
                                                                         style="line-height: 18px; font-size: 16px;"><b><b><span
                                style="line-height: 115%; font-family: calibri; font-size: 12pt;">Iraq's provinces<br></span></b></b></span></font>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">&nbsp;Baghdad, Mousel,Basrah,&nbsp;Salahddin,&nbsp; Duhok,&nbsp;Erbil, Sulimania,&nbsp;Dyala,&nbsp;Wassit, Missan,&nbsp;Thiqar,&nbsp;Muthana,&nbsp;Babil,&nbsp;karbala, Najaf, Al-qadisiyyah,&nbsp;Anbar, karkuk.&nbsp; <br></span></b>
        </td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Timing</span></b></td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">GMT+3.00</span></b></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">Internet ID</span></b></td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">IQ</span></b></td>
    </tr>
    <tr>
        <td align="left"
            style="width: 140px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span
                    style="line-height: 115%; font-family: calibri; font-size: 12pt;">International phone code</span></b>
        </td>
        <td align="left"
            style="width: 300px; height: 0px; border-right-color: #333333; border-bottom-color: #333333; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
            <b><span style="line-height: 115%; font-family: calibri; font-size: 12pt;">00964</span></b></td>
    </tr>
    </tbody>
</table>