<?php echo $this->headTitle($this->translate('About Iraq')) ?>
<h1><?php echo $this->translate('About Iraq') ?></h1>

<table class="table table-consended">
    <thead>
    <tr>
        <th width="30%">
            <span><?php echo $this->translate('The official name') ?> </span>
        </th>
        <th>
            <span><?php echo $this->translate('Republic of Iraq') ?>'</span></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td valign="middle">
            <span><span><?php echo $this->translate('Flag') ?></span></span></td>
        <td align="" valign="baseline">
            <p><span><a href="#" target="_self"><img width="138" height="88" title="Iraq MOFA" align="" alt="Iraq MOFA" src="/img/landing/about-iraq/flag.jpeg" border="0" vspace="0" hspace="0"></a></span>
            </p>

            <p><br></p></td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('Logo') ?>'</span>
        </td>
        <td valign="baseline">
            <a href="#" target="_self"><img width="83" height="98" title="" align="" alt="" src="/img/landing/about-iraq/logo.jpg" border="0" vspace="0" hspace="0"></a></td>
    </tr>
    <tr>
        <td>
            <span lang="IT"><?php echo $this->translate('President') ?></span>
        </td>
        <td>
            <span><?php echo $this->translate('Fuad Masum') ?>'</span></td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('The Prime Minister') ?></span></td>
        <td>
            <span><?php echo $this->translate('Haider al-Abadi') ?>'</span></td>
    </tr>
    <tr>
        <td valign="middle">
            <span><?php echo $this->translate('National Anthem') ?></span><p>
                <br></p></td>
        <td valign="middle">
            <span><?php echo $this->translate('Mawtini') ?>'</span></td>
    </tr>
    <tr>
        <td>
            <span>Capital</span></td>
        <td>
            <span>Baghdad</span></td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('Other major cities') ?></span>
        </td>
        <td>
            <span><?php echo $this->translate('Mosal, Basra, Erbil, Karkok, Babil') ?>.</span></td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('Area<') ?>/span></td>
        <td>
            <span>438317 km</span><span>²</span></td>
    </tr>
    <tr>
        <td>
            <?php echo $this->translate('Geographicallocation') ?>
        </td>
        <td>
            <?php echo $this->translate('It\'s located in west Asia and It\'s partof middle east, Jordan and Syria are to it\'s west ,Turkey to It’s north ,Iran to it\'s ast and Kuwait and Saudi Arabia to it\'s south .') ?>
        </td>
    </tr>
    <tr>
        <td>
            <font face="calibri"><span><span><?php echo $this->translate('Population') ?></span></span></font>
        </td>
        <td>
            <?php echo $this->translate('33330000 Based on estimations of central of statistics with in the ministryof planning of 2011 <a href="/documents/about-iraq/129864794138480018.pdf" target="_self">for more details...</a>') ?></td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('Language') ?>'</span></td>
        <td>
            <span><?php echo $this->translate('The official languages are Arabic and Kurdish <a href="/documents/about-iraq/129912295460517064.pdf" target="_self">see section-4 of Iraqi constitution</a>') ?></span></td>
    </tr>
    <tr>
        <td>
            <font face="calibri"><span><span><?php echo $this->translate('Topography') ?>'</span></span></font>
        </td>
        <td>
            <?php echo $this->translate('Iraq is featured by the plains of Tigris and Euphrates, the marshes are to the south east, the mountains are in Kurdistan region at the borders with Iran to the east and turkey to the north') ?></td>
    </tr>
    <tr>
        <td valign="baseline">
            <?php echo $this->translate('Climate') ?>
        </td>
        <td>
            <span><?php echo $this->translate('The western parts have typical desert climate of extreme heat in the summer and extreme cold in the winter ,while the central and southern parts have a hot summer and a moderate winter') ?>'</span>
        </td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('The Major National Resources') ?></span>
        </td>
        <td>
            <?php echo $this->translate('Petrol , Phosphate , Natural Gas and Sulfur') ?>
        </td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('Currency') ?>'</span></td>
        <td>
            <span><?php echo $this->translate('Iraqi Dinar') ?></span></td>
    </tr>
    <tr>
        <td>
            <?php echo $this->translate('Iraq\'s provinces') ?>
        </td>
        <td>
            <span><?php echo $this->translate('Baghdad, Mousel, Basrah, Salahddin, Duhok, Erbil, Sulimania, Dyala, Wassit, Missan, Thiqar, Muthana, Babil, karbala, Najaf, Al-qadisiyyah,Anbar, karkuk. ') ?>'<br></span>
        </td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('Timing') ?></span></td>
        <td>
            <span>GMT+3.00</span></td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('Internet ID') ?>'</span></td>
        <td>
            <span>IQ</span></td>
    </tr>
    <tr>
        <td>
            <span><?php echo $this->translate('International phone code') ?></span>
        </td>
        <td>
            <span>00964</span></td>
    </tr>
    </tbody>
</table>