<?php echo $this->headTitle($this->translate('Investment')) ?>
<div class="sidebar col-md-4">
    <?php echo $this->partial('sidebar', ['routes' => $this->routes]) ?>
</div>
<div class="col-md-8">
<h1><?php echo $this->translate('Investment') ?></h1>

<div class="list-group">
    <a class="list-group-item" href="/documents/investment/InvestmentOverview.pdf">
        <?php echo $this->translate('Investment Overview') ?>
    </a>
    <a class="list-group-item" href="/documents/investment/InvestorGuide.pdf">
        <?php echo $this->translate('Investor Guide') ?>
    </a>
    <a class="list-group-item" href="/documents/investment/NICProjectsDec09v4.pdf">
        <?php echo $this->translate('NIC Projects Dec 09 v4') ?>
    </a>
</div>
</div>