<?php $this->headTitle($this->translate('The Virtual Museum of Iraq')) ?>
<div class="sidebar col-md-4">
    <?php echo $this->partial('sidebar', ['routes' => $this->routes]) ?>
</div>
<div class="col-md-8">
<h1><?php echo $this->translate('The Virtual Museum of Iraq') ?></h1>
<table>
<tbody>
<tr>
    <td valign="top">

        <table border="0" cellspacing="0" cellpadding="0">

            <tr>
                <td colspan="2" valign="top">

                    <p style="margin: 0px; text-align: center;"><span style="font-weight: bold;"><?php echo $this->translate('Visiting the Virtual Museum of Iraq') ?></span>
                    </p>

                    <p style="margin: 0px; text-align: left;"><br><?php echo $this->translate('The National museum of Iraq is one of the important
                        institutions in the world that established in 1932 in Alawi-al hilla baghdad,Iraq.') ?></p>

                    <p style="margin: 0px; text-align: left;"><br></p>

                    <p style="margin: 0px; text-align: left;"><br><?php echo $this->translate('The Virtual Museum contains eight halls, set up in
                        chronological order of Historical and cultural Eras like Assyrian, Sumerian, and Islamic era
                        which contains different collections of Islamic Art.') ?></p>

                    <p style="margin: 0px; text-align: left;"><br><br><a
                            href="http://www.virtualmuseumiraq.cnr.it/homeENG.htm" target="_blank"><?php echo $this->translate('Visit the virtual
                            Museum of Iraq...') ?></a></p>

                    <p style="margin: 0px; text-align: left;"><br><br><br><br></p>

                    <p style="margin: 0px; text-align: left;"><br><br><br><br></p>

                    <p></p><br>
                </td>
            </tr>


            </tbody>
        </table>

    </td>
</tr>
</tbody></table>
</div>