<?php echo $this->doctype(); ?>

<html lang="<?php echo Locale::getPrimaryLanguage(Locale::getDefault())?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Ministry of Foreign Affairs | Republic of Iraq'))->setSeparator(' | ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        //->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.css')
        ->prependStylesheet($this->basePath() . '/css/site.min.css')
        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/layout/right-sidebar.js')
        ->prependFile($this->basePath() . '/js/landing/main.js')
        //->prependFile('https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.js')
        ->prependFile($this->basePath() . '/js/plugin/newsTicker/jquery.newsTicker.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

    <?php if ($this->locale == 'ar_IQ') : ?>
        <!--
        <link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/master/dist/cdnjs/3.3.1-rc2/css/bootstrap-rtl.min.css">
        -->
        <link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/bootstrap-rtl.min.css">
        <link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/rtl.css">
    <?php endif; ?>

</head>
<?php
$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch();
if ($routeMatch) {
    $routeName = $routeMatch->getMatchedRouteName();
    $modules = explode('/', $routeName);
}
?>
<body class="<?php echo isset($modules) ? join(' ', $modules) : '' ?>">
<div class="container">
    <?php echo $this->partial('layout/header') ?>

    <!-- Main content -->
    <div id="main-wrapper">
        <div class="col-md-3">
            <?php echo $this->partial('left-sidebar') ?>
        </div>
        <div class="col-md-6" id="main-content">
            <?php echo $this->content; ?>
        </div>
        <script>
            var latestNewsUrl = '<?php echo $this->url('latest-news') ?>';
            var readMoreText = '<?php echo $this->translate('Read more') ?>';
        </script>
        <div id="right-sidebar" class="col-md-3">
            <?php echo $this->partial('right-sidebar') ?>
        </div>
    </div>
</div> <!-- /container -->

<footer>
    <?php echo $this->partial('layout/footer') ?>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
