<!DOCTYPE html>
<html class="html" lang="ar">
<head>

    <script type="text/javascript">
        if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["jquery-1.8.3.min.js", "museutils.js", "jquery.musemenu.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "jquery.watch.js", "index.css"], "outOfDate":[]};
    </script>

    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
    <meta name="generator" content="2014.2.1.284"/>
    <link rel="shortcut icon" href="/trash/images/favicon.ico?393988555"/>
    <title>جمهورية العراق :: وزارة الخارجية :: الصفحة الرئيسة</title>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/trash/css/site_global.css?455398302"/>
    <link rel="stylesheet" type="text/css" href="/trash/css/master_a-master.css?4245347644"/>
    <link rel="stylesheet" type="text/css" href="/trash/css/index.css?276340188" id="pagesheet"/>
    <!-- Other scripts -->
    <script type="text/javascript">
        document.documentElement.className += ' js';
        var __adobewebfontsappname__ = "muse";
    </script>
    <!-- JS includes -->
    <script type="text/javascript">
        document.write('\x3Cscript src="/trash/' + (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//webfonts.creativecloud.com/droid-serif:n7:all;droid-sans:n7:all;carme:n4:all;actor:n4:all;cabin:n5:all.js" type="text/javascript">\x3C/script>');
    </script>
    <!--[if lt IE 9]>
    <script src="/trash/scripts/html5shiv.js?4241844378" type="text/javascript"></script>
    <![endif]-->
    <!--/*

*/
-->
</head>
<body>

<div class="clearfix" id="page"><!-- column -->
<div class="position_content" id="page_position_content">
<div class="clearfix colelem" id="pu1573"><!-- group -->
    <div class="clip_frame grpelem" id="u1573"><!-- image -->
        <img class="block" id="u1573_img" src="/trash/images/3.jpg" alt="" width="333" height="123"/>
    </div>
    <div class="clip_frame grpelem" id="u1583"><!-- image -->
        <img class="block" id="u1583_img" src="/trash/images/en_logo.jpg" alt="" width="105" height="122"/>
    </div>
    <nav class="MenuBar clearfix grpelem" id="menuu1323"><!-- horizontal box -->
        <div class="MenuItemContainer clearfix grpelem" id="u1331"><!-- vertical box -->
            <div class="MenuItem MenuItemWithSubMenu clearfix colelem" id="u1332"><!-- horizontal box -->
                <div class="MenuItemLabel NoWrap clearfix grpelem" id="u1333-4"><!-- content -->
                    <p>عربي</p>
                </div>
            </div>
        </div>
    </nav>
    <div class="clearfix grpelem" id="u1589-7"><!-- content -->
        <p id="u1589-2">Republic of Iraq</p>
        <p id="u1589-4">Ministry of Foreign Affairs</p>
        <p>&nbsp;</p>
    </div>
    <div class="PamphletWidget clearfix grpelem" id="pamphletu1946"><!-- none box -->
        <div class="popup_anchor" id="u1947popup">
            <div class="ContainerGroup clearfix" id="u1947"><!-- none box -->
                <div class="Container invi shadow rounded-corners clearfix grpelem" id="u1948"><!-- column -->
                    <div class="position_content" id="u1948_position_content">
                        <div class="clip_frame colelem" id="u1985"><!-- image -->
                            <img class="block" id="u1985_img" src="/trash/images/investment.jpg" alt="" width="132" height="126"/>
                        </div>
                        <div class="clearfix colelem" id="u1992-9"><!-- content -->
                            <p id="u1992-2">Dear Investor,</p>
                            <p id="u1992-4">The investment opportunities found in today’s Iraq vary in type, size, scope,sector, purpose, and structure. Potential investors will find an openlandscape to develop projects that will fill the needs of Iraq’s expanding and demanding population. Iraq’s location at the center of many historic andcurrent middle&#45;east trade routes provides an undeniable advantage;combined with a variety of natural resources and a desire for advanced quality of life, this advantage creates many opportunities for builders,suppliers, transporters, developers, producers, providers, manufacturers,servicers, and financiers, all of whom will find many avenues by which to</p>
                            <p id="u1992-6">establish new relationships, build new operations, create new markets, and develop new mutually beneficial business connections.</p>
                            <p id="u1992-7">&nbsp;</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ThumbGroup clearfix grpelem" id="u1963"><!-- none box -->
            <div class="popup_anchor">
                <a class="nonblock nontext Thumb popup_element rounded-corners" id="u1965" href="/trash/assets/investmentoverview.pdf"><!-- simple frame --></a>
            </div>
        </div>
    </div>
</div>
<nav class="MenuBar clearfix colelem" id="menuu813"><!-- horizontal box -->
    <div class="MenuItemContainer clearfix grpelem" id="u863"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu MuseMenuActive clearfix colelem" id="u864" href="/trash/index.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u867-4"><!-- content --><p>Home</p></div></a>
    </div>
    <div class="MenuItemContainer clearfix grpelem" id="u856"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix colelem" id="u857" href="/trash/the-ministry.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u859-4"><!-- content --><p>The Ministry</p></div><div class="grpelem" id="u860"><!-- image --></div></a>
        <div class="SubMenu  MenuLevel1 clearfix" id="u861"><!-- vertical box -->
            <ul class="SubMenuView clearfix colelem" id="u862"><!-- vertical box -->
                <li class="MenuItemContainer clearfix colelem" id="u969"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u970" href="/trash/faq-s.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u972-4"><!-- content --><p>FAQ's</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u979"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u980" href="/trash/ministry-departments.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u983-4"><!-- content --><p>Ministry Departments</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u986"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u989" href="/trash/the-minister.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u990-4"><!-- content --><p>The Minister</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u993"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u996" href="/trash/speeches---interviews.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u998-4"><!-- content --><p>Speeches &amp; Interviews</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u1000"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u1003" href="/trash/udersecretaries.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u1005-4"><!-- content --><p>Udersecretaries</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u1007"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u1008" href="/trash/ministry-s-announcements.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u1011-4"><!-- content --><p>Ministry's Announcements</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u1021"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u1024" href="/trash/ministry-s-magazine.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u1026-4"><!-- content --><p>Ministry's Magazine</p></div></a></li>
            </ul>
        </div>
    </div>
    <div class="MenuItemContainer clearfix grpelem" id="u821"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix colelem" id="u824" href="/trash/about-iraq.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u827-4"><!-- content --><p>About Iraq</p></div><div class="grpelem" id="u825"><!-- image --></div></a>
        <div class="SubMenu  MenuLevel1 clearfix" id="u822"><!-- vertical box -->
            <ul class="SubMenuView Style-1 clearfix colelem" id="u823"><!-- vertical box -->
                <li class="MenuItemContainer clearfix colelem" id="u871"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u872" href="/trash/investment-in-iraq.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u874-4"><!-- content --><p>Investment in Iraq</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u883"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u886" href="/trash/iraq-s-constitution.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u889-4"><!-- content --><p>Iraq's Constitution</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u890"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u891" href="/trash/iraq-encyclopedia.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u892-4"><!-- content --><p>Iraq Encyclopedia</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u897"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u898" href="/trash/announcements.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u900-4"><!-- content --><p>Announcements</p></div></a></li>
            </ul>
        </div>
    </div>
    <div class="MenuItemContainer clearfix grpelem" id="u849"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix colelem" id="u850" href="/trash/news.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u851-4"><!-- content --><p>News</p></div></a>
    </div>
    <div class="MenuItemContainer clearfix grpelem" id="u842"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix colelem" id="u845" href="/trash/foreign-policy.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u848-4"><!-- content --><p>Foreign Policy</p></div><div class="grpelem" id="u847"><!-- image --></div></a>
        <div class="SubMenu  MenuLevel1 clearfix" id="u843"><!-- vertical box -->
            <ul class="SubMenuView menu gradient clearfix colelem" id="u844"><!-- vertical box -->
                <li class="MenuItemContainer clearfix colelem" id="u955"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u956" href="/trash/press-releases.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u959-4"><!-- content --><p>Press Releases</p></div></a></li>
                <li class="MenuItemContainer clearfix colelem" id="u931"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u932" href="/trash/international-organizations.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u934-4"><!-- content --><p>International organizations</p></div></a></li>
            </ul>
        </div>
    </div>
    <div class="MenuItemContainer clearfix grpelem" id="u828"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix colelem" id="u831" href="/trash/diplomatic-missions.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u833-4"><!-- content --><p>Diplomatic Missions</p></div><div class="grpelem" id="u832"><!-- image --></div></a>
        <div class="SubMenu  MenuLevel1 clearfix" id="u829"><!-- vertical box -->
            <ul class="SubMenuView menu gradient clearfix colelem" id="u830"><!-- vertical box -->
                <li class="MenuItemContainer clearfix colelem" id="u911"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u912" href="/trash/iraqi-ambassadors.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u914-4"><!-- content --><p>Iraqi Ambassadors</p></div></a></li>
            </ul>
        </div>
    </div>
    <div class="MenuItemContainer clearfix grpelem" id="u835"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix colelem" id="u836" href="/trash/consular-services.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u838-4"><!-- content --><p>Consular Services</p></div><div class="grpelem" id="u837"><!-- image --></div></a>
        <div class="SubMenu  MenuLevel1 clearfix" id="u840"><!-- vertical box -->
            <ul class="SubMenuView Style-3 clearfix colelem" id="u841"><!-- vertical box -->
                <li class="MenuItemContainer clearfix colelem" id="u921"><!-- horizontal box --><a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix grpelem" id="u922" href="/trash/other-links.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u924-4"><!-- content --><p>Other Links</p></div></a></li>
            </ul>
        </div>
    </div>
    <div class="MenuItemContainer clearfix grpelem" id="u814"><!-- vertical box -->
        <a class="nonblock nontext MenuItem MenuItemWithSubMenu clearfix colelem" id="u815" href="/trash/contact-us.html"><!-- horizontal box --><div class="MenuItemLabel NoWrap clearfix grpelem" id="u817-4"><!-- content --><p>Contact us</p></div></a>
    </div>
</nav>
<div class="menu gradient colelem" id="u550"><!-- simple frame --></div>
<div class="clearfix colelem" id="pu1113"><!-- group -->
    <div class="clearfix grpelem" id="u1113"><!-- group -->
        <div class="clearfix grpelem" id="u1115"><!-- group -->
            <div class="clearfix grpelem" id="u1116-4"><!-- content -->
                <p>News</p>
            </div>
        </div>
    </div>
    <div class="clearfix grpelem" id="u1484-4"><!-- content -->
        <p>Foreign Minister Receives his Italian Counterpart</p>
    </div>
</div>
<div class="clearfix colelem" id="u1117-4"><!-- content -->
    <p>Main News</p>
</div>
<div class="colelem" id="u1120"><!-- simple frame --></div>
<div class="clearfix colelem" id="pu1190"><!-- group -->
    <div class="clip_frame grpelem" id="u1190" data-mu-ie-matrix="progid:DXImageTransform.Microsoft.Matrix(M11=-1,M12=0,M21=0,M22=-1,SizingMethod='auto expand')" data-mu-ie-matrix-dx="0" data-mu-ie-matrix-dy="0"><!-- image -->
        <img class="block" id="u1190_img" src="/trash/images/1419757222_basics-06-128.png" alt="" width="40" height="54"/>
    </div>
    <div class="clearfix grpelem" id="u1199-4"><!-- content -->
        <p>Other News</p>
    </div>
    <div class="grpelem" id="u1462"><!-- simple frame --></div>
    <div class="clearfix grpelem" id="u1908-12"><!-- content -->
        <p id="u1908-2">Foreign Minister Receives US</p>
        <p id="u1908-4">Senator</p>
        <p id="u1908-5">&nbsp;</p>
        <p id="u1908-6">&nbsp;</p>
        <p id="u1908-8">Dr. Ibrahim al&#45;Jaafari, the Iraqi Foreign Minister, received in his office in Baghdad late Wednesday, 12.24.2014, the head of the Iranian Shura Council, Ali Larijani, and his accompanying delegation</p>
        <p id="u1908-9">&nbsp;</p>
        <p id="u1908-10">&nbsp;</p>
    </div>
    <div class="clip_frame grpelem" id="u1909"><!-- image -->
        <img class="block" id="u1909_img" src="/trash/images/130624171941559967.jpg" alt="" width="339" height="226"/>
    </div>
    <div class="grpelem" id="u1460"><!-- simple frame --></div>
    <div class="clearfix grpelem" id="pu1159"><!-- column -->
        <div class="clip_frame colelem" id="u1159"><!-- image -->
            <img class="block" id="u1159_img" src="/trash/images/130621488965494661.jpg" alt="" width="278" height="184"/>
        </div>
        <div class="clearfix colelem" id="u1158-5"><!-- content -->
            <p id="u1158-3"><span id="u1158">Foreign Minister Meets French Defense Minister </span><span id="u1158-2">Read more</span></p>
        </div>
        <div class="clearfix colelem" id="u1194-4"><!-- content -->
            <p>Consular Services</p>
        </div>
    </div>
    <div class="grpelem" id="u1463"><!-- simple frame --></div>
    <div class="clip_frame grpelem" id="u1181"><!-- image -->
        <img class="block" id="u1181_img" src="/trash/images/1419757222_basics-06-128.png" alt="" width="40" height="54"/>
    </div>
    <div class="clearfix grpelem" id="u1914-5"><!-- content -->
        <p id="u1914-2">30/12/2014</p>
        <p id="u1914-3">&nbsp;</p>
    </div>
    <div class="clearfix grpelem" id="u1933-4"><!-- content -->
        <p>Read more</p>
    </div>
</div>
<div class="colelem" id="u1198"><!-- simple frame --></div>
<div class="colelem" id="u1195"><!-- simple frame --></div>
<div class="clearfix colelem" id="pppu531"><!-- group -->
    <div class="clearfix grpelem" id="ppu531"><!-- column -->
        <div class="clearfix colelem" id="pu531"><!-- group -->
            <div class="grpelem" id="u531"><!-- simple frame --></div>
            <div class="clip_frame grpelem" id="u1200"><!-- image -->
                <img class="block" id="u1200_img" src="/trash/images/1.jpg" alt="" width="177" height="118"/>
            </div>
            <div class="clip_frame grpelem" id="u1211"><!-- image -->
                <img class="block" id="u1211_img" src="/trash/images/32.jpg" alt="" width="176" height="117"/>
            </div>
            <div class="clip_frame grpelem" id="u1218"><!-- image -->
                <img class="block" id="u1218_img" src="/trash/images/22.jpg" alt="" width="179" height="119"/>
            </div>
        </div>
        <div class="clearfix colelem" id="pu1230-4"><!-- group -->
            <div class="clearfix grpelem" id="u1230-4"><!-- content -->
                <p>&nbsp;Preparatory Meeting for the Coming PM Visit to Turkey</p>
            </div>
            <div class="clearfix grpelem" id="u1231-4"><!-- content -->
                <p>Undersecretary Concludes Visit to Romania</p>
            </div>
            <div class="clearfix grpelem" id="u1229-4"><!-- content -->
                <p>Undersecretary Meets Chairman of the Parliamentary Committee</p>
            </div>
        </div>
        <div class="clearfix colelem" id="ppu1941-4"><!-- group -->
            <div class="clearfix grpelem" id="pu1941-4"><!-- group -->
                <div class="clearfix grpelem" id="u1941-4"><!-- content -->
                    <p>Read more</p>
                </div>
                <div class="clearfix grpelem" id="u1940-4"><!-- content -->
                    <p>28/12/2014</p>
                </div>
            </div>
            <div class="clearfix grpelem" id="u1930-4"><!-- content -->
                <p>Read more</p>
            </div>
            <div class="clearfix grpelem" id="u1935-4"><!-- content -->
                <p>Read more</p>
            </div>
            <div class="clearfix grpelem" id="u1938-4"><!-- content -->
                <p>28/12/2014</p>
            </div>
            <div class="clearfix grpelem" id="u1943-4"><!-- content -->
                <p>28/12/2014</p>
            </div>
        </div>
    </div>
    <div class="clearfix grpelem" id="ppu532"><!-- column -->
        <div class="clearfix colelem" id="pu532"><!-- group -->
            <div class="grpelem" id="u532"><!-- simple frame --></div>
            <div class="clip_frame grpelem" id="u1206"><!-- image -->
                <img class="block" id="u1206_img" src="/trash/images/2.jpg" alt="" width="175" height="117"/>
            </div>
        </div>
        <div class="clearfix colelem" id="u1227-5"><!-- content -->
            <p id="u1227-2">Undersecretary Meets the Romanian Ambassador</p>
            <p id="u1227-3">&nbsp;</p>
        </div>
        <div class="clearfix colelem" id="pu1936-4"><!-- group -->
            <div class="clearfix grpelem" id="u1936-4"><!-- content -->
                <p>Read more</p>
            </div>
            <div class="clearfix grpelem" id="u1944-4"><!-- content -->
                <p>28/12/2014</p>
            </div>
        </div>
    </div>
    <div class="clearfix grpelem" id="ppu1874"><!-- column -->
        <div class="clearfix colelem" id="pu1874"><!-- group -->
            <div class="clip_frame grpelem" id="u1874"><!-- image -->
                <img class="block" id="u1874_img" src="/trash/images/aboutiq.jpg" alt="" width="112" height="101"/>
            </div>
            <div class="clearfix grpelem" id="u1899-4"><!-- content -->
                <p>Investment in IRAQ</p>
            </div>
        </div>
        <div class="clearfix colelem" id="pu1885"><!-- group -->
            <div class="clip_frame grpelem" id="u1885"><!-- image -->
                <img class="block" id="u1885_img" src="/trash/images/departments.jpg" alt="" width="112" height="101"/>
            </div>
            <div class="clearfix grpelem" id="u1905-4"><!-- content -->
                <p>Ministry Departments</p>
            </div>
        </div>
    </div>
    <div class="clearfix grpelem" id="ppu1880"><!-- column -->
        <div class="clearfix colelem" id="pu1880"><!-- group -->
            <div class="clip_frame grpelem" id="u1880"><!-- image -->
                <img class="block" id="u1880_img" src="/trash/images/connection.jpg" alt="" width="112" height="101"/>
            </div>
            <div class="clearfix grpelem" id="u1904-4"><!-- content -->
                <p>Links</p>
            </div>
        </div>
        <div class="clearfix colelem" id="pu1890"><!-- group -->
            <div class="clip_frame grpelem" id="u1890"><!-- image -->
                <img class="block" id="u1890_img" src="/trash/images/question.jpg" alt="" width="112" height="101"/>
            </div>
            <div class="clearfix grpelem" id="u1907-4"><!-- content -->
                <p>FAQ</p>
            </div>
        </div>
    </div>
</div>
<div class="clearfix colelem" id="pu533"><!-- group -->
    <div class="browser_width grpelem" id="u533-bw">
        <div class="gradient" id="u533"><!-- simple frame --></div>
    </div>
    <div class="clearfix grpelem" id="u519-4"><!-- content -->
        <p>Language</p>
    </div>
    <div class="clearfix grpelem" id="u522-4"><!-- content -->
        <p>Links</p>
    </div>
    <div class="clearfix grpelem" id="u525-4"><!-- content -->
        <p>Site Map</p>
    </div>
    <div class="grpelem" id="u526"><!-- simple frame --></div>
    <div class="grpelem" id="u1226"><!-- simple frame --></div>
    <div class="grpelem" id="u1928"><!-- simple frame --></div>
    <div class="clearfix grpelem" id="u541-7"><!-- content -->
        <p id="u541-2">English</p>
        <p id="u541-4">عربي</p>
        <p id="u541-5">&nbsp;</p>
    </div>
    <div class="clearfix grpelem" id="u547-16"><!-- content -->
        <p>Home</p>
        <p>The Ministry</p>
        <p>Minister</p>
        <p>Udersecretaries</p>
        <p>Foreign Policy</p>
        <p>Minister Speeches</p>
        <p>ConsularServices</p>
    </div>
    <div class="clearfix grpelem" id="u1922-16"><!-- content -->
        <p>Iraq's Constitution</p>
        <p>Speeches</p>
        <p>Investment in Iraq</p>
        <p>Iraq Encyclopedia</p>
        <p>International Conventions</p>
        <p>Ministry's Announcements</p>
        <p>MOFA Ministers</p>
    </div>
    <div class="clearfix grpelem" id="u1926-10"><!-- content -->
        <p>Ministry's Magazine</p>
        <p>International Conventions</p>
        <p>Security Council Resolutions</p>
        <p>International organizations</p>
    </div>
    <div class="clearfix grpelem" id="u1929-7"><!-- content -->
        <p id="u1929-2">Republic of Iraq</p>
        <p id="u1929-4">Ministry of Foreign Affairs</p>
        <p id="u1929-5">&nbsp;</p>
    </div>
    <div class="clip_frame grpelem" id="u1916"><!-- image -->
        <img class="block" id="u1916_img" src="/trash/images/logo.png" alt="" width="100" height="125"/>
    </div>
</div>
</div>
</div>
<!--[if lt IE 9]>
<div class="preload_images">
    <img class="preload" src="/trash/images/u830-r-grad.png" alt=""/>
</div>
<![endif]-->
<!-- JS includes -->
<script type="text/javascript">
    if (document.location.protocol != 'https:') document.write('\x3Cscript src="/trash/http://musecdn2.businesscatalyst.com/scripts/4.0/jquery-1.8.3.min.js" type="text/javascript">\x3C/script>');
</script>
<script type="text/javascript">
    window.jQuery || document.write('\x3Cscript src="/trash/scripts/jquery-1.8.3.min.js" type="text/javascript">\x3C/script>');
</script>
<script src="/trash/scripts/museutils.js?3777594392" type="text/javascript"></script>
<script src="/trash/scripts/jquery.musemenu.js?415733523" type="text/javascript"></script>
<script src="/trash/scripts/webpro.js?474087315" type="text/javascript"></script>
<script src="/trash/scripts/musewpslideshow.js?274584885" type="text/javascript"></script>
<script src="/trash/scripts/jquery.museoverlay.js?170414611" type="text/javascript"></script>
<script src="/trash/scripts/touchswipe.js?100683906" type="text/javascript"></script>
<script src="/trash/scripts/jquery.watch.js?4144919381" type="text/javascript"></script>
<!-- Other scripts -->
<script type="text/javascript">
    $(document).ready(function() { try {
        (function(){var a={},b=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),16);return 0};(function(){$('link[type="text/css"]').each(function(){var b=($(this).attr("href")||"").match(/\/?css\/([\w\-]+\.css)\?(\d+)/);b&&b[1]&&b[2]&&(a[b[1]]=b[2])})})();(function(){$("body").append('<div class="version" style="display:none; width:1px; height:1px;"></div>');
            for(var c=$(".version"),d=0;d<Muse.assets.required.length;){var f=Muse.assets.required[d],g=f.match(/([\w\-\.]+)\.(\w+)$/),k=g&&g[1]?g[1]:null,g=g&&g[2]?g[2]:null;switch(g.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");c.addClass(k);var g=b(c.css("color")),h=b(c.css("background-color"));g!=0||h!=0?(Muse.assets.required.splice(d,1),"undefined"!=typeof a[f]&&(g!=a[f]>>>24||h!=(a[f]&16777215))&&Muse.assets.outOfDate.push(f)):d++;c.removeClass(k);break;case "js":k.match(/^jquery-[\d\.]+/gi)&&
                typeof $!="undefined"?Muse.assets.required.splice(d,1):d++;break;default:throw Error("Unsupported file type: "+g);}}c.remove();if(Muse.assets.outOfDate.length||Muse.assets.required.length)c="Some files on the server may be missing or incorrect. Clear browser cache and try again. If the problem persists please contact website author.",(d=location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi))&&Muse.assets.outOfDate.length&&(c+="\nOut of date: "+Muse.assets.outOfDate.join(",")),d&&Muse.assets.required.length&&(c+="\nMissing: "+Muse.assets.required.join(",")),alert(c)})()})();
        /* body */
        Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
        Muse.Utils.prepHyperlinks(true);/* body */
        Muse.Utils.initWidget('.MenuBar', function(elem) { return $(elem).museMenu(); });/* unifiedNavBar */
        Muse.Utils.initWidget('#pamphletu1946', function(elem) { new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'loose',event:'mouseover',deactivationEvent:'mouseout_trigger',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false}); });/* #pamphletu1946 */
        Muse.Utils.resizeHeight()/* resize height */
        Muse.Utils.showWidgetsWhenReady();/* body */
        Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
    } catch(e) { if (e && 'function' == typeof e.notify) e.notify(); else Muse.Assert.fail('Error calling selector function:' + e); }});
</script>
</body>
</html>
