<?php echo $this->doctype(); ?>

<html lang="<?php echo Locale::getPrimaryLanguage(Locale::getDefault())?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Ministry of Foreign Affairs | Republic of Iraq'))->setSeparator(' | ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        //->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.css')
        ->prependStylesheet($this->basePath() . '/css/site.min.css')
        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/landing/main.js')
        //->prependFile('https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.js')
        ->prependFile($this->basePath() . '/js/plugin/newsTicker/jquery.newsTicker.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

    <?php if ($this->locale == 'ar_IQ') : ?>
        <!--
        <link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/master/dist/cdnjs/3.3.1-rc2/css/bootstrap-rtl.min.css">
        -->
        <link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/bootstrap-rtl.min.css">
        <link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/rtl.css">
    <?php endif; ?>

</head>
<?php
$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch();
if ($routeMatch) {
    $routeName = $routeMatch->getMatchedRouteName();
    $modules = explode('/', $routeName);
}
?>
<body class="<?php echo isset($modules) ? join(' ', $modules) : '' ?>">
<div class="container">
    <header class="clearfix">
        <div class="logo pull-left flip">
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('/trash/images/en_logo.jpg') ?>" alt="Republic of Iraq"/>&nbsp;
            </a>
        </div>
        <div class="head-logo pull-left flip">
            <?php echo $this->translate('Republic of Iraq') ?><br />
            <?php echo $this->translate('Ministry of Foreign Affairs') ?>
        </div>
        <div id="language-switcher">
            <div class="dropdown">
                <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?php echo $this->translate('Language') ?>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li>
                        <a href="/" title="<?php echo $this->translate('English') ?>"><?php echo $this->translate('English') ?></a>
                        <a href="/ar/" title="<?php echo $this->translate('Arabic') ?>"><?php echo $this->translate('Arabic') ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <nav id="top-nav" class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <?php echo $this->partial('layout/navigation') ?>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div id="news-ticker" class="clearfix">
        <div class="title pull-left flip">
            <?php echo $this->translate('News') ?>
        </div>
        <div class="news-ticker-content pull-left flip">
            <script>
                var newsTickerUrl = '<?php echo $this->url('news-ticker') ?>';
            </script>
            <ul class="news-ticker">
                <li>
                    <?php echo $this->translate('No news.') ?>
                </li>
            </ul>
        </div>
    </div>

    <!-- Main content -->
    <div id="main-content">
        <?php echo $this->content; ?>
    </div>
</div> <!-- /container -->

<footer>
    <?php echo $this->partial('layout/footer') ?>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
