<?php echo $this->doctype(); ?>

<html lang="<?php echo Locale::getPrimaryLanguage(Locale::getDefault())?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Ministry of Foreign Affairs | Republic of Iraq'))->setSeparator(' | ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/site.min.css', ['media' => 'print']) ?>

    <?php if ($this->locale == 'ar_IQ') : ?>
        <!--
        <link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/master/dist/cdnjs/3.3.1-rc2/css/bootstrap-rtl.min.css">
        -->
        <link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/bootstrap-rtl.min.css">
        <link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/rtl.css">
    <?php endif; ?>
    <style>
        img {max-width: 100%;}
    </style>
</head>
<?php
$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch();
if ($routeMatch) {
    $routeName = $routeMatch->getMatchedRouteName();
    $modules = explode('/', $routeName);
}
?>
<body class="<?php echo isset($modules) ? join(' ', $modules) : '' ?>">
<div class="container2">
    <header class="clearfix">
        <div class="logo pull-left flip">
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('/trash/images/en_logo.jpg') ?>" alt="Republic of Iraq"/>&nbsp;
            </a>
        </div>
        <div class="head-logo pull-left flip">
            <?php if ($this->locale == 'en_US'): ?>
                <?php echo $this->translate('Republic of Iraq') ?><br />
                <?php echo $this->translate('Ministry of Foreign Affairs') ?>
            <?php else : ?>
                <img src="<?php echo $this->basePath() ?>/trash/images/logo_ar.jpg" alt="" />
            <?php endif; ?>
        </div>
    </header>

    <!-- Main content -->
    <div id="main-content">
        <?php echo $this->content; ?>
    </div>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
