<?php $this->headTitle($this->translate('Categories Manager')) ?>
<h1><?php echo $this->translate('Categories Manager') ?></h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Locale</th>
            <th>Moderators</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
        </tr>
    </tbody>
</table>