<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/home-menu/EN/styles.css') ?>
<div id='cssmenu'>
<ul>
   <li class='has-sub'><a href='http://104.236.81.79/the-ministry/the-minister'>The Minister</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/about-iraq/constitution'>Iraq's Constitution</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/about-iraq/encyclopedia'>Iraq Encyclopedia</a></li>
   <li class='active has-sub'><a href='http://104.236.81.79/foreign-policy/human-rights'>Human Rights</a>
   <li class='has-sub'><a href='#'>International Conventions</a>
      <ul>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/un_charter.pdf'>The UN Charter</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinen.pdf'>The First Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinen.pdf'>The Second Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinenc.pdf'>The Third Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinen.pdf'>The Fourth Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinenc.pdf'>Consular Relations</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/foreign-policy/security-council-resolutions'>Security Council Resolutions</a></li></ul>
   <li class='has-sub'><a href='http://104.236.81.79/foreign-policy/the-new-iraq	'>The New Iraq</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/foreign-policy/international-organizations'>International Organizations</a></li>
</ul>
</div>
<section class="selectm">
  <div class="dropdown">
<select name="forma" onchange="location = this.options[this.selectedIndex].value;">
  <optgroup label="Europe">
    <option value="#">Iraqi Missions Abroad</option>
    <option value="http://mofamissions.info/en/CzechPr
">Iraqi Embassy to Czech-Prague</option>
    <option value="http://mofamissions.info/en/AustVien
">Iraqi Embassy to Austria-Vienna</option>
    <option value="http://mofamissions.info/en/Belarus
">Iraqi Embassy to Belarus-Minsk</option>
    <option value="http://mofamissions.info/en/Belgium
">Iraqi Embassy to Belgium-Bruxelles</option>
    <option value="http://mofamissions.info/en/Bulgaria
">Iraqi Embassy to Bulgaria-Sofia</option>
    <option value="http://mofamissions.info/en/Denmark
">Iraqi Embassy to Denmark-Copenhagen</option>
    <option value="http://mofamissions.info/en/Finland
">Iraqi Embassy to Finland-Helsinki</option>
    <option value="http://mofamissions.info/en/France
">Iraqi Embassy to France-Paris</option>
    <option value="http://mofamissions.info/en/Germany
">Iraqi Embassy to Germany-Berlin</option>
    <option value="http://mofamissions.info/en/Greece
">Iraqi Embassy to Greece-Athena</option>
    <option value="http://mofamissions.info/en/Hungary
">Iraqi Embassy to Hungary-Budapest</option>
    <option value="http://mofamissions.info/en/Italian
">Iraqi Embassy to Italian-Rome</option>
    <option value="http://mofamissions.info/en/Netherla
">Iraqi Embassy to Netherlands-Lahai</option>
    <option value="http://mofamissions.info/en/NorwayOs
">Iraqi Embassy to Norway-Oslo</option>
    <option value="http://mofamissions.info/en/PolandWa
">Iraqi Embassy to Poland-Warsaw</option>
    <option value="http://mofamissions.info/en/Portugal
">Iraqi Embassy to Portugal - Lisbon</option>
    <option value="http://mofamissions.info/en/Romania
">Iraqi Embassy to Romania-Bucharest</option>
    <option value="http://mofamissions.info/en/RomeVati
">Iraqi Embassy to Rome-Vatican</option>
    <option value="http://mofamissions.info/en/SerbiaB
">Iraqi Embassy to Serbia-Belgrade</option>
    <option value="http://mofamissions.info/en/Slovakia
">Iraqi Embassy to Slovakia-Brateslava</option>
    <option value="http://mofamissions.info/en/SpainMa
">Iraqi Embassy to Spain-Madrid</option>
    <option value="http://mofamissions.info/en/SwedenS
">Iraqi Embassy to Sweden-Stockholm</option>
    <option value="http://mofamissions.info/en/Switzerl
">Iraqi Embassy to Switzerland - Bern</option>
    <option value="http://mofamissions.info/en/UKLondon
">Iraqi Embassy to UK - London</option>
    <option value="http://mofamissions.info/en/Ukraine
">Iraqi Embassy to Ukraine-Kiev</option>
    <option value="http://mofamissions.info/en/GerFrank
">Iraqi Consulate to Germany-Frankfurt</option>
    <option value="http://mofamissions.info/en/UKManch
">Iraqi Consulate to Manchester-UK</option>
<option value="http://mofamissions.info/en/UNGeneva
">Representation of the Republic of Iraq to Geneva
</option>
    
  </optgroup>
  <optgroup label="North America">
    <option value="http://mofamissions.info/en/USANewY
">Representation of The Republic of Iraq to New York</option>
    <option value="http://mofamissions.info/en/USADC
">Iraqi Embassy in Washington</option>
    <option value="http://mofamissions.info/ab/USADC
">Consulate of Republic of Iraq to Detroit</option>
    <option value="http://mofamissions.info/en/CanadaMo
">Iraqi Consulate to Canada-Montreal</option>
    <option value="http://mofamissions.info/en/CanadaOt
">Iraqi Consulate to Canada-Ottawa</option>
    <option value="http://mofamissions.info/en/USALosAn">Iraqi Consulate to Los-Angeles</option>
  </optgroup>
  <optgroup label="South America">
    <option value="http://mofamissions.info/en/Brazilb
">Iraqi Embassy to Brazil-Brasilia</option>
    <option value="http://mofamissions.info/en/Buenos
">Iraqi Embassy to Buenos Aires</option>
    <option value="http://mofamissions.info/en/ChileSan
">Iraqi Embassy to Chile-Santiago</option>
    <option value="http://mofamissions.info/en/MexicoM
">Iraqi Embassy to Mexico</option>
    <option value="http://mofamissions.info/en/Venezuel
">Iraqi Embassy in Venezuela-Caracas</option>
  </optgroup>
  <optgroup label="Asia">
    <option value="http://mofamissions.info/en/YemenSa
">Iraqi Embassy in Yemen-Sanaa</option>
    <option value="http://mofamissions.info/en/Afghanst
">Iraqi Embassy to Afghanstan-Kabul</option>
    <option value="http://mofamissions.info/en/Azerbaij
">Iraqi Embassy to Azerbaijan-Baku</option>
    <option value="http://mofamissions.info/en/Bahrain
">Iraqi Embassy to Bahrain-Manama</option>
    <option value="http://mofamissions.info/en/Banglade
">Iraqi Embassy to Bangladesh-Dhaka</option>
    <option value="http://mofamissions.info/en/ChinaBei
">Iraqi Embassy to China-Beijing</option>
    <option value="http://mofamissions.info/en/Emirates
">Iraqi Embassy to Emirates-AbuDhabi</option>
    <option value="http://mofamissions.info/en/Georgia
">Iraqi Embassy to Georgia-Tbilisi</option>
    <option value="http://mofamissions.info/en/IndiaNew
">Iraqi Embassy to India-New Delhi</option>
    <option value="http://mofamissions.info/en/Indonesi
">Iraqi Embassy to Indonesia-Jakarta</option>
    <option value="http://mofamissions.info/en/IranTeh
">Iraqi Embassy to Iran-Tehran</option>
    <option value="http://mofamissions.info/en/JordanA
">Iraqi Embassy to Jordan-Amman</option>
    <option value="http://mofamissions.info/en/Kazakhst
">Iraqi Embassy to Kazakhstan-Astana</option>
    <option value="http://mofamissions.info/en/Kuwait
">Iraqi Embassy to Kuwait</option>
    <option value="http://mofamissions.info/en/Lebanese
">Iraqi Embassy to Lebanese-Beirut</option>
    <option value="http://mofamissions.info/en/Malaysia
">Iraqi Embassy to Malaysia-Kuala Lumpur</option>
    <option value="http://mofamissions.info/en/OmanMusc
">Iraqi Embassy to Oman-Muscat</option>
    <option value="http://mofamissions.info/en/Pakistan
">Iraqi Embassy to Pakistan-Islamabad</option>
    <option value="http://mofamissions.info/en/Philippi
">Iraqi Embassy to Philippines-Manila</option>
    <option value="http://mofamissions.info/en/QatarDoh
">Iraqi Embassy to Qatar-Doha</option>
    <option value="http://mofamissions.info/en/KSARyad
">Iraqi Embassy to Saudi Arabia-Al Ryadh</option>
    <option value="http://mofamissions.info/en/SyriaDa
">Iraqi Embassy to Syria-Damascus</option>
    <option value="http://mofamissions.info/en/TurkeyA
">Iraqi Embassy to Turkey-Ankara</option>
    <option value="http://mofamissions.info/en/EmiDubai
">Iraqi Consulate to Emirates-Dubai</option>
    <option value="http://mofamissions.info/en/TurkeyGh
">Iraqi Consulate to Ghaziantep-Turkey</option>
    <option value="http://mofamissions.info/en/Indiamu
">Iraqi Consulate to India-mumbai</option>
    <option value="http://mofamissions.info/en/IranAhw
">Iraqi Consulate to Iran-Ahwaz</option>
    <option value="http://mofamissions.info/en/IranMash
">Iraqi Consulate to Iran-Mashad</option>
    <option value="http://mofamissions.info/en/TurkeyIs
">Iraqi Consulate to Istanbul</option>
    <option value="http://mofamissions.info/en/KSAJedda
">Iraqi Consulate to Saudi Arabia-Jeddah</option>
    <option value="http://mofamissions.info/en/SyriaAle
">Iraqi Consulate to Syrian-Aleppo</option>
    <option value="http://mofamissions.info/en/IranKerm
">Consulate to Iran-Kermanshah</option>
  </optgroup>
  <optgroup label="Australia">
    <option value="http://mofamissions.info/en/AustCan
">Iraqi Embassy to Australia-Canberra</option>
    <option value="http://mofamissions.info/en/Australi
">Iraqi Consulate to Australia-Sydney</option>
  </optgroup>
  <optgroup label="Africa">
    <option value="http://mofamissions.info/en/LibyaTr
">Iraqi Embassy to Tripli-Libya</option>
    <option value="http://mofamissions.info/en/EgyptCa
">Iraqi Embassy to Egypt-Cairo</option>
    <option value="http://mofamissions.info/en/Algeria
">Iraqi Embassy to Algeria-Alger</option>
    <option value="http://mofamissions.info/en/Mauritan
">Iraqi Embassy to Mauritania-Nouakshott</option>
    <option value="http://mofamissions.info/en/SouthAfr
">Iraqi Embassy to South Africa-Pretoria</option>
    <option value="http://mofamissions.info/en/Tunisia
">Iraqi Embassy to Tunisia-Tunis</option>
    <option value="http://mofamissions.info/en/KenyaNa
">Iraqi Embassy to Kenya-Nairobi</option>
    <option value="http://mofamissions.info/en/LeaguEyg
">Permanent Mission of The Republic of Iraq to the League Of Arab States</option>
  </optgroup>
</select>
<div id="mag">
<a href="http://www.beladitvnews.com/ar/news/arabic-ministry-s-magazine">
<img border="0" alt="W3Schools" src="/trash/images/m.jpg">
</a>
</div>
