<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/home-menu/EN/styles.css') ?>
<div id='cssmenu'>
<ul>
   <li class='has-sub'><a href='http://104.236.81.79/the-ministry/the-minister'>The Minister</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/about-iraq/constitution'>Iraq's Constitution</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/about-iraq/encyclopedia'>Iraq Encyclopedia</a></li>
   <li class='active has-sub'><a href='http://104.236.81.79/foreign-policy/human-rights'>Human Rights</a>
   <li class='has-sub'><a href='#'>International Conventions</a>
      <ul>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/un_charter.pdf'>The UN Charter</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinen.pdf'>The First Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinen.pdf'>The Second Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinenc.pdf'>The Third Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinen.pdf'>The Fourth Geneva Convention</a>
   <li class='has-sub'><a href='http://104.236.81.79/documentfiles/vinenc.pdf'>Consular Relations</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/foreign-policy/security-council-resolutions'>Security Council Resolutions</a></li></ul>
   <li class='has-sub'><a href='http://104.236.81.79/foreign-policy/the-new-iraq	'>The New Iraq</a></li>
   <li class='has-sub'><a href='http://104.236.81.79/foreign-policy/international-organizations'>International Organizations</a></li>
</ul>
</div>
