<?php
$this->headScript()
    ->prependFile($this->basePath('js/landing/blog-view.js'))
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.js')
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js')
;
$this->headLink()
    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.css')
    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css')
;
?>
<?php
/** @var \Blog\Entity\Blog $blog */
$blog = $this->blog;
$cats = $blog->getCategories();

/**
 * Set meta data
 */
$this->headTitle($blog->getTitle());
if ($blog->getMetaDescription()) {
    $this->headMeta()->setName('description', $blog->getMetaDescription());
}
if ($blog->getMetaKeywords()) {
    $this->headMeta()->appendName('keywords', $blog->getMetaKeywords());
}
?>
<h1><?php echo $this->blog->getTitle() ?></h1>

<div class="blog-author">
    <i class="glyphicon glyphicon-calendar"></i>
    <?php echo $blog->getExactCreateTime() ?>
    |
    <i class="glyphicon glyphicon-user"></i>
    <?php echo sprintf($this->translate('Written by %s'), $blog->getCreateUser()->getDisplayName()) ?>
</div>
<div class="button">
    <a style="font-size: 20px; color: #444;" href="?print=1" title="<?php echo $this->translate('Print') ?>">
        <i class="glyphicon glyphicon-print"></i>
    </a>
</div>
<hr />
<div class="article-photo text-center">
    <img src="<?php echo $blog->getPhotoUrl() ?>" alt="<?php echo $blog->getTitle() ?>" title="<?php echo $blog->getTitle() ?>" />
</div>
<div class="blog-content">
    <?php echo $blog->getContent(); ?>
</div>
<hr />