<?php
/** @var \Blog\Entity\Category $category */
$category = $this->category;
$this->headTitle($this->translate($category->getName()))
?>
<h1 class="text-center"><?php echo $category->getName() ?></h1>
<hr />

<?php foreach ($this->paginator as $blog) : ?>
    <?php echo $this->partial('article_partial', ['blog' => $blog]) ?>
<?php endforeach; ?>

<?php
// add at the end of the file after the table
echo $this->paginationControl(
// the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Blog'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'blog/view',
        'link' => $category->getUrl()
    )
);
?>