<?php
/** @var \Mission\Entity\Blog $blog */
$blog = $this->blog;
$cats = $blog->getCategories();

/**
 * Set meta data
 */
$this->headTitle($blog->getTitle());
if ($blog->getMetaDescription()) {
    $this->headMeta()->setName('description', $blog->getMetaDescription());
}
if ($blog->getMetaKeywords()) {
    $this->headMeta()->appendName('keywords', $blog->getMetaKeywords());
}
?>
<h1><?php echo $this->blog->getTitle() ?></h1>

<div class="blog-author">
    <i class="glyphicon glyphicon-calendar"></i>
    <?php echo $blog->getExactCreateTime() ?>
    |
    <i class="glyphicon glyphicon-user"></i>
    <?php echo sprintf($this->translate('Written by %s'), $blog->getCreateUser()->getDisplayName()) ?>
</div>
<hr />
<div class="article-photo text-center">
    <img src="<?php echo $blog->getPhotoUrl() ?>" alt="" />
</div>
<div class="blog-content">
    <?php echo $blog->getContent(); ?>
</div>
<hr />