<?php $this->headTitle($this->translate('Ministry\'s Announcements')) ?>
<h1><?php echo $this->translate('Ministry\'s Announcements') ?></h1>
<table id="ctl00_Main_grid2" cellspacing="0" border="0" style="border-style:None;width:100%;border-collapse:collapse;">
    <tbody>
    <tr>
        <td>
            <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolor="#eeeeee" class="maintext">
                <tbody>
                <tr>

                    <td width="70%" colspan="2" bgcolor="#D7EFFD"><b>0</b></td>
                </tr>

                <tr>

                    <td width="70%" colspan="2"><b><?php echo $this->translate('Ministry of Foreign Affairs Receives Health Insurance Offers') ?> </b>
                    </td>
                </tr>
                <!--
                  <tr>
                    <td  width="30%">Start Date</td>
                    <td width="70%">03/06/2014</td>
                  </tr>
                  <tr>
                    <td >Close Date</td>
                    <td>03/06/2014</td>
                  </tr>
                  -->
                <tr>
                    <td><?php echo $this->translate('more details') ?>'</td>
                    <td><a href="/documents/Announcements/130462695647405952.pdf" target="_blank">D<?php echo $this->translate('ownload More
                            details') ?></a></td>
                </tr>


                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolor="#eeeeee" class="maintext">
                <tbody>
                <tr>

                    <td width="70%" colspan="2" bgcolor="#D7EFFD"><b><?php echo $this->translate('Announcement') ?> </b></td>
                </tr>

                <tr>

                    <td width="70%" colspan="2"><b><?php echo $this->translate('information about the property or documents belonging to the State of
                            Kuwait to contact our ministry in order to return them to Kuwait... ') ?></b></td>
                </tr>
                <!--
                  <tr>
                    <td  width="30%">Start Date</td>
                    <td width="70%">27/10/2013</td>
                  </tr>
                  <tr>
                    <td >Close Date</td>
                    <td>27/10/2013</td>
                  </tr>
                  -->
                <tr>
                    <td><?php echo $this->translate('more details') ?></td>
                    <td><a href="/documents/Announcements/130273455312130758.pdf" target="_blank"><?php echo $this->translate('Download More
                            details') ?></a></td>
                </tr>


                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolor="#eeeeee" class="maintext">
                <tbody>
                <tr>

                    <td width="70%" colspan="2" bgcolor="#D7EFFD"><b>0</b></td>
                </tr>

                <tr>

                    <td width="70%" colspan="2"><b><?php echo $this->translate('Announcement on Missing People during the War in Kuwait and their
                            Whereabouts') ?> </b></td>
                </tr>
                <!--
                  <tr>
                    <td  width="30%">Start Date</td>
                    <td width="70%">27/10/2013</td>
                  </tr>
                  <tr>
                    <td >Close Date</td>
                    <td>27/10/2013</td>
                  </tr>
                  -->
                <tr>
                    <td><?php echo $this->translate('more details') ?>'</td>
                    <td><a href="/documents/Announcements/130273318724102944.pdf" target="_blank"><?php echo $this->translate('Download More
                            details') ?></a></td>
                </tr>


                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolor="#eeeeee" class="maintext">
                <tbody>
                <tr>

                    <td width="70%" colspan="2" bgcolor="#D7EFFD"><b><?php echo $this->translate('Promotions for health insurance<') ?>'/b></td>
                </tr>

                <tr>

                    <td width="70%" colspan="2"><b><?php echo $this->translate('Promotions for health insurance programs for mofa employee in
                            missions and consulates') ?> </b></td>
                </tr>
                <!--
                  <tr>
                    <td  width="30%">Start Date</td>
                    <td width="70%">23/05/2013</td>
                  </tr>
                  <tr>
                    <td >Close Date</td>
                    <td>23/05/2013</td>
                  </tr>
                  -->
                <tr>
                    <td><?php echo $this->translate('more details') ?>'</td>
                    <td><a href="/documents/Announcements/130137701616443316.pdf" target="_blank"><?php echo $this->translate('Download More
                            details') ?></a></td>
                </tr>


                </tbody>
            </table>

        </td>
    </tr>
    </tbody>
</table>