<?php $this->headTitle($this->translate('Ministry\'s Magazine')) ?>
<div class="sidebar col-md-4">
    <?php echo $this->partial('sidebar', ['routes' => $this->routes]) ?>
</div>
<div class="col-md-8">
<h1><?php echo $this->translate('Ministry\'s Magazine') ?></h1>
<table class="table">
    <tbody>
    <tr>
        <td colspan="2" valign="top" class="maintext">

            <p></p>

            <p style="text-align: center; margin: 0px"><img title="" border="0" hspace="0" alt=""
                                                            src="/img/landing/ministry-magazine/1.jpg">
            </p>

            <p style="text-align: right; margin: 0px"><br></p>

            <p style="text-align: center; margin: 0px"><span style="font-weight: bold"><?php echo $this->translate('Quartely Magazine means in Foreign Affairs Service inside and outside Iraq...') ?>&nbsp;</span>
            </p>

            <p style="text-align: justify; margin: 0px"><span style="font-weight: bold"></span>&nbsp;</p>
            <table align="center" cellspacing="5" cellpadding="5"
                   style="height: 1160px; border-top-color: ; border-left-color: ">
                <tbody>
                <tr>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid; width: 150px; background-color: #cccccc">
                        <p style="text-align: center; margin: 0px"><span style="font-weight: bold">&nbsp;<?php echo $this->translate('Sada Al-Kharidiya') ?></span>
                        </p></td>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid; background-color: #cccccc">
                        &nbsp;<strong><?php echo $this->translate('Read in this issue...') ?>'</strong></td>
                </tr>
                <tr>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        <p style="text-align: center; margin: 0px">&nbsp;<img title="" border="0" hspace="0" alt=""
                                                                              src="/img/landing/ministry-magazine/2.jpg"
                                                                              width="131" height="164"
                                                                              style="height: 164px; width: 131px"></p>
                    </td>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid; width: 0px">
                        <p style="text-align: justify; margin: 0px">&nbsp;<?php echo $this->translate('Baghdad Summit is a political and diplomatic
                            success for Iraq.') ?></p>

                        <p style="text-align: justify; margin: 0px"><br></p>

                        <p style="text-align: justify; margin: 0px"><?php echo $this->translate('Iraq and the United Nations Organizations in
                            Rome.') ?>'</p></td>
                </tr>
                <tr>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        <p style="text-align: center; margin: 0px">&nbsp;<img title="" border="0" hspace="0" alt=""
                                                                              src="/img/landing/ministry-magazine/3.jpg"
                                                                              width="137" height="165"
                                                                              style="height: 165px; width: 137px"></p>
                    </td>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        &nbsp;<?php echo $this->translate('The Third Iraqi Ambassadors Conference:<br>&nbsp; Serious revision of what has been
                        achieved... and a new start to the future.<br><br>Italian Ambassador to Baghdad:<br>&nbsp; Iraq
                        would be the richest country in the Arab World over the next ten years.') ?>&nbsp; </td>
                </tr>
                <tr>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        <p style="text-align: center; margin: 0px">&nbsp;<img title="" border="0" hspace="0" alt=""
                                                                              src="/img/landing/ministry-magazine/4.jpg"
                                                                              width="136" height="167"
                                                                              style="height: 167px; width: 136px"></p>
                    </td>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        &nbsp;<?php echo $this->translate('Security Council adopted three Iraqi historic resolutions managed to get out of the
                        provisions of Charter (7)<br><br>Ministry reconstrution... a struggle story between life makers
                        and darkness bats<br><br>48 ambassadors engaged their representatives to Iraq around the globe') ?>'
                    </td>
                </tr>
                <tr>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        <p style="text-align: center; margin: 0px">&nbsp;<img title="" border="0" hspace="0" alt=""
                                                                              src="/img/landing/ministry-magazine/5.jpg"
                                                                              width="133" height="162"
                                                                              style="height: 162px; width: 133px"></p>
                    </td>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        &nbsp;<?php echo $this->translate('Secretary-General of the United Nations calling the neighboring countries to respect
                        Iraq\'s sovereignty') ?>'
                    </td>
                </tr>
                <tr>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        <p style="text-align: center; margin: 0px">&nbsp;<img title="" border="0" hspace="0" alt=""
                                                                              src="/img/landing/ministry-magazine/6.jpg"
                                                                              width="129" height="155"
                                                                              style="height: 155px; width: 129px"></p>
                    </td>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        &nbsp;<?php echo $this->translate('Facts relating to the exit of Iraq from 7th charter<br><br>Reconstruction operations
                        defeat terror<br><br>Arab openness to Baghdad through Egyptians') ?>
                    </td>
                </tr>
                <tr>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        <p style="text-align: center; margin: 0px">&nbsp;<img title="" border="0" hspace="0" alt=""
                                                                              src="/img/landing/ministry-magazine/7.jpg"
                                                                              width="132" height="161"
                                                                              style="height: 161px; width: 132px"></p>
                    </td>
                    <td style="border-top: #000000 1px solid; border-right: #000000 1px solid; border-bottom: #000000 1px solid; border-left: #000000 1px solid">
                        <?php echo $this->translate('The Ministry continues the recontruction for its ambassies abroad<br><br>Iraqi parliament
                        approves designation of 57 new ambassador') ?>'
                    </td>
                </tr>
                </tbody>
            </table>
            <p></p><br>
        </td>
    </tr>
    </tbody>
</table>
</div>