<?php $this->headTitle($this->translate('Mofa Ministers')) ?>
<h1><?php echo $this->translate('Mofa Ministers') ?></h1>
<table id="ctl00_Main_grid2" cellspacing="0" cellpadding="2" border="0" style="border-collapse:collapse;">
    <tbody>
    <tr>
        <td>
            <table width="100%" bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/130602513592514529.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Dr. Ibrahim al-Jaafari') ?></b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Iraqi Foreign Ministry 2014') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325589406210299.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Hoshyar Zebari') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister 2003 to 2014') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129327298404049847.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Naji Sabri') ?></b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister') ?>
                        from 2001
                        to 2003
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325617138909023.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Mohammed Saeed AL-Sahaf') ?></b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 1992
                        to 2000') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325605988766303.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Tariq Aziz') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister from 24/1/1983
                        to 22/3/1991') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325606710650543.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Saadoun Hammadi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister from 11/11/1974
                        to 24/1/1983') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325607505660719.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Shathel taka') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister from24/6/1974 to 20/10/1974') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325608045198875.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Murtadha Saeed') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister from 31/10/1971
                        to 23/6/1974') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325634769915947.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abdul Karim Sheikhli') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister from31/7/1968
                        to 29/9/1971') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325635520081799.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Ismail Kher Allah') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister from 11/7/1967
                        to16/7/1968') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325636903693259.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Nasir AL-Hani') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 18/7/1968
                        to 30/7/1968') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325637574014339.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Adnan AL- Bachachi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 18/4/1966
                        to 10/7/1967') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325638455900627.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abd AL-Rahman al-Bazzaz') ?></b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 6/9/1965
                        to 9/8/1966') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325639001688863.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Naji Talib') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 14/11/1964
                        to 6/9/1965') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325640254986155.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Subhi Abdul Hamed') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 18/11/1963
                        to 14/11/1964') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325640719679603.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Taleb Shibib') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 8/2/1963
                        to 17/11/1963') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325641250467647.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Hashim Jwad') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 7/2/1959
                        to 7/2/1963') ?> <br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325641896569667.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abdul Jabbar AL-Jumarad') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister originality
                        from 14/7/1958
                        to 7/2/1959') ?> <br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326413085949527.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Burhan Alden Aaian') ?></b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister

                        The first of 7/5/1955

                        to 20/6/1957

                        And the last of 16/12/1957

                        to 3/3/1958') ?>

                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326413503767375.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abdullah Baker') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 17/9/1953
                        to 8/3/1954') ?> <br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326413908303803.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Shaker AL-Wadi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister from 18/8/1949
                        to 4/11/1949
                        And the last of 15/7/1951
                        to 9/7/1952') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326414506748963.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Muzahim AL- Bachachi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister The first of 26/6/1948
                        to 6/10/1948
                        And the last 10/12/1949
                        5/2/1950') ?>

                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326415046443371.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Mohammed Fadhel AL Jamali') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 1/6/1946
                        to 27/1/1948
                        And the last 2/3/1958
                        to 19/5/1958') ?>

                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326415604263011.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Ali MumtazAL-Daftry') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 21/5/1946
                        to30/5/1946
                        And the last 20/6/1957
                        to 13/12/1957') ?>

                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326416380835451.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Hamdi AL- Bachachi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 26/8/1945
                        to 22/2/1946
                        And the last 29/1/1948
                        to 27/3/1948') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326416929592475.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Arshad AL- Omari') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 3/6/1944
                        to 25/8/1945') ?>


                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326417703039875.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Mahmud Subhi AL-Daftry') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 25/12/1943
                        to 3/6/1944') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326418076169651.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Tahsin AL-Askri') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 27/9/1943
                        to 25/12/1943') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326419426499435.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Nasra AL- Farisi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 23/6/1943
                        to 27/9/1943
                        And the last 28/3/1948
                        to 26/6/1948') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326420242916135.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abdullah Hafudh') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 8/10/1942
                        to 23/6/1943
                        And the last 6/1/1949
                        to 17/3/1949') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326420731516139.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Taha AL- Hashimi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 1/2/1941
                        to 4/2/1941') ?><br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326421812154971.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Musa AL- Shabnder') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 29/1/1941
                        to 1/2/1941
                        And the last 3/9/1954
                        ot 7/5/1955') ?><br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326424027183323.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Ali Jawdat AL- Ayubi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 25/4/1939
                        to 22/2/1940
                        And the last 20/6/1957
                        to 15/12/1957') ?><br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326424505001939.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Naji AL- Asil') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 29/10/1936
                        to 17/8/1937
                        The first of 25/4/1939
                        to 22/2/1940
                        And the last 20/6/1957
                        to 15/12/1957') ?><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326425043602583.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abdul Qader Rashed') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 3/11/1932
                        to 18/3/1933') ?><br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326428163798771.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abdullah AL- Damalugi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 18/10/1930
                        to 19/10/1931
                        And the last 9/2/1942
                        to 31/5/1942') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129325489755716039.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Nori AL- Saiid') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 23/3/1930
                        to 18/10/1930
                        And the last 5/2/1950
                        to 15/7/1950') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326433701213399.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Naji AL- Swedi') ?></b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 18/11/1929
                        to 13/3/1930
                        And the last 15/1/1941
                        to 25/1/1941') ?><br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326434288095911.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Taufiq AL- Swedi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 21/4/1929
                        to 23/3/ 1931
                        And the last 19/5/1958
                        to 14/7/1958') ?><br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326434627631507.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Jaffar AL- Askri') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        The first of 21/11/1926
                        to 18/1/1928
                        And the last 19/10/1931
                        to 3/10/1932') ?><br><br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    <tr>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326435092481207.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Abdul Mhsen AL- Sadoon') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 24/11/1924
                        to 26/6/1925') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
        <td>
            <table bgcolor="#eeeeee" cellpadding="0" cellspacing="0" height="200">
                <tbody>
                <tr>
                    <td align="center" valign="top" height="112">
                        <img src="/img/static/129326435400297647.jpg" border="0">

                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="20">

                        <b><?php echo $this->translate('Yasin AL- Hashimi') ?>
                        </b><br>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" height="68">


                        <?php echo $this->translate('Foreign Minister
                        from 24/11/1924
                        to 26/6/1925') ?>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    </tbody>
</table>
