<?php echo $this->headTitle($this->translate('The Minister')) ?>
<div class="sidebar col-md-4">
    <?php echo $this->partial('sidebar', ['routes' => $this->routes]) ?>
</div>
<div class="col-md-8">
<h1><?php echo $this->translate('The Minister') ?></h1>
<table>
    <tr>
        <td colspan="2" valign="top" class="maintext">

            <p></p>

            <p style="margin: 0px; text-align: center;"><img
                    src="/img/landing/the-ministry.jpg" alt="" border="3" align=""
                    vspace="0" hspace="0" title="" width="177" height="104"><br><br><br></p>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Name: Dr. Ibrahim al-Jaafari') ?></p>
            <ul>
                <li><p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Iraqi Foreign Ministry.') ?></p></li>
                <li><p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Former Iraqi Prime Minister.') ?></p></li>
            </ul>
            <table role="table" class="table table-consended" cellpadding="3" cellspacing="2">
                <thead>
                <tr height="30">
                    <th width="60" valign="middle" colspan="1"><?php echo $this->translate('Date') ?></td>
                    <th align="center"><?php echo $this->translate('Curriculum Vitae') ?></td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1947</td>
                    <td><?php echo $this->translate('Ibrahim &nbsp;Al Ashaiqer, surnamed (Jaafari), Foreign Minister,born in the holy city of
                        Karbala.') ?><br></td>
                </tr>
                <tr>
                    <td>1966</td>
                    <td><?php echo $this->translate('Joined the Islamic Dawa Party.') ?> <br></td>
                </tr>
                <tr>
                    <td>1966</td>
                    <td><?php echo $this->translate('Got the highest secondary school grade at Mosul City that enabled him to join the Faculty of
                        Medicine, University of Mosul.') ?><br></td>
                </tr>
                <tr>
                    <td>1974</td>
                    <td><?php echo $this->translate('Mr. Jaafari got married, with two sons and three daughters.') ?> <br></td>
                </tr>
                <tr>
                    <td>1980</td>
                    <td><?php echo $this->translate('February, Left Iraq with his family, heading to Syria, and from there to Iran until 1990. ') ?><br>
                    </td>
                </tr>
                <tr>
                    <td>1980</td>
                    <td><?php echo $this->translate('He was elected a member of the Islamic Dawa Party.') ?> <br></td>
                </tr>
                <tr>
                    <td>1982</td>
                    <td><?php echo $this->translate('Participated in founding the Islamic Supreme Council, and be in charge of the Executive Office
                        and the Executive Committee.') ?><br></td>
                </tr>
                <tr>
                    <td>1990</td>
                    <td><?php echo $this->translate('Resided at London until 2003.') ?> <br></td>
                </tr>
                <tr>
                    <td>1991</td>
                    <td><?php echo $this->translate('Participated in the formation and leadership of (The Joint Action Committee of the Iraqi
                        Opposition).') ?><br></td>
                </tr>
                <tr>
                    <td>1991</td>
                    <td><?php echo $this->translate('Participated in the Iraqi political conferences, such as the (Beirut Conference).') ?><br></td>
                </tr>
                <tr>
                    <td>1992</td>
                    <td><?php echo $this->translate('Participated in the formation and leadership of the (United National Congress).') ?><br></td>
                </tr>
                <tr>
                    <td>1996</td>
                    <td><?php echo $this->translate('Elected officially as a Spokesman for the Islamic Dawa Party.') ?> <br></td>
                </tr>
                <tr>
                    <td>2002</td>
                    <td><?php echo $this->translate('Called to form the (Coalition of the Iraqi National Powers) which includes 17 political forces,
                        along with 33 Iraqi figures representing the (Plenary Session).') ?><br></td>
                </tr>
                <tr>
                    <td>2003</td>
                    <td><?php echo $this->translate('2003 After the fall of Saddam\'s regime, in August 2003, Dr. Jaafari became the first president
                        of the Governing Council. The most prominent achievements were: forming a 25 members committee
                        to prepare the draft new Iraqi constitution. He set up basis for the political relations of the
                        new Iraq and visited seven Arab countries in seven days, in addition to his visit to the League
                        of Arabic States in Cairo, where he delivered a distinctive speech. He formed the first Iraqi
                        government in the new testament.') ?><br></td>
                </tr>
                <tr>
                    <td>2004</td>
                    <td><?php echo $this->translate('Dr. Ibrahim Al Jaafari occupied the Vice-President post of the Republic of Iraq. He contributed
                        effectively to enhance compatibility and smooth flow in government work between the presidency
                        and the cabinet. He found in his work as Vice-President a chance to enhance general Iraq\'s
                        relations and Iraqi - Arab relations in particular.') ?><br></td>
                </tr>
                <tr>
                    <td>2005</td>
                    <td><?php echo $this->translate('occupied the Prime Minister post, as the first elected Prime Minister of Iraq, following the
                        general elections which the Iraqi people participated in heavily January 30, 2005. He managed to
                        achieve significant achievements during the transitional government time, by starting the wide
                        development projects; to promote collapsed infrastructure, overcome the heavy legacy of the
                        previous regime, in addition to the creation of the preparation and approval requirements of the
                        (permanent constitution) of Iraq, and the successful election the permanent (House of
                        Representatives) in under successful security, as well as paying great attention to the media,
                        poets, artists, writers and athletes. He also laid the foundations of the rule of law and
                        contributed to the consolidation of the foundations of the new Iraqi state.') ?><br></td>
                </tr>
                <tr>
                    <td>2006</td>
                    <td><?php echo $this->translate('2006 Jaafari became a member of the House of Representatives for two terms; 2006 until 2010, and
                        2010 until 2014, in addition to the presidency of the National Alliance.') ?><br></td>
                </tr>
                <tr>
                    <td>2008</td>
                    <td><?php echo $this->translate('2008 He announced the establishment of the National Reform Trend on May 31, 2008 and
                        participated in the first provincial elections on January 2009.') ?><br></td>
                </tr>
                <tr>
                    <td>2010</td>
                    <td><?php echo $this->translate('2010 He was elected as President of the Iraqi National Alliance, played a pivotal role in the
                        convergence of views and solving political differences, and the formation of the Iraqi
                        government.') ?><br></td>
                </tr>
                <tr>
                    <td>2014</td>
                    <td><?php echo $this->translate('Foreign Minister, Incumbent, in the government of Dr. Haider Al Abadi.') ?><br></td>
                </tr>
                </tbody>
            </table>
            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Has several books, studies, and researches, including (State
                Approach),(Experience of Rule),(Woman .. the Battle of Identity),(Art .. Pulse of Life),(Youth Between
                Authenticity and Innovation),(Students Makers of Life).<br> Several books were written about him: (Ring
                of Fire),(Iraqi Labor),(For A Better Tomorrow),(Kings and Message).') ?><br><br></p>

            <p style="margin: 0px; text-align: center;"><br></p>

            <p></p><br>
        </td>
    </tr>
</table>
</div>