<?php echo $this->headTitle($this->translate('Arab League')) ?>
<h1><?php echo $this->translate('Arab League') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tbody>

    <tr>
        <td colspan="2" valign="top">

            <p></p>

            <p style="margin: 0px; text-align: justify;"><br></p>
            <ul style="text-align: justify;">
                <li><?php echo $this->translate('Iraq was one of the founding members of the Arab League in 1945. In September 2003, a delegation
                    from the Ministry of Foreign Affairs, led by Minister Zebari, regained Iraq\'s seat at the 120th
                    Session of the Arab League in Cairo.') ?><br><br></li>
                <li><?php echo $this->translate('In March 2004, Minister Zebari also participated in the Arab League
                    Foreign Minister\'s preparatory
                    meeting in Cairo for the Arab Summit in Tunis, which will now be held on 22-23 May 2004.') ?><br><br>
                </li>
                <li><?php echo $this->translate('Since 1980, under the former regime, Iraq failed to pay its dues to
                    the Arab League. In March 2004,
                    the Ministry of Foreign Affairs paid Iraq\'s annual membership totalling $3, 515, 411 to the
                    organisation.') ?><br><br></li>
                <li><?php echo $this->translate('Iraq is fully committed to upholding and defending the charter of the Arab League and playing a
                    vital role in all its agencies and institutions. We place great emphasis on strengthening
                    multi-lateral relations in the Arab and Islamic domains and we actively promote friendly and
                    beneficial relations between the Arab world and the international community.') ?> <br></li>
            </ul>
            <p><br></p>

            <p style="text-align: center;"><span style="font-weight: bold;">
                    <?php echo $this->translate('(Updates on Arab League and its Stand on Iraq after 2006)<br>Iraq’s Participations in the Meetings
                    of Arab League on the Summit Level and the Arab Foreign Ministers Level') ?></span>
            </p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">1-</span> March 2007: H.E Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the 127th Ordinary Session held
                in Cairo. The Meeting discussed the issues listed on the Agenda, to include the item of Iraq’s Situation
                Developments.') ?></p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">2-</span> March 2007: H.E Foreign Affairs
                Minister, Hoshyar Zebari, participates in the 19th Ordinary Session of Arab Summit Conference in Riyadh.
                Iraq’s Delegation submitted many proposals on amending and updating the draft resolution on the
                situation in Iraq, in light of the results of conferences, meetings and political activities took place
                after the issuance of the resolution on Iraq.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">3- </span>July 2007: H.E Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the Extraordinary Meeting of the
                Arab League Council on the Ministerial level held in Cairo. The Meeting discussed the findings of Arab
                efforts to activate the Arab Peace Initiative and the developments of the issue of the Libyan children
                injected with HIV.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">4-</span> September 2007: H.E Foreign Affairs
                Minister, Hoshyar Zebari, participates in the 127th Ordinary Session in Cairo. Through this session the
                item of Iraq’s Situation Developments was reviewed; where Iraq’s Delegation requested activating Clause
                7 and 15 of the al-Khartoum Summit Resolution No. 340 on 29/03/2006 concerning the item of Iraq’s
                Situation Developments and put them into execution. Clause 7 stipulates that the member States,
                following the example of foreign States, shall have diplomatic representations in Baghdad soonest.
                Clause 15 stipulates urging the Arab States to cancel their debts on Iraq.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">5- </span>September 2007: H.E Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the 128th Ordinary Session held
                in Cairo. Iraq’s Delegation succeeded in incorporating some amendments on the draft resolution prepared
                by the General Secretariat in line with the positive developments taking place in Iraq in various
                fields.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">6- </span>January 2008: H.E Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the Extraordinary Meeting of the
                Arab League Council on the Ministerial level held in Cairo. The Meeting discussed the Lebanese crisis in
                light of the discords over the presidential elections in addition to the efforts exerted on activating
                the Arab Peace Initiative and countering the Israeli aggressive practices represented by the economic
                blockade and assaults on civilians in Gaza Sector.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">7- </span>On 27/01/2008, were held the
                meetings of the Extraordinary Session of the Arab League Council on Ministerial level. H.E. Foreign
                Affairs Minister, Hoshyar Zebari, headed Iraq’s Delegation to the Meeting, which was dedicated to follow
                up the developments of the situations in Lebanon and Palestine.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">8-</span> March 2008: H.E. Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the 129th Ordinary Session in
                Cairo. Iraq’s Delegation succeeded in incorporating some amendments on the draft resolution prepared by
                the General Secretariat on the situation in Iraq.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">9-</span> March 2008: H.E. Foreign Affairs
                Minister, Hoshyar Zebari, participates in the 20th Session of Arab Summit in Damascus. The Summit issued
                the Special Resolution on Iraq, which included a reference to support the efforts of the Government of
                Iraq in rebuilding its security establishment on patriotic and professional basis, and create
                appropriate conditions to finalize the security issue across Iraq. In addition to the special condition
                on the situation of Iraqi emigrants in the Arab States, which included giving thanks and appreciation to
                the Arab States hosting Iraqi immigrants for the burdens borne by these States in securing decent living
                for them, and calling these States to facilitate granting visa and residence to Iraqi willing visitors,
                also to expedite the provision of urgent aids depositing them in the special account opened by the
                General Secretariat of Arab League to support the Iraqi emigrants.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">10-</span> May 2008: H.E. Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the Extraordinary Meeting of the
                Council of Arab League on Ministerial level held in Cairo. The Meeting discussed the developments of the
                Lebanese crisis. H.E. delivered important interposition over the containment of the Lebanese crisis.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">11-</span> July 2008: The Foreign Affairs
                Undersecretary, Mr. Labeed Abbawi, acting for the Foreign Affairs Minister, heads the Iraq’s Delegation
                participating in the Extraordinary Meeting of the Arab League Council held in Cairo. The Meeting
                discussed the updates of the situation between Sudan and the International Criminal Court.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">12-</span> September 2008: H.E. Foreign
                Affairs Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the 130th Ordinary
                Session held in Cairo. Iraq’s Delegation succeeded in incorporating some amendments on the draft
                resolution prepared by the General Secretariat of the Arab League (Iraq’s Situation Developments), which
                is a revised wording of the resolution adopted by the Arab League Council on Ministerial level in its
                previous 129th session.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">13-</span> March 2009: H.E. Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the Meeting of the 131st Ordinary
                Session held in Cairo. New amendments and proposals were incorporated in the draft special resolution on
                Iraq, inter-alia, originating a new operative clause, Ser. 4th, over Iraq’s signing the Agreement on the
                US Troops Withdrawal by the end of 2011, as well as the Strategic Framework Agreement on Friendly
                Relation between the Republic of Iraq and the United States of America.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">14-</span> March 2009: H.E. Foreign Affairs
                Minister, Hoshyar Zebari, participates in the 21st Session of Arab Summit in Doha. H.E. Prime Minister
                Nouri al-Maliki delivered a comprehensive speech wherein he stressed on the importance of making the
                Doha Summit a comprehensive Arab outset. H.E. touched on Iraq’s success in surmounting the most
                dangerous crises and challenges threatened its unity and sovereignty. He reassured the Arab leaders that
                the Iraqi forces have become capable of filling the void will be left behind the US troops withdrawal
                from all Iraqi territories. H.E. reserved on the special wording on Iraq in the Doha Declaration; he
                requested the summit Headship to make amendments thereon. The request for amendment was approved, as per
                the wording submitted by H.E., to read as follows: (the Arab Summit praises the steps achieved in Iraq
                on security, stability, national unity, discarding sectarianism and stability of political process via
                the participation of the mosaic of Iraqi people). Also, he confirmed on Iraq’s right to host the next
                Arab Summit. However, due to incompletion of technical and logistic procedures to host this important
                Arab event, it has been decided that Iraq shall host the 23rd Session of Arab Summit in 2011.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">15-</span> May 2009: The Foreign Affairs
                Undersecretary, Mr. Labeed Abbawi, acting for the Foreign Affairs Minister, heads the Iraq’s Delegation
                participating in the Extraordinary Meeting of the Arab League Council on Ministerial level held in
                Cairo. The Meeting discussed the Israeli breaches in Gaza, and following up the war crimes committed by
                the Israeli occupation forces on Gaza Sector.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">16-</span> June 2009: H.E. Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the Extraordinary Meeting of the
                Arab League Council on Ministerial level held in Cairo. The Meeting discussed the new Arab stand after
                the latest address of the US President, Barak Obama.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">17- </span>September 2009: H.E. Foreign
                Affairs Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the Meeting of the 132nd
                Ordinary Session held in Cairo. New amendments and proposals were incorporated in the draft special
                resolution on Iraq. As well as praising the advancement taking place in the political process in Iraq
                and the Government’s role in anchoring and consolidation of the democracy, and holding the parliament
                and presidential elections in Kurdistan Region on 25/07/2009 with the participation of an Arab League’s
                delegation within the observation teams.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">18-</span> March 2010: The Foreign Affairs
                Undersecretary for Political Planning and Bilateral Relations, Mr. Labeed Abbawi, heads the Iraq’s
                Delegation participating in the 133rd Ordinary Session held in Cairo. New Clause was added to the draft
                special resolution on Iraq; where a clause concerning water and Iraq’s right to utilize its share,
                according to the international laws, was incorporated (Clause 14). Also, a new item concerning the
                situation of the displaced Iraqis in the hosting Arab countries was incorporated in accordance with
                Syrian draft and after making the necessary amendments resulted from the interpositions of the Iraq’s
                Delegation Head; where its wording was precise and objective.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">19- </span>March 2010: H.E. Foreign Affairs
                Minister, Hoshyar Zebari, heads the Iraq’s Delegation participating in the 22nd Ordinary Session of Arab
                Summit in Sirt – Libya, where the Resolution on the Situation in Iraq was passed according to the
                wording submitted by the Iraq’s Delegation and to serve the higher interests of Iraq. While the item of
                Displaced Iraqis in the Hosting Arab countries, was only included in the Agenda of the 133rd Session
                held in March 2010 in the General Secretariat’s headquarter in Cairo, from which Sirt Declaration was
                issued to hail the parliament elections took place in Iraq on 07/03/2010 and call Iraq to form the new
                government soonest. As well, the Meeting issued Sirt Document under which was formed a pentagonal
                committee to survey the reality of the Joint Arab Action, to which Iraq is a member represented by H.E.
                President Jalal Talabani.') ?></p>

            <p>&nbsp;<?php echo $this->translate('<span style="font-weight: bold;">20- </span>June 2010: Iraq participates
                in the Extraordinary Ministerial Meeting held in Cairo, where the following was discussed:<br>- Gaza
                Flotilla Raid, which was condemned.<br>- The Ministerial Meeting of the Pentagonal Higher Committee to
                discuss the Development of Joint Arab Action Group') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">21-</span> June 2010: H.E. President Jala
                Talabani heads the Iraq’s Delegation participating in the Meeting of the Higher Pentagonal Committee
                held in Tripoli, capital of Libya. The development of the Joint Arab Action Group was discussed.') ?></p>

            <p><?php echo $this->translate('<span style="font-weight: bold;">22-</span> October 2010: H.E. President Jala
                Talabani heads the Iraq’s Delegation participating in the Extraordinary Arab Summit and the Afro-Arab
                Summit, both held in Sirt – Libya. The following meetings were held:<br>a- The Preparatory Meeting for
                the Afro-Arab Summit on the level of higher executives.<br>b- The Preparatory Meeting of the Arab
                Foreign Ministers.<br>c- The Preparatory Meeting of the Arab and African Foreign Ministers.<br>d- The
                Extraordinary Arab Summit.<br>e- The Afro-Arab Summit.<br>The Extraordinary Arab Summit discussed the
                following two items: The development of Joint Arab Action Group and the Arab Neighbourly Politics and
                Creating the Regional Neighbourly League. The discussions were dominated by controversial issues
                connected with the above mentioned items.') ?></p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">23.</span>March 2011, Foreign Minister
                Hoshyar Zebari, headed the delegation of the Republic of Iraq to the regular session (135) to discuss
                the meeting of the Arab league at the summit level, which is scheduled to be held in Baghdad, and a
                decision was made to hold the summit in Baghdad May 15, 2011.') ?></p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">24.</span>March 2011, Undersecretary
                Labeed, Abbawi headed the delegation of the Republic of Iraq and Ambassador Dr. Jaber Habib Jaber,
                Ambassador Mohammed Humaimidi to the extraordinary ministerial meeting, which dealt with the latest
                developments of events in Libya and its implications.') ?></p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">25.</span> September 2011 Foreign Minister
                Hoshyar Zebari headed the delegation of the Republic of Iraq to the regular session (136) at the
                ministerial level at the General Secretariat headquarters in Cairo, the meeting focused on the situation
                in Syria.') ?></p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">26.</span> October 2011, Iraq participated
                in the ministerial emergency meeting on the situation in Syria, which resulted in the issuance of a
                decision to form a committee of the Ministry headed by Qatar and Algeria, Oman, Sudan and the Secretary
                General of the League, to connect to the Syrian government and its claim to stop the violence in Syria.') ?>
            </p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">27.</span> November 2011, Iraq
                participated in the extraordinary session of the Arab League at the ministerial level to follow the
                latest developments in Syria.') ?></p>

            <p><br><?php echo $this->translate('<span style="font-weight: bold;">28.</span> November 2011, Iraq
                participated in the extraordinary session of the League of Arab States at the ministerial level to
                follow up the developments of the situation in Syria; the meeting was issued by Resolution No. (7438)
                which stated. - Suspend the participation of Syrian delegation in the meetings of the League of Arab
                states until the implementation of the Arab Plan .<br>- Provide protection for Syrian civilians<br>-
                Call on the Syrian army to not get involved in acts of violence and murder.<br>- The signing of economic
                sanctions against the Syrian government.<br>-Call upon Arab states to withdraw their ambassadors from
                Damascus.<br>- Invite Syrian opposition parties to a meeting at the headquarters of the Arab eLague.<br><br><span
                    style="font-weight: bold;">29.</span>November 2011, Iraq participated in the extraordinary session
                of the Arab League at the ministerial level to follow up on the situation in Syria, and stressed
                reservation Iraq on the fourth paragraph of the draft resolution (7441), on the imposition of economic
                sanctions on Syria in the absence of Syrian government signed the protocol of the Arab
                initiative.<br><br><span style="font-weight: bold;">30.</span> November 27, 2011, Iraq participated in
                the extraordinary session of the Council of the League of Arab States at the ministerial level on the
                developments of the situation in Syria and that it issued Resolution No. (7442), containing the
                imposition of economic sanctions on Syria, which included a stop flights to Syria and stop commercial
                exchanges with the Syrian government In addition to freeze financial assets.<br><br><span
                    style="font-weight: bold;">31.</span> December 2011, Iraq participated in the Ministerial Committee
                on Syria, under the chairmanship of the State of Qatar, which reported the results of a list of names of
                officials that will be prevented from entering the Arab countries and freezing their
                assets.<br><br><span style="font-weight: bold;">32.</span>The Meeting of the extraordinary session of
                the Arab League Council at the ministerial level on 2/6/2012 in Doha, to discuss the developments of the
                situation in Syria, and the situation in Sudan, and the Palestinian issue. The Minister chaired the
                esteemed delegation of Iraq, and the membership Undersecretary Labeed Abbawi and Permanent
                Representative Dr. Qais al-Azzawi.<br><br><span style="font-weight: bold;">33.</span>The meeting of
                extraordinary session of the Arab League at the ministerial level took place on 22/7/2012 in Doha, to
                discuss the developments of the situation in Syria, the Palestinian issue, the Arab peace initiative.
                The meeting was chaired by Undersecretary Labeed Abbawi and the membership of Permanent Representative
                Dr. Qais al-Azzawi.<br><br><span style="font-weight: bold;">34.</span>A meeting of the Arab League will
                be held at the ministerial level in the regular session (138) on 09/05/2012 at the Arab League
                headquarters in Cairo.') ?><br></p>

            <p><br></p>

            <p><br></p>

            <p style="text-align: center;"><span style="font-weight: bold;"><?php echo $this->translate('Iraq’s Contribution in the Budget of the League of Arab States') ?></span>
            </p>

            <p><br><?php echo $this->translate('Iraq paid 256,476.10 USD as its participation for 2010. Also, Iraq paid
                159,900.10 USD, representing the 4th installment of the debts on Iraq.<br>Iraq paid $ (61,295,222) U.S.
                dollars contributions for 2011 in addition to 10% worth of for the year 2010.') ?></p>

            <p style="text-align: center;"><span style="font-weight: bold;"><?php echo $this->translate('Permanent Representation of the Republic of Iraq to the Arab League') ?></span>
            </p>

            <p><?php echo $this->translate('The permanent representative, Dr. Qais al-Azzawi, submitted the Letter of
                Credence to the Secretary General of the League of Arab States, Mr. Amr Moussa, on 03/05/2010.') ?></p>

            <p style="text-align: center;"><br></p>

            <p style="margin: 0px; text-align: center;"><span style="font-weight: bold;"><?php echo $this->translate('The League of Arab States’ Mission to Baghdad') ?></span>
            </p>

            <p style="margin: 0px; text-align: center;"></p>

            <p style="margin: 0px; text-align: center;"></p>

            <p><?php echo $this->translate('The executive Minister, Mr. Nagi Ahmed Shalgam took office as head
                of the League of Arab States’ Mission to Baghdad on 01/01/2010.') ?></p>

            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>
                       