<?php echo $this->headTitle($this->translate('Economic Rehabilitation')) ?>
<h1><?php echo $this->translate('Economic Rehabilitation') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tbody>

    <tr>
        <td colspan="2" valign="top">

            <p></p>

            <p style="margin: 0px; text-align: justify;"><br></p><span
                style="font-weight: bold; text-decoration: underline;"><div style="text-align: justify;"><?php echo $this->translate('Rehabilitation
                    of the Ministry of Foreign Affairs:') ?><br></div></span>

            <p style="margin: 0px; text-align: justify;">&nbsp;&nbsp;&nbsp; <?php echo $this->translate('Legacy of the former regime ended with
                rickety institutions lacking efficiency due to the lack of scheme caused by the bad planned policies and
                individual decisions that expelled Iraqi state institutions away from the standards used by rest of the
                world.') ?></p>

            <p style="margin: 0px; text-align: justify;">&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $this->translate('The Foreign Ministry, with its
                organizational structure and the management style, was part of that legacy.') ?></p>

            <p style="margin: 0px; text-align: justify;">&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $this->translate('Iraq\'s new Government worked hard to
                make essential reform for the rehabilitation of the Foreign Ministry to show the bright image which
                befits the status of Iraq and its diplomatic history that the former regime has deformed through losing
                a lot of its luster giving the diplomatic institution a security touch that has dominated all of its
                departments, so the ministry and its structure was rehabilitated after 2003 to be harmonized with Iraq\'s
                pursuit to restore its active role through the constructive diplomatic work and the openness to the
                international community.') ?></p>

            <p style="margin: 0px; text-align: justify;">&nbsp;&nbsp;&nbsp; <?php echo $this->translate('The Iraqi Foreign Ministry worked and still
                working to achieve that vision in a thoughtful way through the following:') ?></p>

            <p style="margin: 0px; text-align: justify;"> <?php echo $this->translate('Preparing&nbsp; efficient diplomatic staff in the Foreign
                Service Institute according to the guidelines and precise conditions to choose, with high transparency,
                appropriate elements from the young Iraqi academics wishing to serve their country&nbsp; in the
                diplomatic corps.') ?></p>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('&nbsp; Providing modern curriculum to create diplomatic ,
                administrative and technical staff capable&nbsp; of practicing their jobs efficiently and in line with
                the evolution of the expanding Iraqi diplomatic work.') ?></p>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('&nbsp; Successes of the Ministry of Foreign Affairs in the new
                Iraq went beyond its diplomatic duties to develop its legal systems that keep pace with the modern era.
                Foreign Service Law No. 45 of 2008 was issued to be a mainstay in determining the mechanisms of work
                within the organizational structure of the Iraqi diplomacy institution to grant it more disciplined
                flexibility, and by virtue of that low , a system of Foreign Service no. (1) of 2010 was also issued to
                clarify the practical purposes of the Foreign Service Law . To complete the ministry\'s pursuit for
                making the work more sophisticated and flexible, the ministry issued a booklet on its instructions to
                address the practical difficulties that appear during all types of the ministerial workflow. ') ?></p>

            <p><span
                    style="font-weight: bold; text-decoration: underline;"><?php echo $this->translate('The Most Important Conventions and Treaties') ?></span><br><span
                    style="text-decoration: underline;"> </span><br>&nbsp;<?php echo $this->translate('The Multilateral conventions<br>&nbsp;Agreements
                with the Islamic Conference&nbsp; <br>&nbsp;Agreements with the Arab countries<br>&nbsp;Agreements with
                the Asian countries<br>&nbsp;Agreements with the African countries<br>&nbsp;Agreements with the European
                countries<br>&nbsp;Agreements with the United States of America<br>&nbsp;Agreements with the Latin
                American countries') ?></p>

            <p><br></p>

            <p><br></p>

            <div style="text-align: justify;"><br><br></div>
            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>
                       