<?php echo $this->headTitle($this->translate('Human Rights')) ?>
<h1><?php echo $this->translate('Human Rights') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tbody>

    <tr>
        <td colspan="2" valign="top">

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Human rights are rights inherent to all human beings, whatever
                their nationality, place of residence, sex, national or ethnic origin, color, religion, language, or any
                other status was. We are all equally entitled to our human rights without discrimination. These rights
                are all interrelated, interdependent and indivisible.') ?></p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Universal human rights are often expressed and guaranteed by
                law, in the forms of treaties, customary international law, general principles and other sources of
                international law. International Human Rights Law lays down obligations of Governments to act in certain
                ways or to refrain from certain acts, in order to promote and protect human rights and fundamental
                freedoms of individuals or groups.') ?></p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('The principle of universality of human rights is the
                cornerstone of international human rights law. This principle, as first emphasized in the Universal
                Declaration on Human Rights in 1948, has been reiterated in numerous international human rights
                conventions, declarations, and resolutions. The 1993 Vienna World Conference on Human Rights, for
                example, noted that it is the duty of States to promote and protect all human rights and fundamental
                freedoms, regardless of their political, economic and cultural systems.') ?></p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Human rights are inalienable. They should not be taken away,
                except in specific situations and according to due process. For example, the right to liberty may be
                restricted if a person is found guilty of a crime by a court of law.') ?></p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('All human rights are indivisible, whether they are civil or
                political rights, such as the right to life, equality before the law and freedom of expression,
                economic, social and cultural rights, such as the rights to work, social security and education, or
                collective rights, such as the rights to development and self-determination, are indivisible,
                interrelated and interdependent. The improvement of one right facilitates advancement of the others.
                Likewise, the deprivation of one right adversely affects the others.&nbsp;') ?> </p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Non-discrimination is a cross-cutting principle in
                international human rights law. The principle is present in all the major human rights treaties and
                provides the central theme of some of international human rights conventions such as the International
                Convention on the Elimination of All Forms of Racial Discrimination and the Convention on the
                Elimination of All Forms of Discrimination Against Women.') ?>&nbsp; </p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('The principle applies to everyone in relation to all human
                rights and freedoms and it prohibits discrimination on the basis of a list of non-exhaustive categories
                such as sex, race, colour and so on. The principle of non-discrimination is complemented by the
                principle of equality, as stated in Article 1 of the International Declaration of Human Rights: “All
                human beings are born free and equal in dignity and rights.”') ?></p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Human rights entail both rights and obligations. States assume
                obligations and duties under international law to respect, to protect and to fulfill human rights. The
                obligation to respect means that States must refrain from interfering with or curtailing the enjoyment
                of human rights. The obligation to protect requires States to protect individuals and groups against
                human rights abuses. The obligation to fulfill means that States must take positive action to facilitate
                the enjoyment of basic human rights. At the individual level, while we are entitled to our human rights,
                we should also respect the human rights of others.') ?></p><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('All States have ratified at least one, and 80% of States have
                ratified four or more of the core human rights treaties, reflecting consent of States which creates
                legal obligations for them and giving concrete expression to universality. Some fundamental human rights
                norms enjoy universal protection by customary international law across all boundaries and
                civilizations.') ?></p>

            <p style="margin: 0px; text-align: justify;"><br></p><br><br><span style="font-weight: bold;"><?php echo $this->translate('Human Rights Bodies') ?></span><br><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('The Office of the High Commissioner for Human Rights (OHCHR)
                works to offer the best expertise and support to the different human rights monitoring mechanisms in the
                United Nations system: UN Charter-based bodies, including the Human Rights Council, and bodies created
                under the international human rights treaties and made up of independent experts mandated to monitor
                State parties\' compliance with their treaty obligations. Most of these bodies receive secretariat
                support from the Human Rights Council and Treaties Division of the Office of the High Commissioner for
                Human Rights (OHCHR).</p><br><br>1 - Charter-based bodies') ?><br><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Charter bodies include the former Commission on Human Rights,
                the Human Rights Council, and Special Procedures. The Human Rights Council, which replaced the
                Commission on Human Rights, held its first meeting on 19 June 2006. This intergovernmental body, which
                meets in Geneva 10 weeks a year, is composed of 47 elected United Nations Member States who serve for an
                initial period of 3 years, and cannot be elected for more than two consecutive terms. The Human Rights
                Council is a forum empowered to prevent abuses, inequity and discrimination, protect the most
                vulnerable, and expose perpetrators.') ?></p>

            <p style="margin: 0px; text-align: justify;"><br></p><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $this->translate('The
            Human Rights Council is a separate entity from OHCHR.') ?> <br><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Special Procedures is the general name given to the mechanisms
                established by the Commission on Human Rights and assumed by the Human Rights Council to address either
                specific country situations or thematic issues in all parts of the world. Special Procedures are either
                an individual –a special rapporteur or representative, or independent expert—or a working group. They
                are prominent, independent experts working on a voluntary basis, appointed by the Human Rights
                Council.') ?></p><br><br><br><br>

            <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('Special Procedures mandates usually call on mandate-holders to
                examine, monitor, advise and publicly report on human rights situations in specific countries or
                territories, known as country mandates, or on major phenomena of human rights violations worldwide,
                known as thematic mandates. There are 30 thematic mandates and 8 country mandates. All report to the
                Human Rights Council on their findings and recommendations. They are sometimes the only mechanism that
                will alert the international community on certain human rights issues&nbsp; </p><br>They are:<br><br>•Human
            Rights Council<br><br>•Universal Periodic Review<br><br>•Commission on Human Rights (replaced by the Human&nbsp;&nbsp;&nbsp;&nbsp;
            Rights Council)<br><br>•Special Procedures of the Human Rights Council<br><br>•Human Rights Council
            Complaint Procedure<br><br><br><span style="font-weight: bold;">2 - Treaty-based bodies</span>') ?><br><br>

            <p style="margin: 0px; text-align: justify;">&nbsp;&nbsp;&nbsp; <?php echo $this->translate('There are nine core international human
                rights treaties, the most recent one -- on enforced disappearance -- entered into force on 23 December
                2010. Since the adoption of the Universal Declaration of Human Rights in 1948, all UN Member States have
                ratified at least one core international human rights treaty, and 80 percent have ratified four or
                more.') ?></p><br>

            <p style="margin: 0px; text-align: justify;">&nbsp;&nbsp;&nbsp; <?php echo $this->translate('There are currently ten human rights treaty
                bodies, which are committees of independent experts. Nine of these treaty bodies monitor implementation
                of the core international human rights treaties while the tenth treaty body, the Subcommittee on
                Prevention of Torture, established under the Optional Protocol to the Convention against Torture,
                monitors places of detention in States parties to the Optional Protocol.') ?></p><br>

            <p style="margin: 0px; text-align: justify;">&nbsp;&nbsp; <?php echo $this->translate('The treaty bodies are created in accordance with
                the provisions of the treaty that they monitor. OHCHR supports the work of treaty bodies and assists
                them in harmonizing their working methods and reporting requirements through their secretariats.') ?> </p>

            <p style="margin: 0px; text-align: justify;">&nbsp;<br><br><?php echo $this->translate('These bodies are:<br><br>•Human Rights Committee
                (CCPR)<br><br>•Committee on Economic, Social and Cultural Rights&nbsp;&nbsp;&nbsp; (CESCR)<br><br>•Committee
                on the Elimination of Racial Discrimination (CERD)<br><br>•Committee on the Elimination of
                Discrimination against Women (CEDAW)<br><br>•Committee against Torture (CAT) <br><br>•Subcommittee on
                Prevention of Torture (SPT)<br><br>•Committee on the Rights of the Child (CRC)<br><br>•Committee on
                Migrant Workers (CMW(<br><br>•Committee on the Rights of Persons with Disabilities (CRPD)<br><br>•Committee
                on Enforced Disappearances (CED)') ?><br><br><br><br><br><span
                    style="font-weight: bold; text-decoration: underline;"><?php echo $this->translate('Secondly : The international Conventions on Human Rights and the Convention on the Department of Social Affairs:') ?></span><br><br><br>&nbsp;&nbsp;
            </p>
            <table cellspacing="0" cellpadding="0"
                   style="width: 320px; border-top-color: #000000; border-left-color: #000000; border-top-width: 1px; border-left-width: 1px; border-top-style: solid; border-left-style: solid;">
                <tbody>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: center;"><span
                                style="font-weight: bold;">&nbsp;<?php echo $this->translate('Agreement') ?></span></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: center;">&nbsp;<span style="font-weight: bold;"><?php echo $this->translate('date of entry into force') ?></span>
                        </p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: center;"><span style="font-weight: bold;"><?php echo $this->translate('Number of States Parties') ?>&nbsp;</span>
                        </p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: center;"><span style="font-weight: bold;"><?php echo $this->translate('Iraq\'s position') ?>&nbsp;</span>
                        </p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Convention on the Elimination of All Forms of
                            Discrimination against Women / New York / 12/18/1979') ?></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;03/09/1981</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;187</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq ratified it on&nbsp; 08/13/1986') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('a-Amendment for paragraph (1) of Article 20
                            of the Convention on the Elimination of All Forms of Discrimination Against Women, New York') ?>
                            12/22/1995</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;12/22/1995</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;68</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq has not signed or ratified the
                            Amendment') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('b-Optional Protocol for the Convention on the
                            Elimination of All Forms of Discrimination Against Women, New York, 6 October 1999.') ?></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;12/22/2000</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;104</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq has not signed or ratified the
                            Protocol') ?> </p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Convention on the Rights of the Child') ?></p>
                    </td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;10/02/1990</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;193</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq ratified it on 15/06/1994') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('a-Amendment for Article 43 (2) of the
                            Convention on the Rights of the Child, New York, 12/12/1995') ?></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;18/11/2002</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;143</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq ratified it on&nbsp; 31/12/2001') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;"><?php echo $this->translate('b-The Optional Protocol to the Convention on the
                            Rights of the Child Concerning&nbsp; the Involvement of Children in Armed Conflict, New
                            York, 05/25/2000') ?>&nbsp;</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;12/2/2002</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;151</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq ratified&nbsp; the Protocol on
                            24/6/2008') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('c-Optional Protocol for the Convention
                            on') ?> </p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;18/01/2002</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;163</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq ratified the Protocol on 24/6/2007') ?></p>
                    </td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('the Rights of the Child Concerning the sale
                            of children, child prostitution and child pornography, New York, 05/25/2000') ?></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;"><br></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;"><br></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;"><br></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('D-Optional Protocol for the Convention on the
                            Rights of the Child on Concerning the Submission of complaints. New York, 19/12/2011') ?></p>
                    </td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;19/12/2011</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;4</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq has not ratified or signed the
                            Protocol') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Convention on the Rights of Disabled Persons,
                            New York 13/12/2006') ?></p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;3/5/2008</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;130</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq\'s ratification on 30/04/2013') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('a-Optional Protocol for the Convention
                            on') ?> </p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;3/5/2008</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;76</p></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <p style="margin: 0px; text-align: justify;">&nbsp;<?php echo $this->translate('Iraq has not ratified or signed the
                            Protocol') ?></p></td>
                </tr>
                <tr>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        &nbsp;<?php echo $this->translate('the Rights of Disabled Persons, New York 13/12/2006') ?>
                    </td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <br></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <br></td>
                    <td style="border-right-color: #000000; border-bottom-color: #000000; border-right-width: 1px; border-bottom-width: 1px; border-right-style: solid; border-bottom-style: solid;">
                        <br></td>
                </tr>
                </tbody>
            </table>
            <p style="margin: 0px; text-align: justify;"><br><br><br><?php echo $this->translate('1 - The International Covenant on Civil and
                Political Rights ICCPR.<br>&nbsp;<br>2 - The International Covenant on Economic, Social and Cultural
                Rights. ICESCR<br>&nbsp;<br>3 - Convention on the Elimination of All Forms of Discrimination against
                Women. CEDAW<br>&nbsp;<br>4 - International Convention on the Elimination of All Forms of Racial
                Discrimination. CERD<br>&nbsp;<br>5 - The Convention Against Torture and Other Cruel, Inhuman or
                Degrading Treatment or Punishment CAT.') ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>

            <p style="margin: 0px; text-align: justify;"><br><?php echo $this->translate('6 - Convention on the Rights of the Child CRC.<br><br>7 -
                International Convention for the Protection of the Rights of All Migrant Workers and Their Family
                Members ICRMW.<br>&nbsp;<br>8 - International Convention for the Protection of the Rights of Migrants
                and forced Disappearances.<br>&nbsp;<br>9 - The International Convention for Disabled Persons.<br>&nbsp;<br><br><br><span
                    style="font-weight: bold;">Optional Protocols Attached to the Agreements:</span><br><br>1 - Optional
                Protocol of the International Covenant on Civil and Political Rights ICCRP-OPI<br>&nbsp;<br>2 - Second
                Optional Protocol of the International Covenant on Civil and Political Rights ICCPR-OP2&nbsp;&nbsp;<br>
                <br>3 - Optional Protocol of the Convention on the Elimination of All Forms of Discrimination against
                Women OP-CEDAW.&nbsp;<br> <br>4- Optional Protocol on the Convention on the Rights of the Child on the
                Involvement of Children in Conflict<br>&nbsp;<br>5 - Optional Protocol to the Convention on the Rights
                of the Child on the sale of children, child prostitution and child pornography OP-CRC-SC') ?></p>

            <p style="margin: 0px; text-align: justify;"><br><?php echo $this->translate('6 - Optional Protocol to the Convention against Torture and
                other Cruel, Inhuman or Degrading Treatment or Punishment.&nbsp;<br> <br>7 - Optional Protocol to the
                International Convention for the Disabled.') ?>&nbsp;<br> <br><br><span
                    style="font-weight: bold; text-decoration: underline;">
                    <?php echo $this->translate('Third: Iraq\'s Position with Regard to the Signing and Ratification of the Conventions on Hhuman Rights:') ?>
                </span><br><br><br>&nbsp;
                <?php echo $this->translate('Iraq has already signed and joined nine international and regional conventions on human rights as well as the
                Arab Charter on Human Rights, except the International Convention on Migrant Workers and their families.<br>
                As for the optional protocols, Iraq has joined the two Optional Protocols related to the Convention on
                the Rights of the Child, and in this context it should be said that the Iraqi government represented by
                the ministries concerned are making unremitting efforts in order to sign and join the remaining
                conventions and supplement protocols in order to promote human rights in Iraq in a manner consistent
                with the international standards.') ?><br><br><br></p>

            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>