<?php echo $this->headTitle($this->translate('International Organizations')) ?>
<h1><?php echo $this->translate('International Organizations') ?></h1>

<p><?php echo $this->translate('Iraq continues to increase its representation in international organisations and since September 2003, we have
    successfully re-established our seat in most multilateral bodies including:') ?></p>
<ul style="text-align: justify;">
    <li><a href="#Arab league" target="_self"><?php echo $this->translate('Arab League') ?> </a></li>
    <li><a href="#General Assembly"
           target="_self"><?php echo $this->translate('United Nations General Assembly') ?> </a></li>
    <li><a href="#Islamic Cooperation"
           target="_self"><?php echo $this->translate('Organization of Islamic cooperation') ?></a></li>
    <li><a href="#Non-Aligned Movement" target="_self"><?php echo $this->translate('Non-Aligned Movement') ?></a></li>
    <li><a href="#G77" target="_self"><?php echo $this->translate('G77') ?> </a></li>
    <li><span><a href="#Inter Monetary Fund"
                 target="_self"><?php echo $this->translate('International Monetary Fund') ?></a></span></li>
    <li><a href="#World Bank" target="_self"><?php echo $this->translate('World Bank') ?></a></li>
    <li><a href="#UNESCO" target="_self"><?php echo $this->translate('UNESCO') ?></a></li>
    <li><a href="#UNCTAD" target="_self"><?php echo $this->translate('UNCTAD') ?></a></li>
    <li><a href="#WTO" target="_self"><?php echo $this->translate('World Trade Organization') ?></a></li>
    <li><a href="#OPEC" target="_self"><?php echo $this->translate('OPEC') ?></a></li>
</ul>
&nbsp;<br>
<span style="font-weight: bold;"><a
        name="Arab league"><?php echo $this->translate('League of Arab States') ?></a></span></p>
&nbsp;&nbsp;&nbsp;</p>
<br>
<span style="font-weight: bold;"><a
        name="General Assembly"><?php echo $this->translate('General Assembly of the United Nations') ?></a></span></p>
&nbsp; <?php echo $this->translate('The General Assembly is the main deliberative, policy making and representative organ of the United Nations. Comprising all&nbsp;193 Members of the United Nations, it provides a unique forum for multilateral discussion of the full spectrum of international issues covered by the Charter.') ?>
<a title="UN general assembly" href="/documents/international-organizations/130420236286763864.pdf"
   target="_blank"><?php echo $this->translate('For
    more details...') ?></a></p>
<br></p>
<span style="font-weight: bold;"><a
        name="Islamic Cooperation"><?php echo $this->translate('Organization of the Islamic Cooperation') ?></a></span></p>
&nbsp; &nbsp;<?php echo $this->translate('The organization of the Islamic cooperation (OIC) is the second largest inter-governmental organization after the United Nations which has membership of (57) states spread over four countries. The organization is the collective voice of the Muslim word and ensuring to safeguard and protect the interests of the Muslim world in the spirit of promoting international peace and harmony among various people of the world.') ?>
<a title="OIC" href="/documents/international-organizations/130420225399175214.pdf"
   target="_blank"><?php echo $this->translate('For more
    details...') ?></a></p>
<br>
<span style="font-weight: bold;"><a
        name="Non-Aligned Movement"><?php echo $this->translate('Non - Aligned Movement') ?></a></span></p>
&nbsp; &nbsp;<?php echo $this->translate('The Non - Aligned Movement is one of the results of the Second World War (1939 - 1945)&nbsp;and as a result more directly of the cold war, which escalated between the Western camp (United States of America and NATO) and the Eastern bloc (The Soviet Union and the Warsaw Pact) at the end of the Second World War and the destruction of the Axis powers. The goal of the movement was to move away from the Cold War policies.') ?>
<a title="None-aligned movement" href="/documents/international-organizations/130420218155690938.pdf"
   target="_blank"><?php echo $this->translate('For
    more details...') ?></a></p>
<br></p>
<span style="font-weight: bold;"><a name="G77"><?php echo $this->translate('The Group of 77') ?></a></span></p>
<span>&nbsp; <?php echo $this->translate('The G77 &nbsp;is an alliance group of developing nations, designed to prompt its members\' collective economic interests and create an enhanced joint negotiating capacity in the United Nations.') ?></span></p>
<br>
<span style="font-weight: bold;"><a
        name="Inter Monetary Fund"><?php echo $this->translate('International Monetary Fund') ?>&nbsp;</a></span></p>
&nbsp; &nbsp;<?php echo $this->translate('The International Monetary Fund is a specialized agency of the Bretton Woods Conference was established under an international treaty in (1945) to work on enhancing the safety of the global economy. Its headquarter is in Washington, D.C. , United States. It is managed by its members who include almost all countries of the world\'s (186) countries.') ?>
<a href="/documents/international-organizations/130171462397420336.pdf"
   target="_blank"><?php echo $this->translate('For more details...') ?></a></p>
<br></p>
<span style="font-weight: bold;"><a name="World Bank"><?php echo $this->translate('World Bank') ?></a><br></span>
&nbsp; &nbsp;<?php echo $this->translate('The World Bank is one of the specialized agencies of the United Nations, which dealing with development. It has started its activities to assist in the reconstruction of Europe after the Second World War.') ?>
<a href="/documents/international-organizations/130171485710204628.pdf"
   target="_blank"><?php echo $this->translate('For more details...') ?></a></p>
<br><span style="font-weight: bold;"><a name="UNESCO"><?php echo $this->translate('UNESCO') ?></a></span>
&nbsp; &nbsp;<?php echo $this->translate('UNESCO works, since its founding in (1945), to create the appropriate conditions for dialogue among civilization, cultures, and peoples, based upon respect for commonly shared values. Its headquarter is in Paris - France.') ?>
<a href="/documents/international-organizations/130171478508614022.pdf"
   target="_blank"><?php echo $this->translate('For more details...') ?></a></p>
<br><span style="font-weight: bold;"><a name="UNCTAD"><?php echo $this->translate('UNCTAD') ?></a></span></p>
&nbsp; &nbsp;<?php echo $this->translate('The UNCTAD provides, as part of its technical field cooperation, assistance to the needs of developing countries, with special attentions to the needs of the least developed countries and the developing countries most in need.') ?>
<br><br></p>
<span style="font-weight: bold;"><a name="WTO"></a><?php echo $this->translate('World Trade Organization (WTO)') ?><br></span>
&nbsp; &nbsp;<?php echo $this->translate('The World Trade Organization is an international organization whose main task is to ensure that trade flows as smoothly as the convenience and freedom. As it is the only international organization relevant to international lows on trade between the nations. The World Trade Organization has (157) member countries of the world. Its headquarter is in Geneva - Switzerland.') ?>
<a href="/documents/international-organizations/130172210594803446.pdf"
   target="_blank"><?php echo $this->translate('For more details...') ?></a></p>
<br><span style="font-weight: bold;"><a name="OPEC"></a></span><span
    style="font-weight: bold;"><?php echo $this->translate('Organization of the Petroleum Exporting Countries (OPEC)') ?></span>
<span style="font-weight: bold;"><br></span>
<span style="font-weight: bold;"></span></p>
&nbsp; &nbsp;<?php echo $this->translate('OPEC is an international organization, which has (12) countries, depends on its oil exports to achieve their income. The OPEC members work to increase revenues from the sale of oil in the world market. It was founded in Baghdad in (1960), by Saudi Arabia, Iran, Iraq, Kuwait, and Venezuela. Its headquarter is in Vienna - Austria.') ?>
<a href="/documents/international-organizations/130171515585344412.pdf"
   target="_blank"><?php echo $this->translate('For more details...') ?></a></p>
<p></p>