<?php echo $this->headTitle($this->translate('Iraq and the United Nations')) ?>
<h1><?php echo $this->translate('Iraq and the United Nations') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tbody>

    <tr>
        <td colspan="2" valign="top">

            <p></p>

            <div id="maintext" style="text-align: justify;"><p style="margin: 0px;">The vital role of the United Nations
                    in Iraq has always been welcomed by the Iraqi people, in particular its commitment to humanitarian
                    programmes which provided a lifeline to millions of Iraqis throughout the prolonged Iraq crisis
                    under the former regime. We strongly condemn the devastating bombing of the United Nations
                    Headquarters in Baghdad in August 2003 and pay tribute to the late Sergio Vieira de Mello who was an
                    effective and committed role model for the United Nation's work in Iraq.<br<br> The United Nations
                    has issued three Security Council Resolutions on the future of Iraq since May 2003 (UNSCRs1483, 1500
                    and 1511), which provide a wide mandate for UN involvement in political, economic and administrative
                    fields. The UN has an effective role to play in Iraq in humanitarian affairs, capacity building and
                    democratic reform among other areas and we welcome the two teams which recently arrived in Iraq to
                    assist in the political and electoral processes. The United Nations also currently operates out of
                    Amman and Cyprus with Mr. Ross Mountain supervising these efforts as Acting Special
                    Representative.</br<br></p>

                <p style="margin: 0px;"><br></p>
                <li>In December 2003, the Minister of Foreign Affairs presented the United Nations General Assembly with
                    the timetable for the restoration of sovereignty to Iraq in accordance with the November 15th
                    Agreement on Political Process, signed between the Iraqi Governing Council and the Coalition
                    Provisional Authority in Baghdad.<br><br></li>
                <li>In January 2004, Iraq participated in tripartite meetings at the United Nations between the Iraqi
                    Governing Council, Coalition Provisional Authority and the United Nations Secretariat to discuss the
                    way forward for the UN's role in Iraq in political, electoral and constitutional fields.<br><br>
                </li>
                <li>In February 2004, the UN's Special Advisor to Iraq, Mr. Lakhdar Brahimi, and a UN electoral team
                    conducted a fact-finding mission on the feasibility of elections in Iraq prior to June 30th
                    2004.<br><br></li>
                <li>In March 2004 and in response to a request from the Iraqi Governing Council, a UN team of electoral
                    experts arrived in Iraq to help with preparations for direct elections to be held by the end of
                    January 2005. The UN Secretary General also dispatched a team of UN officials, led by Mr. Lakhdar
                    Brahimi, to assist with the transfer of sovereignty on June 30th 2004.<br><br><br></li>
            </div>
            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>