<?php echo $this->headTitle($this->translate('Iraq\'s Security')) ?>
<h1><?php echo $this->translate('Iraq\'s Security') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tr>
        <td colspan="2" valign="top">

            <p></p>

            <p style="text-align: justify;"><span style="font-weight: bold;"></span></p>

            <p style="text-align: justify;"><span style="font-weight: bold; text-decoration: underline;">Iraq's security:</span>
            </p>

            <p style="text-align: justify;"><span
                    style="font-weight: bold; text-decoration: underline;">&nbsp;&nbsp;</span><br>&nbsp;&nbsp;&nbsp;
                <?php echo $this->translate('Among the most important priorities of the Government of the Republic of Iraq is enhancing cooperation
                with the neighboring countries in particular and the international community in general in the security
                areas to protect Iraq\'s and the region\'s security from internal and external threats, especially
                terrorist ones, and to enhance the security successes achieved after Iraq regained national sovereignty,
                which was culminated in the withdrawal of all coalition forces by the U.S. troops withdraw agreement
                from Iraq signed between the Republic of Iraq and the U.S.') ?><br></p>

            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>