<?php echo $this->headTitle($this->translate('Iraq\'s Diplomatic Missions')) ?>
<h1><?php echo $this->translate('Iraq\'s Diplomatic Missions') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tbody>

    <tr>
        <td colspan="2" valign="top">

            <p></p>

            <div id="maintext" style="text-align: justify">
                <div id="maintext"><?php echo $this->translate('Significant steps have been taken to restore Iraq\'s missions abroad since the April
                    2003 ban was lifted on all diplomatic and consular activities. Iraq now has diplomatic
                    representation in 35 countries around the world, including 3 Permanent Missions to the United
                    Nations in New York, the United Nations Commission on Human Rights in Geneva and the Arab League in
                    Cairo. Thirty missions remain suspended.<br><br>The strategy to enhance or resume diplomatic
                    representation abroad is a key priority of the Ministry of Foreign Affairs, through the following
                    objectives:') ?>
                </div>
                <ul>
                    <li><?php echo $this->translate('The appointment of ambassadors, senior staff and diplomats to overseas missions.') ?> <br><br></li>
                    <li><?php echo $this->translate('The resumption of comprehensive operations in key international missions to provide Iraqi local
                        communities with necessary consular services including certification, passport extensions and
                        provision of interim travel documents, visa issue and local liaison services.') ?> <br><br></li>
                    <li><?php echo $this->translate('Efficient provision of information and the establishment of international exchanges to promote
                        Iraqi interests in social, cultural and religious affairs.') ?> <br><br></li>
                    <li><?php echo $this->translate('Increase Iraq\'s diplomatic activities to contribute to our rehabilitation into the international
                        economy by promoting trade and investment through bilateral exchange and cooperation through
                        multilateral organizations.') ?>
                    </li>
                </ul>
            </div>
            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>