<?php echo $this->headTitle($this->translate('Iraq\'s Security')) ?>
<h1><?php echo $this->translate('Iraq\'s Security') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tr>
        <td colspan="2" valign="top">

            <p></p>

            <p style="text-align: justify;"><span style="font-weight: bold;"></span></p>
            <p>
                <?php echo ($this->locale == 'en_US') ? 'Iraq\'s security:' : 'أمن العراق:<br>تعمل حكومة جمهورية العراق، ضمن اهم أولوياتها على توثيق التعاون مع دول الجوار بصفة خاصة والمجتمع الدولي عموما في المجالات الامنية وحماية لأمن البلد والمنطقة من التهديدات الداخلية والخارجية ولاسيما الارهابية منها،وتعزيزاً للنجاحات الامنية المتحققة بعد ان استعاد العراق سيادته الوطنية التي تكللت بأنسحاب جميع قوات التحالف حسب اتفاقية سحب القوات الامريكية من العراق المبرمة بين جمهورية العراق والولايات المتحدة الامريكية.' ?>
            </p>

            <p style="text-align: justify;"><span
                    style="font-weight: bold; text-decoration: underline;">&nbsp;&nbsp;</span><br>&nbsp;&nbsp;&nbsp;
                <?php echo $this->translate('Among the most important priorities of the Government of the Republic of Iraq is enhancing cooperation
                with the neighboring countries in particular and the international community in general in the security
                areas to protect Iraq\'s and the region\'s security from internal and external threats, especially
                terrorist ones, and to enhance the security successes achieved after Iraq regained national sovereignty,
                which was culminated in the withdrawal of all coalition forces by the U.S. troops withdraw agreement
                from Iraq signed between the Republic of Iraq and the U.S.') ?><br></p>

            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>