<?php echo $this->headTitle($this->translate('Reforming the Ministry')) ?>
<h1><?php echo $this->translate('Reforming the Ministry') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tbody>

    <tr>
        <td colspan="2" valign="top">

            <p></p>

            <div id="maintext" style="text-align: justify;">
                <div id="maintext"><?php echo $this->translate('Under the previous regime, the reputation of the Ministry of Foreign Affairs was
                    degraded in the eyes of Iraqis and the international community. The institution, its missions and
                    its activities, were abused to spy and intimidate in deliberate breach of internationally-accepted
                    diplomatic practice. The professionalism of Ministry staff was undermined and any initiative was
                    suffocated by an oppressive and corrupt working culture. <br><br>Today, Ministry of Foreign Affairs
                    personnel are undertaking diplomatic training overseas through professional development programs
                    provided by host countries. These programs include language and information technology skills,
                    diplomatic training in all fields and exposure to internationally accepted diplomatic practices.
                    Since August last year, 251 members of the Ministry\'s staff have been selected to go to twenty
                    countries to receive diplomatic training. The countries are Pakistan, Poland, the Czech Republic,
                    India, Jordan, South Korea, the United Kingdom, the United States, France, Germany, Romania, Turkey,
                    China, Spain, the Netherlands, Egypt, Malaysia, The Sudan, Austria and Switzerland. Some 60 members
                    of staff have already started their training in Pakistan, Poland, the Czech Republic, India, Jordan,
                    Korea and the United Kingdom, while 35 other staff have returned from Pakistan, the Czech Republic,
                    Jordan and India. <br><br>The new Ministry of Foreign Affairs is further committed to enhance its
                    foreign policy capabilities through reforming and modernising its organisation, personnel and
                    activities according to the following principles:') ?>
                </div>
                <ul>
                    <li><?php echo $this->translate('The development and implementation of transparent selection and recruitment processes in
                        conjunction with a ministry-wide de-Ba\'athification program.') ?> <br><br></li>
                    <li><?php echo $this->translate('New standard recruitment procedures based on merit, equal opportunities and a just and fair
                        criteria offering various entry levels and opportunity to all sectors of Iraqi society, in
                        particular to women.') ?> <br><br></li>
                    <li><?php echo $this->translate('Recruitment campaigns conducted through public announcement.') ?> <br><br></li>
                    <li><?php echo $this->translate('Employee vetting, training assessments and personnel evaluation undertaken via open and standard
                        procedures.') ?> <br><br></li>
                    <li><?php echo $this->translate('Preparations are also ongoing to re-open and reform the Foreign Service Institute in order to
                        resume normal diplomatic training activity. Since early 2003, the building\'s restoration has
                        been completed and serves as temporary accommodation for the Ministry.') ?> <br><br></li>
                    <li><?php echo $this->translate('All Ministry of Foreign Affairs personnel must possess an understanding of human rights issues,
                        democratic principles and the prerequisite of political impartiality in civil service.') ?> <br><br>
                    </li>
                    <li><?php echo $this->translate('All Ministry of Foreign Affairs personnel must possess an understanding of human rights issues,
                        democratic principles and the prerequisite of political impartiality in civil service.') ?> <br><br>
                    </li>
                    <li><?php echo $this->translate('Employee commitment to the Ministry of Foreign Affairs\' new work ethic of integrity,
                        professional respect and a commitment to serve in the best interests of the Iraqi people.') ?>
                        <br><br></li>
                    <li><?php echo $this->translate('The Ministry is committed to working practices that encourage initiative, professional skill
                        development, communication and objectivity in provision of foreign policy advice.') ?> <br><br></li>
                    <li><?php echo $this->translate('All new initiatives and restructuring changes are communicated throughout the Ministry.') ?></li>
                </ul>
            </div>
            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>