<?php echo $this->headTitle($this->translate('Security Council Resolutions')) ?>
<h1><?php echo $this->translate('Security Council Resolutions') ?></h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">

    <tbody>

    <tr>
        <td colspan="2" valign="top">

            <p><span style="font-weight: bold;"><br>Security Council Resolutions</span><br></p>
            <table cellspacing="2" cellpadding="2" style="width: 420px;">
                <tbody>
                <tr>
                    <td align="center" style="border: 1px solid #7c7c7c; height: 30px;"><p
                            style="margin: 0px; text-align: center;"><span
                                style="text-decoration: underline;">&nbsp;</span><span
                                style="font-weight: bold; text-decoration: underline;">Security council Resolutions in regarding to Iraq</span><br>
                        </p></td>
                </tr>
                <tr>
                    <td style="border: 1px solid #7c7c7c;"><span
                            style="font-weight: bold;">&nbsp;Res.2170(2014)</span><br>Security Council resolution on&nbsp;sanctions&nbsp;Associated
                        with&nbsp;(ISIS) dated&nbsp;15 August 2014.<br><span style="font-weight: bold;"><a
                                href="http://www.mofa.gov.iq/documentfiles/130576630016581138.pdf" target="_self">for
                                more details...</a></span></td>
                </tr>
                <tr>
                    <td style="border: 1px solid #7c7c7c;">&nbsp;<span
                            style="font-weight: bold;">Res.2107(2013)</span><br> Security Council resolution on Iraq's
                        Exit from Provisions of Chapter VII.<br>&nbsp;<a
                            href=" http://www.mofa.gov.iq/documentfiles/130225216084468138.pdf" target="_blank"><span
                                style="font-weight: bold;">for more details...</span></a></td>
                </tr>
                <tr>
                    <td style="border: 1px solid #7c7c7c;"><span style="font-weight: bold;">Res.1956(2010)</span><br>Adopted
                        by the Security Council at its 6450th meeting, on 15 December 2010.<br><a
                            href="http://www.mofa.gov.iq/documentfiles/130225293430354392.pdf" target="_blank"><span
                                style="font-weight: bold;">for more details...</span></a></td>
                </tr>
                <tr>
                    <td style="border: 1px solid #7c7c7c;"><span style="font-weight: bold;">Res.1957(2010)</span><br>Adopted
                        by the Security Council at its 6450th meeting, on 15 December 2010.<br><a
                            href="http://www.mofa.gov.iq/documentfiles/130225301113051064.pdf" target="_blank"><span
                                style="font-weight: bold;">for more details...</span></a></td>
                </tr>
                <tr>
                    <td style="border: 1px solid #7c7c7c;"><span style="font-weight: bold;">Res.1958(2010)</span><br>Adopted
                        by the Security Council at its 6450th meeting, on 15 December 2010.<br><a
                            href="http://www.mofa.gov.iq/documentfiles/130225304132659614.pdf" target="_blank"><span
                                style="font-weight: bold;">for more details...</span></a></td>
                </tr>
                <tr>
                    <td style="border: 1px solid #7c7c7c;"><span style="font-weight: bold;">Res.1618(2005)-4 August 2005<br></span>Condemns
                        without reservation and in&nbsp;the strongest terms the terrorist attacks that have taken place
                        in Iraq,and regards any act of terrorism as a threat&nbsp;to peace and security.<a
                            href="http://www.mofa.gov.iq/documentfiles/129760968003614385.pdf" target="_blank">.<span
                                style="font-weight: bold;">for more details...</span></a></td>
                </tr>
                <tr>
                    <td style="border: 1px solid #7c7c7c;">&nbsp;<span style="font-weight: bold;">Res.1538(2004)-12 April 2004</span><br>

                        <p style="margin: 0px; text-align: justify;">Expressing the desire to see a full and fair
                            investigation of efforts by the former Government of Iraq,including through
                            bribery,kickbacks,surcharges on oil,sales,and illict payments in&nbsp;regard to purchases of
                            huminitarian goods, to evade the provisions of resolution 661 (1991)of 6 August 1990 and
                            subsequent relevant resolutions...</p><a
                            href="http://www.mofa.gov.iq/documentfiles/129760953366958211.pdf" target="_blank"><span
                                style="font-weight: bold;">for more details...&nbsp;</span></a><br>&nbsp;</td>
                </tr>
                </tbody>
            </table>
            <p></p><br>
        </td>
    </tr>


    </tbody>
</table>