<?php echo $this->headTitle($this->translate('The New Iraq')) ?>
<div class="sidebar col-md-4">
    <?php echo $this->partial('sidebar', ['routes' => $this->routes]) ?>
</div>
<div class="col-md-8">
<h1><?php echo $this->translate('The New Iraq') ?></h1>

<p>
    <?php echo $this->translate('•The new Iraq inherited a heavy legacy of hostility and distrust as a result of the irresponsible policies of the
    former regime towards the neighboring and far countries which led to a decline in the country\'s position in the
    international community.') ?>
    <br>
    <?php echo $this->translate('•The Foreign Ministry in the new Iraq faced these challenges and still, to
    address that legacy in a bid to retrieve \'s position that befits rich civilization heritage and its people and
    its riches. ') ?>
    <br>
    <?php echo $this->translate('•As representatives of the new Iraq, we have actively and successfully worked on
    removing the isolation condition to achieve the goals of our foreign policy in a responsible vision in accordance
    with the following:') ?>
    <br><br>
    <?php echo $this->translate('1-To protect Iraq\'s security and promote stability and preserve the unity and
    harmony of society.') ?>
    <br>
    <?php echo $this->translate('2-To move forward in the expansion of bilateral diplomatic relations area with the
    world countries and bring the international community to contribute in the reconstruction of Iraq and its
    infrastructure and development.') ?>
    <br>
    <?php echo $this->translate('3-Contribute to building the economy in a thoughtful way that ensures
    raising the standard of the Iraqi people\'s living.') ?>
    <br>
    <?php echo $this->translate('4-Promoting the activity of the Iraqi diplomatic
    missions and enhances Iraq\'s interests in political, economic, social and cultural spheres.') ?>
    <br>
    <?php echo $this->translate('5-Continue the
    support of Iraq\'s role in multilateral bodies towards a more active work, and strive to expand Iraq\'s international
    participation by joining more of those bodies, particularly the economic ones.') ?>
    <br>
    <?php echo $this->translate('6-Continue upgrading the
    work of the Ministry of Foreign Affairs and the level of performance, guided by the constitutional basis and legal
    controls designed to achieve Iraq\'s vision in a way that matches its prestigious stature as a civilization and
    people.') ?>
    <br>
    <?php echo $this->translate('7-Strengthen the foundations of democracy within the framework of sovereignty, unity and equality
    among citizens.') ?>
    <br>
    <?php echo $this->translate('•Iraq confirms its peaceful foreign policy aiming at normalization of diplomatic
    relations with the international community on the basis of cooperation and respect for mutual interests and
    sponsoring them in accordance with the international law and stand at the same distance from all international
    parties in an equitable manner.') ?>
</p>
</div>