<?php $this->headTitle($this->translate('Edit a mission category ' . $this->category->getName())) ?>
<?php $this->headScript()
    ->prependFile('/js/admin/category-edit.js')
    ->prependFile('http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js');
?>

<h1 class="text-center"><?php echo $this->translate('Edit a category "' . $this->category->getName() . '"') ?></h1>

<form action="" method="POST" class="form-horizontal" role="form" id="editCategory">
    <input type="hidden" name="id" value="<?php echo $this->category->getId() ?>" />

    <div class="form-group">
        <label class="control-label col-xs-3" for="name">Name *</label>
        <div class="col-xs-7">
            <input class="required form-control" name="name" type="text" value="<?php echo $this->category->getName() ?>" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-xs-3" for="urlKey">Url key</label>
        <div class="col-xs-7">
            <input class="form-control" type="text" name="urlKey" value="<?php echo $this->category->getUrlKey() ?>" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-xs-3" for="locale">Locale *</label>
        <div class="col-xs-7">
            <select class="required form-control" name="locale">
                <option value="">Please choose</option>
                <?php foreach ($this->locales as $locale) : ?>
                <option<?php echo ($locale->getId() == $this->category->getLocale()->getId()) ? ' selected="selected"' : '' ?>
                    value="<?php echo $locale->getId() ?>">
                    <?php echo $locale->getName() ?>
                </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <?php if ($this->category->getLocale()->getId() == 1) :  // check locale is english ?>
        <div class="form-group">
            <label class="control-label col-xs-3" for="category">Translation of Category</label>
            <div class="col-xs-7">
                <select class="form-control" name="category">
                    <option value="">Please choose</option>
                    <?php
                    /** @var \Blog\Entity\Category $category */
                    foreach ($this->arCategories as $category) :
                    ?>
                        <option<?php echo ($this->category && $category->getId() == $this->category->getId()) ? ' selected="selected"' : '' ?>
                            value="<?php echo $category->getId() ?>">
                            <?php echo $category->getName() ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>

    <div class="form-group">
        <label class="control-label col-xs-3" for="urlKey">&nbsp;</label>
        <div class="col-xs-7">
            <input class="form-control btn btn-primary" type="submit" name="submit" value="Edit" />
        </div>
    </div>
</form>