<?php $this->headTitle($this->translate('Add a Mission category')) ?>
<?php $this->headScript()
        ->prependFile('/js/admin/mission-category-new.js')
        ->prependScript("var angularModule = angular.module('customCMS', []);")
        ->prependFile('//ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js')
        ->prependFile('http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js');
?>

<h1 class="text-center"><?php echo $this->translate('Add a category') ?></h1>

<form class="form-horizontal" role="form" id="newCategory" ng-controller="NewCategoryController">
    <input type="hidden" name="id" ng-model="category.id" />

    <div class="form-group">
        <label class="control-label col-xs-3" for="name">Name *</label>
        <div class="col-xs-7">
            <input class="required form-control" name="name" type="text" ng-model="category.name" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-xs-3" for="urlKey">Url key</label>
        <div class="col-xs-7">
            <input class="form-control" type="text" name="urlKey" ng-model="category.urlKey" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-xs-3" for="locale">Locale *</label>
        <div class="col-xs-7">
            <select class="required form-control" name="locale" ng-model="category.locale">
                <option value="">
                    Please choose
                </option>
                <option ng-repeat="locale in locales" value="{{locale.id}}">
                    {{locale.name}}
                </option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-xs-3" for="urlKey">&nbsp;</label>
        <div class="col-xs-7">
            <input ng-click="submit()" class="form-control btn btn-primary" type="submit" name="urlKey" value="Create" />
        </div>
    </div>
</form>