<div class="container clearfix">
    <div class="col-md-3 pull-left">
        <h3 class="white-head"><?php echo $this->translate('Site Map') ?></h3>
        <ul>
            <li>
                <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('ministry') ?>"><?php echo $this->translate('The Ministry') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('ministry/undersecretaries') ?>">
                    <?php echo $this->translate('Undersecretaries') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('foreign-policy') ?>">
                    <?php echo $this->translate('Foreign Policy') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('about-iraq') ?>"><?php echo $this->translate('About Iraq') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('diplomatic-missions') ?>">
                    <?php echo $this->translate('Diplomatic Missions') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('consular-services') ?>">
                    <?php echo $this->translate('Consular Services') ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('contact-us') ?>"><?php echo $this->translate('Contact Us') ?></a>
            </li>
        </ul>
    </div>
    <div class="col-md-5 pull-left clearfix">
        <h3 class="white-head"><?php echo $this->translate('Links') ?></h3>
        <div class="col-sm-6 pull-left">
            <ul>
                <li>
                    <a href="<?php echo $this->url('about-iraq/constitution') ?>">
                        <?php echo $this->translate('Iraq\'s Constitution') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('ministry/speeches-interviews') ?>">
                        <?php echo $this->translate('Speeches') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('about-iraq/investment') ?>">
                        <?php echo $this->translate('Investment in Iraq') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('about-iraq/encyclopedia') ?>">
                        <?php echo $this->translate('Iraq Encyclopedia') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('foreign-policy/international-organizations') ?>">
                        <?php echo $this->translate('International organizations') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('ministry/announcements') ?>">
                        <?php echo $this->translate('Ministry\'s Announcements') ?></a>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 pull-left">
            <ul>
                <li>
                    <a href="<?php echo $this->url('ministry/magazine') ?>">
                        <?php echo $this->translate('Ministry\'s Magazine') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('ministry/speeches-interviews') ?>">
                        <?php echo $this->translate('Speeches') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('about-iraq/investment') ?>">
                        <?php echo $this->translate('Investment in Iraq') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('about-iraq/encyclopedia') ?>">
                        <?php echo $this->translate('Iraq Encyclopedia') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('foreign-policy/international-organizations') ?>">
                        <?php echo $this->translate('International organizations') ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('ministry/announcements') ?>">
                        <?php echo $this->translate('Ministry\'s Announcements') ?></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-4 pull-left clearfix">
        <div class="col-sm-6 pull-left">
            <h3 class="white-head"><?php echo $this->translate('Languages') ?></h3>
            <ul>
                <li>
                    <a href="/"><?php echo $this->translate('English') ?></a>
                </li>
                <li>
                    <a href="/ar/"><?php echo $this->translate('عربي') ?></a>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 pull-left text-center">
            <a href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('/trash/images/logo.png') ?>" alt="Republic of Iraq"/>&nbsp;
            </a>
            <p class="site-title">
                <?php echo $this->translate('Republic of Iraq') ?><br />
                <?php echo $this->translate('Ministry of Foreign Affairs') ?>
            </p>
        </div>
    </div>
</div>