<header class="clearfix">
    <div class="logo pull-left flip">
        <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
            <img src="<?php echo $this->basePath('/trash/images/en_logo.jpg') ?>" alt="Republic of Iraq"/>&nbsp;
        </a>
    </div>
    <div class="head-logo pull-left flip">
        <?php if ($this->locale == 'en_US'): ?>
            <?php echo $this->translate('Republic of Iraq') ?><br />
            <?php echo $this->translate('Ministry of Foreign Affairs') ?>
        <?php else : ?>
            <img src="<?php echo $this->basePath() ?>/trash/images/logo_ar.jpg" alt="" />
        <?php endif; ?>
    </div>
    <div id="language-switcher">
        <?php if ($this->locale == 'en_US'): ?>
        <a class="btn" href="/ar/" title="عربي">عربي</a>
        <?php else : ?>
        <a class="btn" href="/" title="English">English</a>
        <?php endif; ?>
    </div>
</header>
<nav id="top-nav" class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <?php echo $this->partial('layout/navigation') ?>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div id="news-ticker" class="clearfix">
    <div class="title pull-left flip">
        <?php echo $this->translate('News') ?>
    </div>
    <div class="news-ticker-content pull-left flip">
        <script>
            var newsTickerUrl = '<?php echo $this->url('news-ticker') ?>';
        </script>
        <ul class="news-ticker">
            <li>
                <i class="glyphicon glyphicon-refresh spinning"></i>
            </li>
        </ul>
    </div>
</div>