<?php
$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch();
if ($routeMatch) {
    $routeName = $routeMatch->getMatchedRouteName();
} else {
    $routeName = '404';
}
?>
<ul class="nav navbar-nav">
    <li<?php echo ($routeName == 'home') ? ' class="active current-menu-item"' : '' ?>>
        <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
    </li>

    <!-- the-ministry -->
    <?php echo $this->partial('dropdown-menu', ['route' => 'the-ministry']) ?>

    <!-- about-iraq -->
    <?php echo $this->partial('dropdown-menu', ['route' => 'about-iraq']) ?>

    <?php
    $routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
        ->getMvcEvent()->getRouteMatch();
    $routes = $this->config('router')['routes']['blog'];
    $currentSlug = $routeMatch->getParams('slug', null);
    $arrayLink = [];

    $activeMenu = false;
    if (isset($custom_links)) {
        foreach ($routes['custom_links'] as $link) {
            $arrayLink[] = $link['link']['en'];
            $arrayLink[] = $link['link']['ar'];
        }
        if (in_array($currentSlug, $arrayLink)) {
            $activeMenu = true;
        }
    }
    ?>
    <li<?php echo ($routeName == 'blog' || $activeMenu) ? ' class="active current-menu-item dropdown"' : ' class="dropdown"' ?>>
        <a href="<?php echo $this->url('blog') ?>" title="<?php echo $this->translate('News') ?>">
            <?php echo $this->translate('News') ?>
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            <!-- Custom pages were set in landing module config route -->
            <?php if (isset($routes['custom_links'])) : ?>
                <?php
                foreach ($routes['custom_links'] as $link) :
                    $url =  (Locale::getPrimaryLanguage(Locale::getDefault()) == 'en') ? $link['link']['en'] : $link['link']['ar'];
                    ?>
                    <li<?php echo ($currentSlug == $url) ? ' class="active"' : '' ?>>
                        <a href="<?php echo $this->url('blog/view', ['slug' => $url]) ?>">
                            <?php echo $this->translate($link['label']) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </li>

    <!-- foreign-policy -->
    <?php echo $this->partial('dropdown-menu', ['route' => 'foreign-policy']) ?>

    <?php
    $routes = $this->config('router')['routes']['mission'];
    $currentSlug = $routeMatch->getParams('slug', null);
    $arrayLink = [];

    $activeMenu = false;
    if (isset($custom_links)) {
        foreach ($routes['custom_links'] as $link) {
            $arrayLink[] = $link['link']['en'];
            $arrayLink[] = $link['link']['ar'];
        }
        if (in_array($currentSlug, $arrayLink)) {
            $activeMenu = true;
        }
    }
    ?>
    <li<?php echo ($routeName == 'mission' || $activeMenu) ? ' class="active current-menu-item dropdown"' : ' class="dropdown"' ?>>
        <a href="<?php echo $this->url('mission') ?>">
            <?php echo $this->translate('Diplomatic Missions') ?>
            <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" role="menu">
            <!-- Custom pages were set in landing module config route -->
            <?php if (isset($routes['custom_links'])) : ?>
                <?php
                foreach ($routes['custom_links'] as $link) :
                    $url =  (Locale::getPrimaryLanguage(Locale::getDefault()) == 'en') ? $link['link']['en'] : $link['link']['ar'];
                    ?>
                    <li<?php echo ($currentSlug == $url) ? ' class="active"' : '' ?>>
                        <a href="<?php echo $this->url('blog/view', ['slug' => $url]) ?>">
                            <?php echo $this->translate($link['label']) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </li>

    <!-- consular-services -->
    <?php echo $this->partial('dropdown-menu', ['route' => 'consular-services']) ?>

    <?php
    $contactUrl = ($this->locale == 'en_US') ?
        $this->url('blog/view', ['slug' => 'en-mofa-contact-us']) :
        $this->url('blog/view', ['slug' => 'ar-mofa-contact-us']);
    ?>
    <li<?php echo (in_array($currentSlug, ['en-mofa-contact-us', 'ar-mofa-contact-us'])) ? ' class="active current-menu-item"' : '' ?>>
        <a href="<?php echo $contactUrl ?>" title="<?php echo $this->translate('Contact Us') ?>">
            <?php echo $this->translate('Contact Us') ?>
        </a>
    </li>
</ul>