<?php
$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')
    ->getMvcEvent()->getRouteMatch();
if ($routeMatch) {
    $routeName = $routeMatch->getMatchedRouteName();
} else {
    $routeName = '404';
}
?>
<ul class="nav navbar-nav">
    <li<?php echo ($routeName == 'home') ? ' class="active current-menu-item"' : '' ?>>
        <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
    </li>
    <?php echo $this->rendermenu($routeMatch) ?>
</ul>
