<?php
/** @var \User\Form\EditForm $form */
$form = $this->form;
?>
<?php $this->headTitle('Edit Moderator "' . $form->get('displayName')->getValue() . '"') ?>
<h1 class="text-center"><?php echo 'Edit Moderator "' . $form->get('displayName')->getValue() . '"' ?></h1>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>

<?php
/** @var \Zend\Form\Element $element */
foreach($form->getElements() as $element): ?>
    <?php
    $messages = $element->getMessages()
    ?>
    <div class="form-group<?php if($messages) echo " has-error" ?>">
        <?php if($messages): ?>
            <?php foreach($messages as $message): ?>
                <div class="col-xs-3">&nbsp;</div>
                <div class="alert-danger col-xs-7">
                    <?php if (is_array($message)): ?>
                        <?php
                        foreach ($message as $k=>$mess) {
                            echo $mess . '<br />';
                        }
                        ?>
                    <?php else: ?>
                        <?php echo $message ?>
                    <?php endif; ?>
                </div>
            <?php endforeach;?>
        <?php endif; ?>
        <label class="control-label col-xs-3"><?php echo $element->getLabel() ?></label>
        <div class="col-xs-7">
            <?php echo $this->formElement($element); ?>
        </div>
    </div>
<?php endforeach;?>

<?php echo $this->form()->closeTag(); ?>