<?php

return [
    'bjyauthorize' => [
        'unauthorized_strategy' => 'BjyAuthorize\View\RedirectionStrategy',
        'guards'                => [

            'BjyAuthorize\Guard\Route' => [
                ['route' => 'admin', 'roles' => ['moderator']],

                // user
                ['route' => 'zfcuser', 'roles' => ['guest']],
                ['route' => 'zfcuser/logout', 'roles' => ['user']],
                ['route' => 'zfcuser/changepassword', 'roles' => ['user']],
                ['route' => 'zfcuser/login', 'roles' => ['guest']],

                // api
                ['route' => 'api/blog', 'roles' => ['guest']],
                ['route' => 'api/category', 'roles' => ['guest']],
                ['route' => 'api/locale', 'roles' => ['guest']],

                // admin
                ['route' => 'zfcadmin', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/blog', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/blog/query', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/blog/new', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/blog/edit', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/blog/delete', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/category', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/category/new', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/category/edit', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/menu', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/menu/new', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/menu/edit', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/menu/delete', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/mission-blog', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/mission-blog/new', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/mission-blog/edit', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/mission-category', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/mission-category/new', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/mission-category/edit', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/mission-category/static', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/mission-category/static/edit', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/mission-category/static/manage', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/mission-category/static/new', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/dashboard', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/default', 'roles' => ['moderator']],
                ['route' => 'zfcadmin/moderator', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/moderator/create', 'roles' => ['administrator']],
                ['route' => 'zfcadmin/moderator/edit', 'roles' => ['administrator']],

                /* For Landing Pages */
                ['route' => 'home', 'roles' => ['guest']],
                ['route' => 'the-ministry', 'roles' => ['guest']],
                ['route' => 'the-ministry/faq', 'roles' => ['guest']],
                ['route' => 'the-ministry/the-minister', 'roles' => ['guest']],
                ['route' => 'the-ministry/mofa-ministers', 'roles' => ['guest']],
                ['route' => 'the-ministry/announcements', 'roles' => ['guest']],
                ['route' => 'the-ministry/magazine', 'roles' => ['guest']],
                ['route' => 'about-iraq', 'roles' => ['guest']],
                ['route' => 'about-iraq/investment', 'roles' => ['guest']],
                ['route' => 'about-iraq/constitution', 'roles' => ['guest']],
                ['route' => 'about-iraq/encyclopedia', 'roles' => ['guest']],
                ['route' => 'about-iraq/announcements', 'roles' => ['guest']],
                ['route' => 'about-iraq/the-virtual-museum-of-iraq', 'roles' => ['guest']],
                ['route' => 'about-iraq/tourist-guide', 'roles' => ['guest']],
                ['route' => 'foreign-policy', 'roles' => ['guest']],
                ['route' => 'foreign-policy/the-new-iraq', 'roles' => ['guest']],
                ['route' => 'foreign-policy/arab-league', 'roles' => ['guest']],
                ['route' => 'foreign-policy/economic-rehabilitation', 'roles' => ['guest']],
                ['route' => 'foreign-policy/human-rights', 'roles' => ['guest']],
                ['route' => 'foreign-policy/iraq-and-the-united-nations', 'roles' => ['guest']],
                ['route' => 'foreign-policy/iraq-s-diplomatic-missions', 'roles' => ['guest']],
                ['route' => 'foreign-policy/iraq-s-security', 'roles' => ['guest']],
                ['route' => 'foreign-policy/iraqi-treaties', 'roles' => ['guest']],
                ['route' => 'foreign-policy/reforming-the-ministry', 'roles' => ['guest']],
                ['route' => 'foreign-policy/security-council-resolutions', 'roles' => ['guest']],
                ['route' => 'foreign-policy/international-organizations', 'roles' => ['guest']],
                ['route' => 'diplomatic-missions', 'roles' => ['guest']],
                ['route' => 'diplomatic-missions/iraqi-ambassadors', 'roles' => ['guest']],
                ['route' => 'consular-services', 'roles' => ['guest']],
                ['route' => 'consular-services/approving-corpse-entry-to-iraq', 'roles' => ['guest']],
                ['route' => 'consular-services/authorization', 'roles' => ['guest']],
                ['route' => 'consular-services/birth-certificate', 'roles' => ['guest']],
                ['route' => 'consular-services/certificate-of-origin', 'roles' => ['guest']],
                ['route' => 'consular-services/death-certificate', 'roles' => ['guest']],
                ['route' => 'consular-services/extension-of-passports', 'roles' => ['guest']],
                ['route' => 'consular-services/faq', 'roles' => ['guest']],
                ['route' => 'consular-services/fees', 'roles' => ['guest']],
                ['route' => 'consular-services/forms', 'roles' => ['guest']],
                ['route' => 'consular-services/general-affairs', 'roles' => ['guest']],
                ['route' => 'consular-services/indigent-deportation', 'roles' => ['guest']],
                ['route' => 'consular-services/lawsuits', 'roles' => ['guest']],
                ['route' => 'consular-services/life-certificate', 'roles' => ['guest']],
                ['route' => 'consular-services/loss-of-passports', 'roles' => ['guest']],
                ['route' => 'consular-services/marriage-divorces-registration', 'roles' => ['guest']],
                ['route' => 'consular-services/nationality-cert', 'roles' => ['guest']],
                ['route' => 'consular-services/non-conviction-certificate', 'roles' => ['guest']],
                ['route' => 'consular-services/palestinian-travel-documents', 'roles' => ['guest']],
                ['route' => 'consular-services/pass-doc', 'roles' => ['guest']],
                ['route' => 'consular-services/passport-system', 'roles' => ['guest']],
                ['route' => 'consular-services/passports-issuance', 'roles' => ['guest']],
                ['route' => 'consular-services/patrimonies', 'roles' => ['guest']],
                ['route' => 'consular-services/ratifications', 'roles' => ['guest']],
                ['route' => 'consular-services/the-civil-status-id', 'roles' => ['guest']],
                ['route' => 'consular-services/visa', 'roles' => ['guest']],
                ['route' => 'contact-us', 'roles' => ['guest']],

                /* For blog pages */
                ['route' => 'blog', 'roles' => ['guest']],
                ['route' => 'news-ticker', 'roles' => ['guest']],
                ['route' => 'latest-news', 'roles' => ['guest']],
                ['route' => 'blog/view', 'roles' => ['guest']],
                ['route' => 'mission', 'roles' => ['guest']],
                ['route' => 'mission-menu', 'roles' => ['guest']],
                ['route' => 'mission-header', 'roles' => ['guest']],
                ['route' => 'mission/view', 'roles' => ['guest']],
            ],
        ],
    ],
];
